BCSDLab/KOIN_API_V2

- src/main/java/in/koreatech/koin/domain/auth/UserAuth.java
- src/main/java/in/koreatech/koin/domain/auth/resolver/UserArgumentResolver.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/repository/UserTokenRepository.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/main/java/in/koreatech/koin/global/config/WebConfig.java
- src/test/java/in/koreatech/koin/acceptance/AuthApiTest.java
- close #20 
1. 로그아웃 호출 시 refreshToken을 제거합니다.
현재 User, Student 두가지 권한이 존재하는데 권한 분리작업은 추후 Owner 권한을 작업하는 과정에서 진행하겠습니다.
- https://github.com/BCSDLab/KOIN_API_V2/issues/1
> feat: logout 구현

- build.gradle
- src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
- src/main/java/in/koreatech/koin/domain/community/dto/ArticlesResponse.java
- src/main/java/in/koreatech/koin/domain/community/exception/ArticleNotFoundException.java
- src/main/java/in/koreatech/koin/domain/community/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/model/Board.java
- src/main/java/in/koreatech/koin/domain/community/model/Criteria.java
- src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/repository/BoardRepository.java
- src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
- src/main/java/in/koreatech/koin/global/exception/ErrorResponse.java
- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
- close #104 
1. 비즈니스 로직 및 테스트 작성
- 공지사항 조회 방법: boardId를 4로 검색
-  참고 
2. `ErrorResponseWrapper` 추가
- 타 API와 달리 에러 발생 시 응답 객체가 "error"로 한 번 더 감싸져 있어 해당 응답에 대응하기 위해 추가했습니다.
- 타 API 에러 응답
- GET /articles 에러 응답
3. Jsoup 의존성 추가
- html 태그 제거를 위해 Jsoup 라이브러리 의존성을 추가했습니다.
1. 응답 객체에서 articles.summary와 board.children이 항상 null인 것 같아서 그렇게 응답하도록 작성했는데 이렇게 진행해도 괜찮은 것인지 궁금합니다.
2. articles의 board_id가 FK로 잡혀있지 않아서 의존관계는 매핑하지 않았습니다.
3. Response가 조금 복잡하다 보니 실수가 있을 수도 있을 것 같습니다. 한 번씩만 확인해주시면 감사하겠습니다!
> feat: 게시글 목록 조회 구현

- src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
- src/main/java/in/koreatech/koin/domain/shop/dto/MenuCategoriesResponse.java
- src/main/java/in/koreatech/koin/domain/shop/model/MenuCategoryMap.java
- src/main/java/in/koreatech/koin/domain/shop/repository/MenuCategoryRepository.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- close #40
1. 메뉴 카테고리 조회 기능 추가했습니다.
-  MenuCategoryRepository 생성했습니다.
2. 상점 유효성 검증 부분은 상점 조회 로직 만들 때 추가하는 게 맞는 것 같아 `TODO` 에 남겼습니다. (머지시 이슈 댓글에 남길 예정입니다.)
- 도메인 설계가 없고, 단순한 로직이라 크게 리뷰 중점사항이 없어 보입니다..
- 상점/메뉴/메뉴카테고리 등 분리는 추후 상점 로직 다룰 때 하는 게 맞는 것 같아 진행하지 않았습니다.
> feat: 메뉴 카테고리 목록 조회

- src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
- src/main/java/in/koreatech/koin/domain/community/dto/ArticleResponse.java
- src/main/java/in/koreatech/koin/domain/community/dto/ArticlesResponse.java
- src/main/java/in/koreatech/koin/domain/community/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/model/ArticleViewLog.java
- src/main/java/in/koreatech/koin/domain/community/model/Comment.java
- src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/repository/ArticleViewLogRepository.java
- src/main/java/in/koreatech/koin/domain/community/repository/BoardRepository.java
- src/main/java/in/koreatech/koin/domain/community/repository/CommentRepository.java
- src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
- src/main/java/in/koreatech/koin/domain/dept/controller/DeptController.java
- src/main/java/in/koreatech/koin/domain/dept/dto/DeptListItemResponse.java
- src/main/java/in/koreatech/koin/domain/dept/dto/DeptResponse.java
- src/main/java/in/koreatech/koin/domain/dept/model/Dept.java
- src/main/java/in/koreatech/koin/domain/dept/service/DeptService.java
- src/main/java/in/koreatech/koin/global/util/ClientUtil.java
- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
- src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
- close #106 
"가장 많이 본 게시글" API를 작업하기에 앞서 본 API 개발이 선행되어야 하기에 이번 작업을 진행했습니다.
1. 게시글 단일 조회 시 게시판 정보와 댓글 목록을 함께 반환합니다.
2. (댓글 작성자와 로그인된 사용자의 일치 여부를 기반으로) 댓글 정보 반환 시 댓글 수정 권한(`grantEdit`)과 댓글 제거 권한(`grantEdit`) 정보를 함께 반환합니다.
3. 게시글 조회 시 로그인된 유저 id와 게시글 id, 로그인 ip 정보를 `article_view_logs` 테이블에 저장합니다.
1. ![image](https://github.com/BCSDLab/KOIN_API_V2/assets/21010656/2ab6e831-b7d3-447e-a6ab-83cc0aaa5bbe)
2. 이 때 1시간 뒤를 만료시간으로 함께 저장합니다.
3. 위 사진에서 `0:0:0:0:0:0:0:1`는 IPv6 기준 localhost(IPv4는 127.0.0.1)을 의미합니다. 로컬 환경에서 테스트해서 저렇게 기입되었습니다.
4. 게시글 조회 시
1. 조회 기록이 없다면
1. 조회 기록을 저장합니다. (조회수 UP)
3. 조회 기록이 있다면
1. 만료 시간이 지나지 않았다면
1. 아무 것도 하지 않습니다.
3. 만료 시간이 지났다면
1. 조회 기록의 만료 시간을 1시간 뒤로 수정합니다. (조회수 UP)
5. `HttpServletRequest`을 통해 로그인 정보와 접속 IP를 조회합니다.
6. 이번 PR 주제와 다른 내용이 포함되어 있습니다. (이전 PR에서 누락된 커밋 반영)
- 학과 코드 …
> feat: 게시글 단일 조회

- src/main/java/in/koreatech/koin/domain/dept/controller/DeptController.java
- src/main/java/in/koreatech/koin/domain/land/controller/LandController.java
- src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
- src/main/java/in/koreatech/koin/domain/track/controller/TrackController.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/model/User.java
- src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/test/java/in/koreatech/koin/acceptance/AuthApiTest.java
- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
- src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
- src/test/java/in/koreatech/koin/acceptance/LandApiTest.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TrackApiTest.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- close #16 
1. 회원 탈퇴를 구현했습니다.
2. `@SQLDelete`를 활용해 삭제를 구현했습니다.
3. `@Where`를 이용해 `is_deleted=true` 인 데이터를 조회하지 않도록 구성했습니다.
4. RestAssured의 log().all() 구문을 전부 제거했습니다.
이전에 논의되었던 내용이긴한데 차후 어드민 기능 구현할 때 적용하는게 좋을까요?
(`@Where` 대신 `@Filter`를 활용하여 선택적 softDelete 데이터 조회 조건 구성)
- https://github.com/BCSDLab/KOIN_API_V2/discussions/160
> feat: 회원 탈퇴 구현

- src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
- src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
- src/main/java/in/koreatech/koin/domain/shop/dto/MenuDetailResponse.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- close #39 
1. 특정 상점의 모든 메뉴를 조회하는 api를 구현했습니다.
2. 해당 상점의 마지막 메뉴 업데이트 날짜를 제공하도록 하였습니다.
3. 꼼꼼한 테스트를 위해 메뉴 3개를 넣어서 최대한 많은 경우를 테스트했습니다.
테스트코드가 조금 복잡하다고 느꼈습니다. 테스트코드를 어떻게 개선할 수 있을지, 또 테스트코드가 올바르게 작성되었는지 위주로 봐주시면 감사하겠습니다.
> feat : 특정상점 전체메뉴조회 api작성

- src/main/java/in/koreatech/koin/global/auth/JwtProvider.java
- src/main/java/in/koreatech/koin/global/config/AwsSesConfig.java
- src/main/java/in/koreatech/koin/global/config/S3Config.java
- src/main/java/in/koreatech/koin/global/config/SwaggerConfig.java
- src/main/java/in/koreatech/koin/global/domain/slack/service/SlackService.java
- src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
- src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadController.java
- src/main/java/in/koreatech/koin/global/domain/upload/dto/UploadFileResponse.java
- src/main/java/in/koreatech/koin/global/domain/upload/dto/UploadUrlResponse.java
- src/main/java/in/koreatech/koin/global/domain/upload/service/UploadService.java
- src/main/java/in/koreatech/koin/global/s3/S3Utils.java
- src/main/resources/application-test.yml
- src/test/java/in/koreatech/koin/global/domain/upload/UploadServiceTest.java
- close #7 
1. 파일 업로드를 구현했습니다
2. AmazonS3를 사용하여 bucket에 파일을 업로드합니다.
로컬에서 테스트 수행해본 결과 잘 올라가는거 확인했습니다.
외부 라이브러리 사용한것 외에는 크게 하드한 기술은 없습니다.
코드가 깔끔하게 작성되었는지 확인 부탁드립니다
> feat: 파일 단건 업로드 구현

- src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
- src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadController.java
- src/main/java/in/koreatech/koin/global/domain/upload/dto/UploadFilesResponse.java
- src/main/java/in/koreatech/koin/global/domain/upload/service/UploadService.java
- close #8 
- close #6
1. 다중 파일 업로드를 구현했습니다.
기존 파일 업로드에서 반복문 돌리는게 대부분이라 큰 변경사항은 없습니다.
> feat: 파일 다중 업로드 구현

- src/main/java/in/koreatech/koin/domain/activity/dto/ActivitiesResponse.java
- src/main/java/in/koreatech/koin/domain/activity/dto/ActivityResponse.java
- src/main/java/in/koreatech/koin/domain/land/controller/LandApi.java
- src/main/java/in/koreatech/koin/domain/land/controller/LandController.java
- src/main/java/in/koreatech/koin/domain/land/dto/LandResponse.java
- src/main/java/in/koreatech/koin/domain/land/dto/LandsGroupResponse.java
- src/main/java/in/koreatech/koin/domain/land/dto/LandsResponse.java
- src/main/java/in/koreatech/koin/domain/land/service/LandService.java
- src/test/java/in/koreatech/koin/acceptance/LandApiTest.java
- src/test/java/in/koreatech/koin/global/domain/upload/UploadServiceTest.java
- close #188 
1. 복덕방 전체 조회(get-lands)의 응답 객체가 미스매치 되어 있는 것을 수정해줬습니다.(반환 값을 list에서 key:value의 형태로 바꾸어 줬습니다.) -> ex) {lands : [ ]}의 형태로 만들어줬습니다.
2. 복덕방 전체 조회의 응답 객체를 맡은 dto의 이름에 자료형(list)가 들어가 있어서 LandsResponse로 이름을 바꿔줬습니다.
3. 전체 조회 관련 테스트 코드를 추가 작성해줬습니다.
4. 원래 제가 맡은 부분은 아니지만 UploadServiceTest가 통과를 못해서 수정해줬습니다(준호와 이야기 됨)
5. 어제 제가 맡았던 부분 마음에 안 드는 것이 있어서 ActivityResponse의 example 관련 코드를 살짝 수정해줬습니다.(준호와 이야기 됨)
6. 추가로 맡았던 Activity 도메인에서 일반 클래스로 작성 된 ActivitiesResponse dto를 일반 클래스에서 record 클래스로 변경 시켜 줬습니다
key:value 형태로 묶어주기 위해서 dto를 하나 더 만들었는데 dto의 이름을 적당하게 잘 작명 한 것인지 모르겠습니다. 그 외 수정 했으면 하는 부분이 있다면, 말씀 해주시면 성실하게 수정하도록 하겠습니다.!
> fix: 복덕방 전제 조회 응답 객체 미스매치 수정

- src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
- src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
- src/main/java/in/koreatech/koin/domain/shop/model/MenuCategory.java
- src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
- src/main/java/in/koreatech/koin/domain/shop/model/ShopCategory.java
- src/main/java/in/koreatech/koin/domain/shop/model/ShopOpen.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- close #226 
shop은 양방향 관계가 존재하는 entity인데 그렇지 못하게 설계했었습니다.
그래서 기존에는 shop과 관련된 데이터를 끌어오기 위해서 연관된 테이블을 하나하나 조회했습니다.
이게 비효율적이라고 느껴서 shop과 관련된 다른 작업들을 하기 전에 미리 리팩토링하는게 좋을 것 같다고 생각해서 작업했습니다.
1. shop연관관계 맵핑을 수정했습니다.
2. 연관관계 수정에 따른 관련된 API수정했습니다.
3. side effect를 염두해서 스웨거 반환값을 기존api와 비교했습니다.
연관관계가 잘 설정되어있는지를 중점적으로 리뷰해주시면 감사하겠습니다!
> refactor: 상점 Entity 연관관계 설정

- src/main/java/in/koreatech/koin/domain/community/model/BoardTag.java
- src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
- close #187 
코인 페이지 상에서 게시판 공지사항이 뜨지 않는 현상을 수정했습니다.
응답 객체 형태 미스매치 이슈는 아니었고 내부 로직 문제였습니다.
공지사항(boardId=4) 조회 시 isNotice가 1인 모든 board를 조회해야 했기에 해당 로직으로 수정했습니다.
> fix: 게시판 공지사항 판단 로직 수정

- src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
- src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
- src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
- src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerVerificationRequest.java
- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerVerifyResponse.java
- src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
- src/main/java/in/koreatech/koin/domain/owner/repository/OwnerInVerificationRedisRepository.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
- src/main/java/in/koreatech/koin/domain/user/model/UserType.java
- src/main/java/in/koreatech/koin/global/auth/AuthArgumentResolver.java
- src/main/java/in/koreatech/koin/global/auth/ExtractAuthenticationInterceptor.java
- src/main/java/in/koreatech/koin/global/auth/JwtProvider.java
- src/main/java/in/koreatech/koin/global/auth/UserId.java
- src/main/java/in/koreatech/koin/global/auth/UserIdArgumentResolver.java
- src/main/java/in/koreatech/koin/global/auth/UserIdContext.java
- src/main/java/in/koreatech/koin/global/auth/exception/AuthenticationException.java
- src/main/java/in/koreatech/koin/global/auth/exception/AuthorizationException.java
- src/main/java/in/koreatech/koin/global/config/WebConfig.java
- src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
- src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadController.java
- src/main/resources/db/migration/V5__update_owners_table.sql
- src/test/java/in/koreatech/koin/AcceptanceTest.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- close #123 
1. Redis에 저장되어있는 값을 기반으로 인증코드를 검증하는 로직을 추가했습니다.
2. 임시 엑세스 토큰 발급로직을 추가했습니다.
- 사장님이 임시 인증을 수행하고 회원가입을 진행하는 과정에서 파일 업로드를 수행해야합니다.
- 파일 업로드 작업은 인증된 유저만 수행할 수 있도록 구성되어있기 때문에 임시 엑세스 토큰을 발급하여 이를 수행할 수 있도록 구성해야 했습니다.
3. @UserId 어노테이션 추가
- 인증을 거치지 않고 사용자의 ID만 추출해야하는 경우가 존재하여 만들었습니다. (/articles API)
4. `@Auth(anonymous = true)` 동작방식 변경
- 기존에 `@Auth(anonymous = true)`는 인증 토큰이 없어도 API를 사용 가능하도록 설정하는 옵션이였습니다.
- 이는 인증을 오구하는 `@Auth` 어노테이션의 맥락에서 벗어나는 행위인 것 같아 위에서 이야기한 `@UserId` 어노테이션을 별도로 구성했습니다.
- 회원가입 과정에서 이미지 업로드를 수행할 수 있도록 임시 토큰을 발급하는 로직을 추가했습니다.
- 임시 회원은 token 내부의 id가 0인 토큰에 대하여 임시 토큰이다 라고 선언했습니다.
- 해당 0이라는 값은 UserType에 상수로 ANONYMOUS_ID 로 선언해뒀습니다.
- 생성 로직은 `jwtProvider.createTemporaryToken()` 참고해주세요
- 정리하면 `@Auth(anonymous = true)` 옵션은 **임시토큰을 허용한다** 라는 옵션으로 인지해주시면 되겠습니다.
5. …
> feat: 사장님 인증코드 검증

- src/main/java/in/koreatech/koin/domain/dept/controller/DeptApi.java
- src/main/java/in/koreatech/koin/domain/dept/controller/DeptController.java
- src/main/java/in/koreatech/koin/domain/dept/dto/DeptListItemResponse.java
- src/main/java/in/koreatech/koin/domain/dept/dto/DeptsResponse.java
- src/main/java/in/koreatech/koin/domain/dept/model/Dept.java
- src/main/java/in/koreatech/koin/domain/dept/service/DeptService.java
- src/test/java/in/koreatech/koin/acceptance/DeptApiTest.java
- close #247 
1. 에너지 신소재 화학 공학부가 에너지 신소재 공학부, 화학생명공학부로 나뉘면서 두개의 과를 추가해줬습니다.
2. 하지만 23 학번 이전은 회원 가입 시에 학번을 입력하면 학부가 자동 완성 되었으면 좋겠다는 요구가 있었기에 기존에 있던 과인 에너지 신소재 화학 공학부를 삭제 하지 않았습니다.
3. get depts api에서는 필요한 과만 반환 하기 위해 에너지 신소재 화학 공학부는 걸러주는 작업을 했습니다.
4. 실제 갖고 있는 과 정보는 11개 이지만(에너지 신소재 화학 공학부 삭제 x) get depts api가 반환하는 값은 10개 이기에 모든 학과 정보 조회 테스트 코드에서 사이즈를 1 줄여 줬습니다.
5. 이제 학번 고유 코드 번호로 null을 갖고 있는 과가 생겼기에, 고유코드번호가 비어있는지 확인하는 테스트 코드는 없앴습니다.
6. 학부 전공별 커리큘럼 링크를 최신걸로 업데이트 하였습니다
7. DeptListItemResponse를 DeptsResponse로 이름을 변경 해주었습니다.
신설과들은 학번 고유 코드번호가 없기에, Optional.empty()를 넣어 줬습니다. 하지만 get depts api를 보면, 반환하는 json의 형태가 학번 코드 자리에 null이 들어가서 괜찮은 것인지 우려가 됩니다.
> fix: 전공별 커리큘럼 링크 수정, 새로운 과 추가

- src/main/java/in/koreatech/koin/domain/user/model/Student.java
- src/main/java/in/koreatech/koin/domain/user/repository/StudentRepository.java
- src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
- close #285 
1. UserIdentity 값을 Ordinal로 정정했습니다.
2. Student의 ID가 User의 ID를 FK 겸 PK로 다루고있어 `@MapsId`로 UserId의 ID를 PK로 다루고있음을 뒤늦게 확인했습니다.
- #283 에 대한 작업내용을 함께 Revert 했습니다.
빠른 리뷰 항상 감사합니다
> fix: student Entity 필드 수정

- src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- close #291 
1. 공백 처리 로직을 추가 해줬습니다
2. log를 제거 했습니다.
우리 회장님한테 에러 처리하는 것 옆에서 좀 배웠는데 앞으로는 더 빠르게 대처 할 수 있도록 하겠습니다
> feat: lecture blank error

- .gitignore
- build.gradle
- src/main/java/in/koreatech/koin/domain/activity/controller/ActivityController.java
- src/main/java/in/koreatech/koin/global/exception/ErrorResponse.java
- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- src/main/java/in/koreatech/koin/global/log/RequestLoggingFilter.java
- src/main/java/in/koreatech/koin/global/log/WebLogConfig.java
- src/main/resources/application-test.yml
- src/main/resources/logback-spring.xml
- close #295 
stage 환경에서 로깅의 역할은 클라이언트와의 협업 간 빠른 문제인식 및 조치를 위한 도구라고 생각합니다.
이에 requestBody, responseBody에 대해 로깅을 추가하고, 
datadog과 유사한 기능을 제공하려는 측면도 존재합니다.
1. logback 설정 및 request 로깅을 추가했습니다.
2. `dev` profile로 실행했을 때만 로그파일이 생성됩니다. (Stage 환경에 대해서만)
- https://www.baeldung.com/spring-profiles 참고
3. slack 알림발송 라이브러리를 추가했습니다.
- Error레벨 이상의 로그가 발생하면 슬랙으로 알림을 발송합니다.
참고자료: https://blog.pium.life/server-logging/
Dev Profile로 실행하면 로그 파일이 생깁니다.
> feat: stage logback 적용

- src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
- src/main/java/in/koreatech/koin/domain/shop/repository/EventArticleRepository.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- src/test/java/in/koreatech/koin/support/JsonAssertions.java
- close #301 
1. 가게가 가지고있는 이벤트 중 진행중인 이벤트가 있다면 is_event : true를, 그렇지 않으면 false를 반환하도록 필드를 추가했습니다.
2. 커스텀하게 json값을 비교할 수 있는  JsonAssertion을 만들었습니다.
- RestAssured로 나온 response에 대해 asPrettyString으로 값을 조작하면 jsonString 형태의 값이 나옵니다.
- 해당 값을 기존의 Assertions, AssertJ를 활용하기에는 기존의 자잘한 공백까지 맞춰야하는 불편함이 존재합니다.
- 두개의 String을 인자로 받아 json 객체로 변환한 후 비교하는 Assert 클래스를 만들었습니다.
- 내부적으로는 AssertJ의 isEquals를 사용중이긴 합니다.
정신없는 상태에서 작성한 코드가 많아서 리뷰 잘부탁드립니다 🙇‍♂️
> feat: is_event값 추가

- src/main/java/in/koreatech/koin/domain/coop/controller/CoopController.java
- src/main/java/in/koreatech/koin/domain/coop/dto/SoldOutRequest.java
- src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
- src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
- src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
- src/main/resources/db/migration/V7__alter_diningmenus_change_field_type.sql
- src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
- close #299 
1. 식단 품절 & 변경 여부를 Boolean에서 LocalDateTime으로 변경했습니다.
> refactor: 식단 품절, 변경 여부 (Boolean -> 시간)으로 변경

- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/dto/AuthResponse.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- close #321 
유저 권한을 조회하는 API를 작성했습니다.
로직은 크게 없어서 url path나 네이밍 위주로 봐주시면 감사하겠습니다.
> feat: 유저 권한 조회 API 작성

- src/main/java/in/koreatech/koin/domain/shop/repository/EventArticleRepository.java
- close #326 
1. EventArticleRepository의 @Query에서 @Param을 수식했습니다.
실행 환경에 따라 @Param이 없을 시 500에러가 뜨는것을 확인했습니다.
궁금한점: 기본적으로 파라미터명으로 매핑된다고 알고있는데 환경에 따라 @Param을 사용하지 않으면 서버에러가 나는것은 관련 설정이 있는것인지 궁금합니다
> fix: @Query에 @Param추가

- src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
- src/main/java/in/koreatech/koin/domain/shop/repository/EventArticleRepository.java
- close #330 
1. 신규 상점 생성 시 기본 카테고리 4종(추천 메뉴, 메인 메뉴, 세트 메뉴, 사이드 메뉴)를 자동으로 추가하는 작업을 진행했습니다.
신규 상점 생성시 기본 카테고리를 제공해줘야한다는 생각을 못했었네요 ㅠ
> feat: 신규상점 생성시 기본 카테고리 추가

- .github/pr-labeler.yml
- .github/workflows/pr-labeler.yml
- src/main/java/in/koreatech/koin/global/domain/notification/model/Notification.java
- src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
- src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
- src/main/java/in/koreatech/koin/global/fcm/FcmClient.java
- src/main/java/in/koreatech/koin/global/fcm/MobileAppPath.java
- src/main/resources/db/migration/V8__alter_notificaion_change_column_name.sql
- close #332  
1. FCM 발송 간 안드로이드, iOS의 onClick 액션을 추가하기위해 FCMClient의 발송 방식을 변경했습니다.
- Android의 경우 onClickAction, iOS의 경우 category 속성을 통해 onclick Action을 구분합니다.   
MobileAppPath를 추가했습니다. 
Notification 문서에서 다음과 같이 정의될 예정입니다.
> feat: FCM 발송방식 수정

- src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsResponse.java
- src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopsResponse.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- close #336 
1. isEvent 값을 추가했습니다.
> feat: isEvent dto 추가

- src/main/java/in/koreatech/koin/domain/user/dto/FindPasswordRequest.java
- close #344 
1. JsonProperty가 address로 설정되어 삭제했습니다.
고생 많으십니다...
> Fix : POST /user/find/password 메일 미발송

- src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
- src/main/java/in/koreatech/koin/global/config/LocalDateTimeAttributeConverter.java
- close #343
1. AttributeConverter에서 밀리 초가 3자리와 null만 고려가 되게 코드가 짜여있었는데 두개인 경우도 가능하도록 코드를 수정했습니다.
2. 기존 코인과 동일하게 authExpiredAt시간을 한시간에서 10시간으로 조정해줬습니다.
에러 수정되었으면 좋겠네요 😢
> fix: attributeConverter milli second 길이가 두개인 경우도 반영

- src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
- src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadController.java
> fix: upload memberId 자료형 수정

- src/main/java/in/koreatech/koin/KoinApplication.java
- src/main/java/in/koreatech/koin/global/config/CorsProperties.java
- src/main/java/in/koreatech/koin/global/config/WebConfig.java
- src/main/resources/application-test.yml
- close #279 
1. CORS 설정을 추가했습니다.
nginx에서 관리하는것 보다 Application 레벨에서 관리하는게 휴먼 에러를 줄일 수 있어서 추가했습니다.
(Allowed Origin에 포함되어있는 클라이언트에서 요청을 보낼때)
(Allowed Origin에 포함되어있지 않은 클라이언트에서 요청을 보낼때)
로컬에서 CORS 테스트를 위해 사용한 코드 공유합니다.
node.js로 구동했습니다.
```javascript
// index.js
const axios = require('axios');
async function fetchDinings() {
try {
// Axios를 이용한 GET 요청
const response = await axios.get('http://localhost:8080/dinings', {
headers: {
// 원하는 헤더를 여기에 추가
'Origin': 'http://localhost:3000'
}
});
console.log('Data:', response.data);
} catch (error) {
// 오류 처리
console.error('Error fetching dinings:', error.message);
console.error('Error fetching dinings:', error);
}
}
fetchDinings();
```
> feat: CORS 설정 추가

- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- 기존
- 비밀번호가 틀렸을 때 400에러를 반환하지만 스웨거 문서에는 401에러를 반환한다고 나와있습니다.
- 변경 후
- 스웨거 문서에 400에러가 반환된다고 표시하였습니다.
> refactor: 유저 로그인에서 swagger에 400에러 표시

- src/main/java/in/koreatech/koin/domain/ownershop/ShopEventCreateEvent.java
- src/main/java/in/koreatech/koin/domain/ownershop/dto/CreateEventRequest.java
- src/main/java/in/koreatech/koin/domain/ownershop/dto/ModifyEventRequest.java
- src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
- src/main/java/in/koreatech/koin/domain/shop/model/ShopEventListener.java
- src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
- src/main/java/in/koreatech/koin/global/domain/notification/model/Notification.java
- src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
- src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
- src/main/java/in/koreatech/koin/global/fcm/MobileAppPath.java
- src/main/resources/db/migration/V11__alter_notification_column_nullable.sql
- src/test/java/in/koreatech/koin/AcceptanceTest.java
- src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
- close #263 
1. 사장님이 가게 생성 시 알림이 발송되도록 로직을 추가했습니다
2. 현수의 수면코딩의 잔해를 걷어냈습니다
- dto example 구체화
- dto 제약조건 추가
3. notification의 필드들이 NotNull일 이유가 없어 제약조건을 해지해줬습니다.
- 이미지가 없는 알림이 있을 수 있지만 현재의 제약조건 상으로는 Notificaiton 테이블에 저장되는 값들은 Not Null이기 때문에 모든 값들이 강제됩니다.
- 이에 V11 flyway 파일을 추가했습니다.
잘부탁드려요~
@Choon0414 제가 원하던 알림발송 로직 구현의 방향성을 녹여봤습니다 리뷰해주세요
- 테스트 기기의 FCM 토큰이 있어야합니다. (클라한테 부탁해서 받아냄 ㅎㅎ)
- users 테이블의 deviceToken 필드에 FCM 토큰값을 넣음
- 로컬에서 사장님 권한으로 로그인해서 이벤트 생성 API 호출
> feat: 사장님 가게 생성 시 알림 발송하도록 추가

- src/main/java/in/koreatech/koin/domain/user/model/UserType.java
- close #392 
임시토큰임을 userId = 0 으로 비교하고있습니다.
지난번 Entity 대규모 패치 과정에서 임시토큰 기준을 Long으로 놔둬서 이를 Integer를 비교하여 발생하는 문제가 발생했습니다.
0 != 0L
1. long을 int로 변경했습니다.
꼼꼼하게 보겠습니다 😅
> fix: 임시토큰 비교 자료형 불일치 수정

- src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopApi.java
- src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopController.java
- src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopEventsResponse.java
- src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
- close #394 
1. `GET /owner/shops/{shopId}/event`의 반환값을 ShopEventsResponse  -> OwnerShopEventsResponse로 변경했습니다.
- 기존 ShopEventsResponse는 오늘 진행중인 이벤트에 대한 값만 반환합니다. (이벤트 배너 조회에 활용되는 DTO)
- OwnerShopEventsResponse는 사장님이 가지고있는 모든 이벤트를 조회하도록 수정했습니다.
dto 재활용.. 가급적이면 하지 맙시다!!
각 API 별 요구사항이 변동될때 유연하지 못합니다
> fix: 사장님 이벤트 날짜조건 제거한 DTO 추가

- src/main/java/in/koreatech/koin/domain/shop/repository/ShopRepository.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- close #379
1. UserService에서 owner만 삭제하는 로직을 추가했습니다. 
이 이미지가 무엇을 의미하는지 잘 이해가 안갑니다. 일단 OwnerAttachment의 owner_id에 해당하는 문제로 발생한것으로 인지했습니다.
>> @OneToMany(cascade = {PERSIST, MERGE, REMOVE}, orphanRemoval = true)
@JoinColumn(name = "owner_id")
private List<OwnerAttachment> attachments = new ArrayList<>(); 
Owner 클래스의 위 코드에서 자식개체를 자동으로 삭제되는 orphanRemoval=true코드가 이미 있어서, UserService에서 따로 OwnerAttachment를 삭제하는 로직을 추가하지 않고, owner만 삭제했습니다.
user_id가 fk참조돼있는 데이터를 모두 지울필요는 없을것같아 다시 수정했는데, 정확히 오류가 무엇때문에 일어나는지 정확힌 모르겠습니다..
> Fix: 사장님 회원탈퇴 오류

- src/main/java/in/koreatech/koin/domain/dept/model/Dept.java
- close #403
1. 건축, 기계, 메카 커리큘럼 링크를 학부 홈페이지 링크에서 교육 과정 페이지 링크로 수정해줬습니다
> fix: 건축, 기계, 메카 커리큘럼 링크 수정

- src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
- src/main/java/in/koreatech/koin/domain/shop/model/Menu.java
- src/main/java/in/koreatech/koin/domain/shop/model/MenuCategory.java
- src/main/resources/db/migration/V12__alter_menu_and_menu_categories_column_remove_is_deleted.sql
- close #408 
1. flyway를 이용해 shop_menu, shop_menu_categories의 is_deleted컬럼을 삭제했습니다.
2. 그에 따른 Menu, MenuCategory Entity의 설정을 변경하였습니다.
메뉴 수정을 어떻게 해야 좋을지 고민하다가 pr이 늦어졌네요.. 일단 id_deleted만 삭제했습니다!
> refactor: 메뉴, 메뉴카테고리 Soft Delete로 변경

- src/main/resources/mail/student_register_certificate_number.html
- close #이슈번호
1. 인증 만료시간이 1시간으로 되어있던 것을 10시간으로 수정해줬습니다.
> fix: 코인 인증 메일 폼 만료 시간 수정

- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- close #428 
서버에서 ClientAbortException를 핸들링하지 않아 500 에러로 발생
핸들링하여 명확한 메시지를 반환
1. ClientAbortException 핸들링 추가
> fix: ClientAbortException handle

- src/main/java/in/koreatech/koin/domain/user/model/UserToken.java
1. 클라이언트 측의 요청으로 잠깐 access 토큰은 10초, 리프레시 토큰 만료 기한을 14일에서 20초로 변경했습니다
2. accesstoken은 build 서버에서 변경 후 젠킨스에서 재 빌드 했습니다
이렇게 하는 것이 맞는지 잘 모르겠네요.. 잘못 된 것 있으면 말씀해주시면 감사하겠습니다!
> feat: 리프레시 토큰 만료 기한을 14일에서 20초로 변경

- src/main/java/in/koreatech/koin/domain/user/model/UserToken.java
1. 리프레시 토큰 기한 14일로 원상 복구 시켰습니다.
2. access 토큰 시간 다시 변경 후 jenkins 빌드 하였습니다.
> feat: 리프레시 토큰 만료 기한 14일로 원상 복구

- src/main/java/in/koreatech/koin/domain/ownershop/EventArticleCreateShopEvent.java
- src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
- src/main/java/in/koreatech/koin/domain/shop/model/ShopEventListener.java
- close #441 
1. 디바이스토큰을 가지고 있는 모든 유저에게 알림을 보내고 있던 코드에서 구독을 한 유저에게만 알림을 보내도록 수정했습니다.
기획이 변경되었을때 인지하고 고쳤어야하는데 지금에야 발견했네요.. ㅠ
> fix: 상점 이벤트 알림을 구독한 유저에게만 알림

- src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
- src/main/java/in/koreatech/koin/global/validation/UniqueId.java
- src/main/java/in/koreatech/koin/global/validation/UniqueIdValidator.java
- src/main/java/in/koreatech/koin/global/validation/UniqueUrl.java
- src/main/java/in/koreatech/koin/global/validation/UniqueUrlsValidator.java
- close #447 
1. 같은 상점 이미지 url을 입력할 때 발생하는 서버 에러를 해결했습니다.
2. 하는김에 같은 카테고리 id를 입력할 경우도 핸들링해줬습니다.
3. custom어노테이션을 만들어서 dto단에서 중복을 체크해줬습니다.
`@UniqueId(message = "카테고리 ID는 중복될 수 없습니다.")`
`@UniqueUrl(message = "이미지 URL은 중복될 수 없습니다.")`
4. 해싱 기반 Set자료구조를 이용해서 중복 여부를 체크해줬습니다.
List를 받는 dto의 요소 중복 체크를 할 때 이번에 작성한 것을 이용하면 좋을 것 같습니다.
> fix: 상점 이미지, 카테고리id중복되는 요소 입력 시 발생하는 에러 핸들링

- src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
- close #467
1. DB의 상점 설명이 null인 경우 예외처리를 해주었습니다.
2. owner register에 있는 의미 없는 save코드를 삭제하였습니다.
리뷰 잘부탁드립니당
> fix: DB의 상점 설명이 null인 경우 예외처리

- src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateRequest.java
- src/main/java/in/koreatech/koin/domain/user/model/User.java
- src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- close #421 
1. 회원 정보 수정에 비밀번호 수정 로직을 추가했습니다.
시간을 많이 쓸 로직은 아니었는데, 이런저런 문제로 테스트 상으로 시간을 너무 많이 썼습니다😢
더 일찍 못 드려서 죄송합니당
> feat : 회원 정보 수정에 비밀번호 수정 추가

- src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
- close #474 
1. /bus/search에서 천안역에서 출발할 경우 Exception이 발생하는 문제를 수정했습니다.
- 버스 타입이 시외버스이고 출발지점이 천안역이 아닌 경우에만 탐색하도록 수정했습니다.
> fix: /bus/search 천안역에서 출발할 경우 Exception 발생 버그 수정

- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
- src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
- src/main/java/in/koreatech/koin/domain/shop/model/ShopOpen.java
- src/main/java/in/koreatech/koin/domain/shop/repository/ShopOpenRepository.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- close #484 
1. 모든 상점 조회시 운영중 여부를 쿼리로 조회하고 있었던 로직을 jpa entity를 이용해서 java로직으로 운영중 여부를 판단하게 변경하였습니다.
2. 만약 오늘 일시에 상점이 운영중이라면 `is_open=true`를 반환합니다
3. 오늘 일시에 상점이 운영중이지 않다면 어제 날짜의 운영시간을 참고해서 운영중인지 확인합니다.
조금 더 최적화해보고싶지만 당장 오늘 밤에 배포를 해야하기 때문에 pr올립니다~!
> refactor: 모든 상점 조회 api 성능개선

- src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
- close #496 
1. 상점 운영중 여부 구분 로직을 수정하였습니다.
2. 시간으로 비교하는 것이 아닌 LocalDateTime으로 비교하는 로직으로 변경하였습니다.
3. 시작일시와 종료일시 사이에 현재 일시가 있는지 검사합니다.
4. 마감 시간이 오픈시간 이전이라면 하루를 넘게 오픈하는 것이기 때문에 마감일시에 하루를 더해준 후 비교를 진행하였습니다.
5. 현재 날짜의 이전 요일의 운영시간도 확인해주었습니다.
6. 시작일시와 종료일시 사이에 현재일시가 있는지 확인하는 로직을 변경하였습니다.
역시 코딩은 잠을 푹자고 해야 잘되는거같네요 이번 로직은 간결하고 정확하게 잘짜여진것 같은 느낌입니다ㅎㅎ 리뷰 잘부탁드립니다!
> refactor: 상점 운영중 여부 로직 변경

- src/main/java/in/koreatech/koin/domain/ownershop/EventArticleCreateShopEvent.java
- src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
- src/main/java/in/koreatech/koin/domain/shop/model/ShopEventListener.java
- src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
- src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
- close #469 
1. 상점 이벤트 알림에 썸네일이미지를 추가하였습니다.
2. NotificationService의 push함수의 코드중복을 제거하였습니다.
리뷰 잘부탁드립니다!
> feat: 상점 이벤트 알림에 썸네일이미지 추가

- src/main/java/in/koreatech/koin/domain/bus/dto/BusTimetableResponse.java
- src/main/java/in/koreatech/koin/domain/bus/model/SchoolBusTimetable.java
- src/main/java/in/koreatech/koin/domain/bus/model/city/CityBusCache.java
- src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusCache.java
- src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
- src/main/java/in/koreatech/koin/domain/bus/util/BusScheduler.java
- src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
- src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
- src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
1. 시외버스/시내버스 OPEN API를 호출하는 주기 변경
- 기존: 요청 시마다 캐시가 없으면 요청
- 개선: 시내버스는 매 분마다, 시외버스는 매 시간마다 자동으로 호출하여 캐싱
- 기대 효과: 코인 버스 API 호출 시간이 5초에서 0.1초 안쪽으로 개선됨
2. 응답 객체 불일치 문제 해결
- bus timetable v2 API의 응답 객체가 어느순간 바뀌어있어서 안드로이드 프로덕션이 고장남
- 원상복구
3. 어색하게 처리된 예외처리 수정
머지 이후 production(main 브랜치)에 머지된 후 develop 브랜치에 다시 머지해야 합니다.
프로덕션에 바로 올라갈 내용이니 크리티컬한 이슈가 없는지 확인해주세요!
+) 머지된 이후 프로덕션 적용 배포는 오늘 자정에 해도 괜찮을까요?? @Choi-JJunho
> hotfix: 버스 API 응답시간 개선 및 응답 스키마 불일치 해결

- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
- src/main/java/in/koreatech/koin/admin/member/dto/AdminMembersResponse.java
- src/main/java/in/koreatech/koin/admin/member/enums/TrackTag.java
- src/main/java/in/koreatech/koin/admin/member/repository/AdminMemberRepository.java
- src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
- close #44 
1. GET /admin/members API를 추가했습니다.
조인을 사용해야 해서 `@EntityGraph`와  JPQL을 사용하여 개발을 진행하였습니다.
> feat: GET /admin/members api 추가

- src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
- src/main/java/in/koreatech/koin/domain/shop/model/MenuCategory.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- src/test/java/in/koreatech/koin/fixture/MenuCategoryFixture.java
- close #468 
1. 메뉴 카테고리가 피그마 UI에 맞게 정렬되어 응답되게 변경하였습니다.
2. 자꾸 테스트가 duplicate menu_category name으로 터지길래 왜그런가 했더니 유니크가 true로 설정되어있었습니다.. 그래서 유니크 false로 바꿔줬습니다(내30분...)
3. 테스트코드에 있는 "추천메뉴", "메인메뉴", "세트메뉴", "사이드메뉴"의 이름에 공백을 추가했습니다. "추천 메뉴", "메인 메뉴", "세트 메뉴", "사이드 메뉴"
자세한 요구사항은 이슈를 확인부탁드립니다!!
> refactor: 메뉴 카테고리 피그마 UI에 맞게 정렬

- src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
- src/main/java/in/koreatech/koin/domain/dining/model/DiningType.java
- close #이슈번호
1. 품절 알림 발송 조건에 날짜도 추가하였습니다.
- 각 코너에 대해 `최초 1회`, `오늘 날짜`, `해당 식사시간 내` 에만 발송 됩니다.
> fix : 품절 알림 발송 조건에 날짜 추가

- src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
- src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
- src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentUpdateRequest.java
- src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentUpdateResponse.java
- src/main/java/in/koreatech/koin/admin/user/repository/AdminStudentRepository.java
- src/main/java/in/koreatech/koin/admin/user/repository/AdminUserRepository.java
- src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
- src/main/java/in/koreatech/koin/domain/user/model/UserType.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
- src/test/java/in/koreatech/koin/fixture/UserFixture.java
- close #92 
1. 관리자 권한으로 특정 학생 정보를 수정할 수 있게 하였습니다.
우선 관리자 계정이 맞는지 확인하기 위해 @Auth를 썼는데 가져온 관리자 id가 사용이 안되어서 이렇게 해도 되는가 고민이 많이 됩니다.. 관련해서 좋은 의견 있으면 말씀해주시면 감사하겠습니다
> feat: admin으로 학생 정보 수정

- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/resources/db/migration/V15__delete_notification_subscribe.sql
- close #513 
1. notification / notification_subscribe에 대해 FK 오류 수정을 위해 DELETE CASCADE flyway sql문을 추가했습니다.
FK에 관해서 CASCADE 처리를 현재 notification과 notification_subscribe에 적용시켰는데, 다른 부분에도 이를 적용해도 되는지, 그리고 추가적으로 CASCADE 처리를 다른 FK 값에 대해서 진행하는 것이 안전한가? 에 대해서 의논이 필요할 것 같습니다.(선권씨 입장)
확인하신다면 의견 부탁드립니당.
> fix : notification FK 회원 삭제 오류 수정

- src/main/java/in/koreatech/koin/domain/member/repository/MemberRepository.java
- src/main/java/in/koreatech/koin/domain/member/service/TrackService.java
- src/test/java/in/koreatech/koin/acceptance/TrackApiTest.java
- src/test/java/in/koreatech/koin/fixture/MemberFixture.java
- close #538 
1. isDelete = true 인 멤버 조회 안하도록 수정
MemberRepository에서 findByTrackId를 findByTrackIdAndIsDeletedFalse로 수정
isDelete = true여도 DB상 남아있기 때문에 테스트에서 id 순서 고려
> fix: 삭제된 멤버 조회 수정

- src/main/java/in/koreatech/koin/admin/land/controller/AdminLandApi.java
- src/main/java/in/koreatech/koin/admin/land/controller/AdminLandController.java
- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
- src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
- src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
- src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentResponse.java
- src/main/java/in/koreatech/koin/admin/user/dto/AdminStudentUpdateResponse.java
- src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
- close #91
1. 어드민 계정으로 특정 학생 조회 api를 구현 했습니다.
2. 전에 구현된 어드민 api들도 @auth를 붙여서 권한 필터링 되게 해줬습니다.
> feat: 어드민 계정으로 특정 학생 조회

- Dockerfile
- close #이슈번호
빌드를 하던 도중 Docker에 wget이 안깔려 있어 빌드가 실패하였습니다.(그리하여 로컬에서 테스트를 하였습니다.)
처음 빌드시 전체가 빌드가 되는 모습을 볼 수 있으며,
두번째 빌드에선 이미 설치가 되었기에 생략되는 모습을 볼 수 있습니다.
이로서 빌드시간을 감축할 수 있습니다.
> refactor: docker 파일 wget설치 명령어 추가

- src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
- src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableUpdateRequest.java
- src/main/resources/db/migration/V16__alter_timetables_colum_nullabe.sql
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- close #542
기존 강의 시간표 생성하는 API를 이용하였습니다.
커스텀 시간표 추가할때 (학기, 이름, 시간)에 대한 요청값만 필요하기 때문에 기존 시간표 생성API를 커스텀 시간표를 고려하여 변경했습니다.
1. DTO 스키마 이름 변경
`@Schema(description = "강의(커스텀) 이름", example = "운영체제", requiredMode = REQUIRED)`
`@Schema(description = "강의(커스텀) 시간", example = "[210, 211]", requiredMode = REQUIRED)`
2. requiredMode 변경
커스텀 시간표를 고려하여 기존에 필수값이였던 학점하고 분반에 대한 요청과 응답 requiredMode를 REQUIRED에서 NOT_REQUIRED로 변경했습니다. <br/>
분반은 DB에서 필수값이 아니므로 NOT_REQUIRED로 변경하였으며, 학점은 DB에서NULL값을 허용하지않으며 시간표 조회시 시간표의 학점으로부터 총 이수학점이 계산되어 나오므로 학점 디폴트값을 0으로 설정하고 NOT_REQUIRED로 변경하였습니다.
> feat: 커스텀 시간표 API

- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
- src/main/java/in/koreatech/koin/admin/member/dto/AdminMemberRequest.java
- src/main/java/in/koreatech/koin/admin/member/repository/AdminMemberRepository.java
- src/main/java/in/koreatech/koin/admin/member/repository/AdminTrackRepository.java
- src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
- close #45 
1. POST /admin/members API를 추가하였습니다.
- `TrackNotFoundException`과 `MemberNotFoundException`을 기존 domain의 Member 패키지에서 사용하던 것들을 단순 재사용했는데, 따로 `AdminTrackNotFoundException`을 추가해서 관리해야 할지 아니면 그냥 쓸지에 대한 고민을 해보았고, 당장은 불필요하다고 생각해서 기존 예외를 재사용하는 방향으로 선택하였습니다.
- 기존 `GET /admin/members` API에서는 트랙 관련 파라미터를 enum으로 처리했는데, Request DTO에서는 `track`을 String으로 받고 `@Pattern`을 통해 검증하도록 하였습니다(기존 KOIN_API 방식). 기존처럼 String으로 처리할지, 혹은 enum으로 처리하도록 수정할지에 대해 고민중이라 의견 주시면 감사하겠습니다.
- 기타 DTO 검증은 KOIN_API에서 하던 방식 그대로 적용하였습니다.
> feat: POST /admin/members API 추가

- src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
- src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerRegisterByPhoneRequest.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- close #560 
1. 전화번호로 회원가입하는 api를 작성했습니다.
2. 기존 api의 dto email필드만 제거하려다가 api를 새로 작성하는게 나을거같아서 새로 작성했습니다.
3. db의 email필드가 notnull이라서 email필드를 전화번호로 채워줬습니다.
> feat: 상점 사장님 휴대폰번호로 회원가입 api작성

- src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- close #557
1. 해당 로직 과정에서 동시성 제어 방식에는 비관적인 방식이 있으나, 현재 리소스가 많은 곳에서 쓰이는 공유자원인 학생인만큼 전체적인 서비스 성능 저하가 유발될것이며, 단순 데이터 중복에 대한 에러를 반환하는것이기에 try-catch문으로 처리했습니다.
2. 동시성 환경에서 발생할 수 있는 로그를 검증하는 테스트를 작성했습니다.
https://velog.io/@kwoo28/%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85-%EB%8F%99%EC%8B%9C%EC%84%B1-%EC%9D%B4%EC%8A%88-%ED%95%B4%EA%B2%B0
> fix: 회원가입 동시성 이슈 처리

- src/main/java/in/koreatech/koin/domain/owner/model/Owner.java
- src/main/java/in/koreatech/koin/domain/owner/model/OwnerAttachment.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
- src/test/java/in/koreatech/koin/fixture/UserFixture.java
```
Exception: DataIntegrityViolationException
Location: HibernateJpaDialect.java Line 269
could not execute statement [Column 'owner_id' cannot be null] [update owner_attachments set owner_id=null where owner_id=? and ((is_deleted=0) )];
```
위와 같은 에러를 수정했습니다. 
* 동시성으로 이유를 파악했었는데 동시성이 문제가 아니였습니다.
해당 문제는 (orphanremoval = true)와 (cascade = remove)와 같은 자식 개체를 같이 삭제하게 해놓은 설정의 문제였습니다.
위와 같은 설정을 하게 되면 
부모 객체를 삭제할 때 해당 설정의 자식 엔티티는 자신이 참조하고 있던 부모 키(fk)를 null로 만들어서 고아 상태로 만드는 update 쿼리 문을 날립니다. 
위처럼 자식 객체도 같이 삭제되게 하는 설정을 하면 회원 탈퇴를 할 때 날라가는 쿼리문은 다음의 순서와 같습니다.
1. owner attachment의 owner_id(fk)를 null로 만드는 update 쿼리문 
2. owner attachment delete 쿼리문
3. owner delete 쿼리문
4. user delete 쿼리문
이때 외래키 설정이 NOT NULL로 되어있으면 부모 외래키를 null로 만들려고 하는 위 설정들과 충돌이 일어나게 됩니다.
따라서 fk값을 null로 만들 수 없게 many인 쪽에 (updatable = …
> fix: 사장님 탈퇴 이슈 예외 처리

- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordResetVerifySmsRequest.java
- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerPasswordUpdateSmsRequest.java
- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerRegisterByPhoneRequest.java
- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerSendSmsRequest.java
- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerSmsVerifyRequest.java
- src/main/java/in/koreatech/koin/domain/owner/dto/VerifySmsRequest.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- close #580
1. 전화번호를 이용한 사장님 회원가입, 비밀번호변경, 인증번호발송 api전화번호필드의 형식을 변경하였습니다.
- `xxx-xxxx-xxxx`에서 `xxxxxxxxxxx`로 변경하였습니다.
변경 사유: 로그인, 네이버인증에서 하이픈이 없는 전화번호 형식을 사용해서 더이상 하이픈을 받을 필요가 없음
> refactor: 전화번호 하이픈 제거

- src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
- close #590 
1. api에서 노선 정보가 없을 경우 빈 배열 리턴중
2. 따라서 천안역 조건 확인이 필요 없어져서 제거
> Refactor: 대성 고속(Express) 천안역 확인 조건문 제거

- src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
메뉴리스트 문자열의 리스트화를 진행할 때 문자열 split이 아니라 정규식 기준으로 잘라서 메뉴 텍스트 속에 `,`가 들어있는 경우 잘못 파싱되는 문제를 해결했습니다.
> fix: 메뉴 리스트 파싱 로직 수정

- src/main/java/in/koreatech/koin/domain/user/dto/UserLoginRequest.java
영양사님 계정을 이메일 형식이 아닌 일반 아이디로 사용하기 위해 이메일 형식 검증을 잠시 제거했습니다.
새로운 로그인 api가 배포되고 프론트 레포가 분리되고 영양사 페이지에 적용되면 다시 추가하여 PR 올리겠습니다.
+) 일요일 중으로 프로덕션 배포하겠습니다. 일요일에 슬랙에 공유하고 저녁쯤 배포누르겠습니당
> refactor: 기존 로그인 api 이메일 형식 검증 제거

- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
- src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
- src/main/java/in/koreatech/koin/domain/member/model/Member.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
- close #48 
1. PUT /admin/members/{id} api 추가하였습니다.
- `POST /admin/members` 와 request가 동일하여 `AdminMemberRequest` dto를 그대로 사용하였습니다.
- track이 변경되었을 때와 변경되지 않았을 때의 2가지 경우를 테스트하였습니다.
> feat : put /admin/members/{id} api 추가

- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- close #602
1. hotfix가 맞는 것 같다는 의견이 있어서 hotfix로 수정해서 main에다가 날립니다
2. develop에서 checkout한 fix브랜치를 hotfix로 이름만 바꾸고 main에다가 그냥 날려버렸다가 잘못됨을 깨닫고 다시 main에서 checkout해서 pr을 날립니다..
3. 정보 수정 란에 들어가기 전 비밀번호를 통해 자신이 맞는지 확인할 때, 비밀번호가 틀리면 401을 반환하면 로그인이 풀려버리는 문제가 발생하였습니다. 따라서 400으로 반환하게 수정해줬습니다.
여러번 귀찮게 해서 죄송합니다
> hotfix: 비밀번호 검증 api 비밀번호 틀렸을시에 400 반환하는 것으로 수정

- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
- src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
- src/main/java/in/koreatech/koin/domain/member/model/Member.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
- src/test/java/in/koreatech/koin/fixture/MemberFixture.java
- close #49 
1. POST /admin/members/{id}/undelete API 추가
- 삭제 상태의 회원을 DB에 저장하기위해 `Fixture`에 `최준호_삭제`를 추가 후 테스트를 진행하였습니다.
> feat: POST /admin/members/{id}/undelete API 추가

- src/main/java/in/koreatech/koin/domain/bus/model/enums/BusStation.java
- src/main/java/in/koreatech/koin/domain/bus/model/enums/BusStationNode.java
- src/main/java/in/koreatech/koin/domain/bus/repository/CityBusRouteCacheRepository.java
- src/main/java/in/koreatech/koin/domain/bus/util/CityBusClient.java
- src/main/java/in/koreatech/koin/domain/bus/util/CityBusRouteClient.java
- src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
- close #582 
1. 시내버스 정류장을 추가했습니다.
- Map<방향, 정류장ID> 에서 Map<방향, List<정류장ID>>로 수정되었습니다.
- 이에 따라 로직도 수정되었습니다.
2. `CityBusRouteCache`를 하나씩 반복하여 save 하도록 수정하였습니다.
- Spring Master GPT씨가 `CrudRepository` 또는 `JpaRepository`가 아닐 경우 `saveAll`을 직접 만들어서 사용해야 된대요
> refactor: 시내버스 정류장 불일치 해결

- src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
- src/main/java/in/koreatech/koin/domain/owner/model/OwnerRegisterBySmsEvent.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- close #620 
1. 기존에 회원가입 후 redis를 초기화 할 때 key는 email로 사용중이였음
2. sms회원가입에서도 key를 email로 처리하고 있는 것을 확인(sms에서는 email이 없음)
3. sms회원가입에서는 account를 key로 처리
> refactor: sms회원가입 redis초기화 로직 변경

- src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
- close #이슈번호
1. 식단의 Kcal 정보가 null일 경우 0을 반환하도록 롤백했습니다.
> fix : 식단의 Kcal가 null 일 경우 0을 반환하도록 롤백

- src/main/java/in/koreatech/koin/domain/bus/util/CityBusRouteClient.java
- close #628 
1. redis에 저장하기 전에 `Set<CityBusRoute>`가 empty인지 확인
2. empty가 아닐 경우에만 저장
이래도 터지면 모르겠어요...
> fix: CityBusRoute 저장시 null 제외 추가

- src/main/java/in/koreatech/koin/admin/land/controller/AdminLandApi.java
- src/main/java/in/koreatech/koin/admin/land/controller/AdminLandController.java
- src/main/java/in/koreatech/koin/admin/land/dto/AdminLandRequest.java
- src/main/java/in/koreatech/koin/admin/land/dto/AdminLandResponse.java
- src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsResponse.java
- src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
- src/main/java/in/koreatech/koin/domain/land/dto/LandResponse.java
- src/main/java/in/koreatech/koin/domain/land/model/Land.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
- src/test/java/in/koreatech/koin/fixture/LandFixture.java
- close #13
- close #14 
- close #15 
1. 마감기한 임박으로 인해 3개의 기능을 한번에 올립니다.
2. 로컬에서의 테스트 및 테스크코드 작성하였습니다
졸면서 구현하였어요
> feat: 어드민 복덕방 조회,수정,삭제취소

- src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadApi.java
- src/main/java/in/koreatech/koin/global/domain/upload/controller/UploadController.java
- close #635 
- close #636 
1. ADMIN 권한을 추가했습니다.
> refactor: ADMIN 권한 추가

- src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateMenuRequest.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopRequest.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyMenuRequest.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopRequest.java
- src/main/java/in/koreatech/koin/global/validation/UniqueIdValidator.java
- src/main/java/in/koreatech/koin/global/validation/UniqueUrlsValidator.java
- close #634
- close #632  
1. imageUrls가 null일 경우 `@UniqueUrl`커스텀 어노테이션에서 null예외가 발생하는 것을 확인하여 DTO의 생성자에 null일경우 빈 리스트로 초기화 해주는 로직을 추가하였습니다.
> fix: 상점 생성,수정 / 메뉴 추가,수정 버그 해결

- src/main/java/in/koreatech/koin/domain/user/dto/StudentLoginRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/UserLoginRequest.java
- src/main/java/in/koreatech/koin/global/validation/EmojiValidator.java
- src/main/java/in/koreatech/koin/global/validation/NotEmoji.java
- close #649
1. 기존 로그인시에 이메일에 이모지를 넣어 발생한 에러는 기존에 있던 이메일 형식 검증 어노테이션을 추가했습니다.
2. 이모지 검증 어노테이션을 추가하여 닉네임이나 이름같은 필드에 이모지를 넣을시 발생할 에러를 방지했습니다.
> Fix: 이모지 검증 추가

- src/main/java/in/koreatech/koin/domain/timetable/repository/LectureRepository.java
- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
- close #659
1. 기존 조회 조건은 여러 개의 강의를 반환하는 경우가 있어서 post timteable api 로직 내부의 조회 조건을 변경했습니다.
(이름 -> code로 변경)
> fix: post timteable 조회 조건 변경

- src/main/java/in/koreatech/koin/global/validation/EmojiValidator.java
- close #666 
1. 이모지 검증하는 어노테이션이 null값을 허용하지 않아서 오류가 발생하여 null값을 허용했습니다.
> fix: 이모지 어노테이션 검증 수정

- .github/workflows/pick-reviewer.yml
- .github/workflows/pr-merged.yml
- .github/workflows/reviewer.json
- close #670 
1. 프론트엔드의 구성을 가져왔습니다.
2. 삐봇에 API path를 추가했습니다.
정상적으로 동작하면 다음과 같은 구조로 뜰 예정입니다.
> feat: github workflow 추가

- src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
> develop 브랜치 충돌해결

- src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
- close #694 
1. Swagger 형식에 맞도록 Requset를 수정했습니다. (11자리 형식에서, 3-4-4 형식 추가)
저번 로그인 로직 수정하면서 전화번호를 통일하겠다! 하고 수정했던 내용인데, Swagger에 반영이 안 되어 있었습니다. 다시 전화번호 형식을 2가지 받도록 했고, 학생 측에서도 전화번호 회원가입도 의견이 나옴에 따라 이 사항도 한 번 논의해봐야 할 것 같습니다.
브랜치를 잘못 파서 PR을 더 날려버렸네요 죄송합니당😢
> hotfix : 학생 회원가입 전화번호 입력 값 Swagger에 맞춰 수정

- src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterCheckResponse.java
- src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
- src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- close #704 
1. GET /semesters/check의 학기 반환값을 오름차순 -> 내림차순으로 변경했습니다.
2. hotfix로 적용하였던 학생 회원가입 전화번호 표현식 변경사항을 develop에도 적용했습니다. (3 - 4 - 4 + 11자리 가능)
프론트엔드 도훈님의 요청으로 학기의 반환값을 내림차순으로 변경했습니다. 
추가적으로 hotfix로 적용하였던 학생 회원가입 전화번호 표현식을 develop에도 적용했습니다.
잘 부탁드립니다~ :D
> feat : GET /semesters/check 반환값 내림차순 변경 & 학생 회원가입 전화번호 형식 hotfix develop 적용

- src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopShopResponse.java
- src/main/java/in/koreatech/koin/domain/coopshop/dto/CoopShopResponse.java
- src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShop.java
- src/main/resources/db/migration/V31__add_coopshop_semester.sql
- src/test/java/in/koreatech/koin/acceptance/CoopShopTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminCoopShopTest.java
- src/test/java/in/koreatech/koin/fixture/CoopShopFixture.java
- close #이슈번호
1. 생협 운영시간에 학기 정보(semester)가 추가되었습니다.
- `coop_shop` 테이블에 `semester` 칼럼 추가
- {"semester" : "하계방학"} 과 같은 형태로 들어갑니다.
> fix : 생협 운영시간 정보에 학기 필드 semester 추가

- src/main/java/in/koreatech/koin/domain/coopshop/model/CoopOpen.java
- src/main/java/in/koreatech/koin/domain/coopshop/model/CoopShop.java
- close #이슈번호
1. CoopShop 조회 시 모든 CoopOpen이 조회되도록 `Lazy`에서 `Eager`로 수정하였습니다.
- CoopShop을 통한 CoopOpen 조회는 OneToMany에 적용해야 하는데 ManyToOne에 잘못 적용해서 다시 올립니다.
> fix : coopShop 조회 시 모든 CoopOpen이 즉시 조회되도록 수정

- src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
- src/main/java/in/koreatech/koin/domain/user/model/UserToken.java
- src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
- close #705 
1.  isMain인 프레임을 삭제하면 isMain이 아닌 것 중에 가장 먼저 생성된 것이 isMain이 되도록 jpa의 힘을 빌려 로직을 짰었으나.. jpql로 바꾸게 되면서 생긴 에러 입니다.  jpql은 limit을 지원하지 않아서 limit을 지원하는 jpa로 메서드를 다시 변경했습니다.(first)
> fix: 시간표 프레임 삭제 관련 에러 수정

- src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
- src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
- src/main/java/in/koreatech/koin/domain/bus/dto/CityBusTimetableResponse.java
- src/main/java/in/koreatech/koin/domain/bus/model/enums/CityBusDirection.java
- src/main/java/in/koreatech/koin/domain/bus/model/mongo/CityBusTimetable.java
- src/main/java/in/koreatech/koin/domain/bus/repository/CityBusTimetableRepository.java
- src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
- src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
- src/test/java/in/koreatech/koin/fixture/BusFixture.java
- close #656 
1. 시내버스 시간표 만들었습니다.
살짝 급하게 만들어서 문제가 많을수도 있어용
> feat: 시내버스 시간표 

- src/main/resources/db/migration/V34__shop_reviews_restrict_change_cascade_.sql
- src/main/resources/db/migration/V35__shop_review_reports_restrict_change_cascade_.sql
- src/main/resources/db/migration/V36__shop_review_images_restrict_change_cascade_.sql
- src/main/resources/db/migration/V37__shop_review_menus_restrict_change_cascade_.sql
- close #721 
1. Shop_review 관련 FK의 제약 조건을 RESTRICT -> CASCADE로 수정했습니다.
확인해보니 `user`가 `review`를 남김 -> `review`에는 `menu / image`가 포함 || 또는 리뷰 신고시 `report`에 `user_id / review_id` 포함되는 형태인데, 각 FK 관계가 RESTRICT여서 오류가 발생했습니다.
review와 관련된 4개의 테이블의 FK 조건을 CASCADE로 변경했습니다. (user / shop)
잘 부탁드려요~
> feat : shop_review 관련 FK 조건 CASCADE 수정

- src/main/java/in/koreatech/koin/domain/shop/dto/CreateReviewRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyReviewRequest.java
- close #725 
1. imageUrls가 null일 경우 nullPointer가 발생하는 이슈를 해결하기 위해 null인 경우 빈 배열로 초기화 해줬습니다.
> feat: imageUrls가 null인 경우 빈 리스트로 초기화한다.

- src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
- src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
- not main 시간표 프레임과 main 시간표 프레임을 동시에 삭제하면 에러가 남
- main 시간표 프레임을 삭제하면 not main 시간표 프레임 중에 최근 시간표 프레임을 조회해서 main으로 바꿔야 하는데 이때 이전에 삭제 요청한게 database에 반영되지 않아 조회되는 문제가 있음
1. not main 시간표 프레임 중에 최근 시간표 프레임을 조회하는 find문에 베타적 락을 걸었습니다.
a. 메인 시간표 프레임을 삭제할 때만 사용하는 함수이기 때문에 성능에 큰 문제가 없을 거라 생각 했습니다.
2. not main 시간표 프레임과 main 시간표 프레임을 동시에 삭제하는 테스트 코드 작성했습니다.
> fix: not main, main 시간표 프레임 동시 삭제 문제 해결

- src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
- close #730
findFirstByUserIdAndSemesterIdAndIsMainFalseOrderByCreatedAtAsc()메서드에 베타락을 걸어도 여전히 위와같은 2개의 트랜잭션이 동시에 접근되는 상황에서 여전히 동시성 에러가 발생되고 있습니다. 이유는 사진과 같이 findById는 여전히 해당 레코드를 공유하여 접근하기 때문에 충돌이 발생합니다.
그래서 findById메서드 또한 베타락을 걸어서 다른 트랜잭션에서 findById 사용할때 해당 레코드에 동시에 접근하는 것을 막게 수정했습니다.
> fix : 시간표 프레임 삭제 동시성

- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
- close #734
하나의 트랜잭션이 B레코드에 베타락을 거는 상황에서, 다른 트랜잭션이 A레코드에 베타락을걸고 B레코드에  베타락을 걸때 JPA에서 데드락으로 간주하고 cannotacquirelockexception예외를 발생시킵니다.
근데 정확히 어디에서 순환관계에 빠진 데드락 상황이 걸린진 모르겠으나, JPA에서 데드락 예외를 발생시킬만한 상황을 없애기 위해 로직순서를 변경했습니다.
> fix: 시간표 프레임 삭제 로직 수정

- src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
- src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
- close #
1. 운영시간 검사 추가해봤습니다
황현식 만만세!
> fix: 식단 이미지 업로드 알림 운영시간 검사 추가

- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- close #741
DELETE/timetable API 동시 호출과정에서 ObjectOptimisticLockingFailureException 에러가 발생했습니다.
- ObjectOptimisticLockingFailureException란?
JPA에서 매핑된 객체에 대한 낙관적 잠금 위반에 대해 발생한 예외를 말합니다. 즉, DB단이 아닌 어플리케이션의 JPA 영속성단에서 레코드를 수정하기 전에 다른 트랜잭션이 해당 레코드를 수정했는지를 확인하고 발생시킵니다.
트랜잭션A : 조회 -> 삭제
트랜잭션B : 조회 -> 삭제
현재 위와같은 삭제API가 동시에 호출되면서 트랜잭션 충돌이 발생하여 JPA에서 ObjectOptimisticLockingFailureException 예외가 발생되었습니다.
해결방안1 - 조회메서드에 비관적락을 건다.
조회메서드에 비관적락을 걸게되면 예외가 발생하지 않고 간단하게 처리됩니다. 하지만 해당 레코드에 많은 트랜잭션의 접근이 발생시 지연이 발생합니다.
해결방안2 - try-catch문으로 예외처리한다.
만약 현재 단순 조회->삭제 로직에서 조회메서드에 락을 걸게된다면 얻는 이익은 예외가 발생 안한다뿐입니다. 그렇기때문에 예외를 발생시키지 않기위해 성능저하를 감수하는것은 올바르지 못한 방향이라 생각이 들었기에, try-catch문을 통해 단순 요청이 빠르다는 정보를 클라이언트에게 넘겨줍니다.
그래서 현재 상황에서 최적의 방안은 해결방안2라고 생각이들어 try-catch문으로 해결했습니다.
> fix: DELETE/timetable 동시성 에러

- src/main/java/in/koreatech/koin/domain/shop/dto/CreateReviewRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyReviewRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewReportRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopsFilterCriteria.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopsFilterCriteriaConverter.java
- src/main/java/in/koreatech/koin/domain/shop/model/ShopReview.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- src/main/java/in/koreatech/koin/global/config/WebConfig.java
- src/main/resources/db/migration/V40__alter_review_content_nullable_.sql
- src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
- close #742
- close #749 
- close #750
1. 모든 상점 조회시 필터값에 유효성 검사를 추가했습니다.
2. 리뷰 작성시 내용이 null이 될 수 있게 변경했습니다.(기획에 맞도록 변경)
3. 리뷰 신고 내역을 여러개 선택할 수 있도록 변경했습니다.
> refactor: 모든 상점 조회시 필터 유효성 검사 추가

- src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
- src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ReviewsSortCriteria.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopMyReviewsResponse.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewsResponse.java
- src/main/java/in/koreatech/koin/domain/shop/model/ShopReview.java
- src/main/java/in/koreatech/koin/domain/shop/repository/ShopReviewRepository.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
- src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
- src/test/java/in/koreatech/koin/config/FixedDate.java
- src/test/java/in/koreatech/koin/config/FixedDateAspect.java
- src/test/java/in/koreatech/koin/config/TestTimeConfig.java
- src/test/java/in/koreatech/koin/fixture/ShopReviewFixture.java
- close #755 
- close #754  
1. 리뷰 조회시 정렬을 할 수 있도록 API를 변경하였습니다.
2. 내가 작성한 리뷰만 모아볼 수 있도록 별도의 API를 작성하였습니다.
3. 정렬 기준 중 오래된순, 최신순이 있는데 그것을 테스트하기 위해서는 `created_at`을 특정 날짜로 지정할 수 있어야 합니다. 따라서 테스트에서만 사용하는 `@FixedDate`어노테이션을 만들었습니다.
- 특정 메소드에 시간을 지정할 수 있습니다.
- `@FixedDate(year = 2024, month = 8, day = 7)`이렇게 메소드 위에 붙이면 AOP를 이용해서 해당 메소드에서는 지정한 시간대로 설정하고 메소드가 끝나면 원래 시간으로 되돌립니다.
테스트코드가 대부분입니다.. ㅎ
> feat: 리뷰 조회 API 정렬 기능 추가

- src/main/java/in/koreatech/koin/domain/shop/dto/ShopsResponseV2.java
- close #761
1. 삭제된 리뷰는 제외하고 상점 정보를 구성할 수 있도록 변경하였습니다.
2. 소수점 둘째자리까지 나타내도록 수정하였습니다.
> refactor: 상점 조회 V2 삭제된 리뷰는 제외하도록 변경

- src/main/resources/db/migration/V41__add_dining_menus_price_column.sql
- close #736 
1. 식단의 `price_card` 와 `price_cash` 칼럼을 `price`로 합쳤습니다.
- `price_card` , `price_cash` 칼럼은 클라이언트 대응 후 삭제할 예정입니다.
> fix: 캠퍼스팀 안 쓰는 컬럼 삭제 - 식단에 price 컬럼 추가

- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- close #763
1. 계절학기는 빈 리스트로 반환될 수 있게 로직 수정했습니다.
> feat: 계절학기 빈 리스트로 반환

- src/main/java/in/koreatech/koin/domain/community/dto/ArticleResponse.java
- src/main/java/in/koreatech/koin/domain/community/dto/ArticlesResponse.java
- src/main/java/in/koreatech/koin/domain/community/dto/HotArticleItemResponse.java
- src/main/java/in/koreatech/koin/domain/community/repository/BoardRepository.java
- src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
- src/main/java/in/koreatech/koin/global/model/Criteria.java
- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
- close #774 
1. 게시글 조회 API를 변경된 명세에 맞게 수정했습니다.
2. 인기있는 게시글 조회 API는 내부 로직은 그대로 두고 명세만 수정했습니다.
1. 로직 수정은 8월 안으로 마무리해서 올리겠습니다.
3. Criteria 클래스 생성자에 limit에 대해 validate가 누락되어있길래 추가했습니다. 
1. 사이드이펙트가 없..을 거라고 믿습니다.
2. 기존 코드 보니까 이 부분에 막혀서 호출단에서 한 번 더 validate한 부분은 있던데 언제 한번 청소해야할 것 같아요
> feat: 게시글 조회 api 응답 수정

- src/main/java/in/koreatech/koin/domain/user/model/UserToken.java
1. refresh token 기간을 2주에서 3개월로 변경하였습니다.
- 3개월로 변경한 이유
- 사용자들이 방학 기간 동안 코인을 잘 사용하지 않음 -> 방학이 끝난 후 다시 들어오면 로그인이 풀림
-> 방학이 끝나도 로그인이 풀리지 않도록 방학 기간인 3개월로 변경
> refactor: refreshToken 기간 변경

- src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
1. v1 시간표 조회 api에서 커스텀 시간표 조회할 때 null 값을 필드에 넣도록 하였습니다.
> fix: v1 시간표 조회 api에서 커스텀 시간표 조회할 때 에러 해결

- src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
- src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
- src/main/java/in/koreatech/koin/domain/community/dto/ArticlesResponse.java
- src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
- close #775
1. 게시글 검색을 간단하게 구현했습니다.
1. 깊게 들어가기 시작하면 아주 복잡해지는데, 지금 일정도 빡빡하고 막상 조회해보니 검색이 체감될 정도로 길어지지는 않는 것 같아서 일단 이대로 진행하려고 합니다.
2. 이번에 작성한 api 응답 명세 중에 맞지 않는 부분들이 있어 수정했습니다.
1. 목록 조회에서 content 필드 제거
2. 페이지네이션 관련 필드 네이밍컨벤션 통일
> feat: 게시글 검색

- src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
- src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
- src/main/java/in/koreatech/koin/domain/shop/dto/CreateReviewRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyReviewRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewsResponse.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopsResponseV2.java
- src/main/java/in/koreatech/koin/domain/shop/repository/ShopReviewRepository.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
- src/main/java/in/koreatech/koin/global/validation/NotBlankElement.java
- src/main/java/in/koreatech/koin/global/validation/NotBlankElementValidator.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
- close #799
- close #800
- close #801 
1. 리뷰 조회 API 응답에 신고 여부 필드를 추가하였습니다.(이에 따른 테스트 코드 수정)
2. 리뷰 추가, 수정시 메뉴명에 공란을 넣을 수 없도록 예외처리 하였습니다.
- `@NotBlankElement`어노테이션을 만들어서 예외처리 하였습니다.
- 이와 관련된 테스트코드 추가하였습니다.
3. 리뷰 조회 API의 응답에 신고된 리뷰도 포함되도록 변경하였습니다.
4. 모든 상점 조회 API에 신고된 리뷰의 내용도 반영하도록 변경하였습니다.
> feat: 리뷰 조회 API 응답에 신고 여부 필드 추가

- src/main/java/in/koreatech/koin/global/domain/test/controller/TestController.java
- src/main/java/in/koreatech/koin/global/fcm/FcmClient.java
- close #이슈번호
1. notification과 data 두 페이로드에 대한 메시지 생성을 분리했습니다.
- fcm은 notification과 data를 선택적으로 처리하는 것이 불가능하여 필요한 정보만 전송해야 한다고 합니다.
- 안드로이드의 경우 구버전은 notification을 통해, 신버전은 data를 통해 알림을 처리할 예정입니다.
- **공통**
- 받을 대상(`device token`)과 내용(`title`,` message` 등) 전달
- **Notification 페이로드**
- FCM에서 자동으로 휴대폰 상단바에 알림을 띄워 줌(코인 앱에서의 처리가 아닌 fcm이 알림을 띄움)
- Andriod, iOS 둘 다 백그라운드(앱이 꺼져있는 상황), 포그라운드(앱 활성화 중)에서 모두 알림 띄우기 가능
- Android
- 알림 클릭을 통한 어플 접속 가능
- 대신 딥링크(특정 상점의 페이지 등)까지는 불가능
- iOS
- 알림 클릭을 통해 딥링크까지 접속 가능
- **data 페이로드**
- FCM에서 데이터 처리 관련 내용을 전달해 줌
- 자동으로 알림을 띄워주지는 않기 때문에 코인 앱 자체에서 알림을 띄우도록 data를 이용한 처리가 필요함
- Android
- 백그라운드, 포그라운드 모두 데이터 처리 가능
- data를 통해 커스텀 알림(클릭 시 딥링크 접속, 알림 문구 수정 등) 가능
- iOS
- 백그라운드에서는 data 페이로드 처리 불가능
- 그래서 notification 페이로드와 함께 활용해야 함
> fix : fcm 알림의 버전 분리

- src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
- src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
- close #813
1. 상점 생성, 수정시 이미지 url의 요소가 공백인 경우 예외처리 하였습니다.
2. 이전에 만들어 두었던 `@NotBlankElement`어노테이션을 활용하였습니다.
> fix: 상점 생성, 수정시 이미지 url의 요소가 공백인 경우 예외처리

- src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopReviewReportStatusRequest.java
- close #820
1. enum에 `@NotBlank`어노테이션을 이용해서 발생한 문제였습니다.
2. `@NotNull`어노테이션으로 변경해줬습니다.
> fix: 리뷰 신고 변경 API의 dto필드 NotBlank에서 NotNull로 변경

- src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterCheckResponse.java
- src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- close #818
1. 클라이언트의 요청에따라 GET/semesters와 GET/semesters/check에 대한 학기 반환값을 '겨울-2-여름-1'과 같은 순으로 변경했습니다.
> feat: 학기 반환 순서 변경

- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureUpdateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
1. entity에서의 길이 제한을 충족시키지 못한 문제로 dto에서 유효성 검사를 할 수 있게 size 어노테이션를 추가했습니다.
> fix: timetable dto에서 유효성 검사 추가

- src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
- src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
- src/main/java/in/koreatech/koin/domain/community/dto/ArticleResponse.java
- src/main/java/in/koreatech/koin/domain/community/exception/ArticleBoardMisMatchException.java
- src/main/java/in/koreatech/koin/domain/community/exception/BoardNotFoundException.java
- src/main/java/in/koreatech/koin/domain/community/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/repository/BoardRepository.java
- src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
1. GET /article/{id} 응답에 `prev_id`, `next_id`를 추가하여 이전글/다음글 기능을 사용할 수 있게 했습니다.
2. article.isNotice를 기반으로 공지글 여부를 판단하던 기존 로직을 article.board.isNotice를 기반으로 판단하도록 수정했습니다.
> feat: 게시글 조회 응답 필드 추가 및 로직 오류 수정

- src/main/java/in/koreatech/koin/domain/community/article/model/ArticleSearchKeyword.java
- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
1. db에 timestamp, 엔티티는 localdatetime으로 되어 있는데 인식을 못해서 columndefinition으로 타입을 명시해줬습니다.
> fix: searchkeyword 엔티티 컬럼 타입 명시

- src/main/java/in/koreatech/koin/domain/community/keyword/controller/KeywordApi.java
- src/main/java/in/koreatech/koin/domain/community/keyword/controller/KeywordController.java
- src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
- src/test/java/in/koreatech/koin/acceptance/KeywordApiTest.java
- close #847 
1. 클라이언트의 요청으로 키워드 추천 api를 비로그인 api로 수정했습니다.
2. 레디스에 캐싱하는 로직을 최근에 사용자가 추가한 키워드가 비어 있을 때가 아니라 15개가 안될 때 전체 조회해서 가져오는 것으로 로직을 변경했습니다. 항상 키워드를 15개를 반환하게 하기 위함입니다.
> refactor: 키워드 추천 api를 비로그인 api로 변경

- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
1. 테스트 응답 값을 순서에 상관 없이 검사 할 수 있도록 수정 했습니다.
> fix: 많이 검색한 키워드 추천 api 테스트 응답 값 순서에 상관 없도록 수정

- src/main/java/in/koreatech/koin/domain/shop/model/ReviewEventListener.java
- src/main/java/in/koreatech/koin/domain/shop/model/ReviewRegisterEvent.java
- src/main/java/in/koreatech/koin/domain/shop/model/ReviewReportEvent.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
- src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotificationFactory.java
- src/test/java/in/koreatech/koin/AcceptanceTest.java
- src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
- src/test/resources/application.yml
- close #851 
1. 리뷰작성, 리뷰신고시 `코인_이벤트알림`채널에 알림이 가도록 작성하였습니다.
2. 이벤트가 발생했는지 테스트코드도 추가해줬습니다.
> feat: 리뷰작성, 리뷰신고 모니터링을 위한 슬랙으로 알림 발송

- src/main/resources/db/migration/V52__update_coopshop_semester_typo.sql
- close #이슈번호
1. "학기 중"에서 "중"은 클라이언트에서 띄워주는 글자라서 삭제하였습니다.
> fix : 생협 운영시간 학기에서 "중" 삭제

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/java/in/koreatech/koin/global/config/LocalDateAttributeConverter.java
- src/main/resources/db/migration/V51__update_koreatech_articles_registered_at.sql
- src/main/resources/db/migration/V53__update_koreatech_articles_registered_at.sql
- close #854 
1. `registered_at`을 `datetime`으로 수정
2. 이에 맞게 attribute converter 수정
시간 날리고 날짜만 저장하도록 수정했습니다.
`yy.MM.dd HH:mm:ss` → `yyyy-MM-dd`
`yyyy-MM-dd HH:mm:ss` → `yyyy-MM-dd`
========
시간을 저장은 하지만 사용하지 않습니다.
`yyyy-MM-dd HH:mm:ss` → `yyyy-MM-dd HH:mm:ss`
`yy.MM.dd HH:mm:ss` → `yyyy-MM-dd HH:mm:ss`
`yyyy-MM-dd` → `yyyy-MM-dd 00:00:00`
> fix: registered_at 업데이트

- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
- src/main/java/in/koreatech/koin/domain/community/article/dto/ArticleResponse.java
- src/main/java/in/koreatech/koin/domain/community/article/dto/ArticlesResponse.java
- src/main/java/in/koreatech/koin/domain/community/article/dto/HotArticleItemResponse.java
- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/article/model/redis/ArticleHit.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/redis/ArticleHitRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/redis/HotArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/scheduler/ArticleScheduler.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- src/test/java/in/koreatech/koin/acceptance/ArticleApiTest.java
- close #776 
1. Article 관련 클래스명이 Community로 남아있는 부분이 있어 수정했습니다.
1. 매일 6시에 최근 1달간 업로드된 모든 게시글의 조회수를 기록한다.
2. 전날 6시와 오늘 6시 사이에 조회수가 많이 올라온 게시글을 인기 게시글로 지정한다.
1. 조회수 상승량에 대해 내림차순으로 정렬한다.
2. 내일 6시 전까지는 반영하지 않고 대기하기 때문에 이 결과를 기록해두고 추후 요청이 오면 그대로 반환한다.
3. 조회수 차이가 없는 게시글은 인기 게시글에서 제외한다.
1. 여기서 여러 문제가 파생되지만 3번 로직으로 해결된다.
2. 단, 4번과 같은 현상이 일어날 수 있다.
3. 인기 게시글 조회 시 지정된 인기 게시글 수가 10개 미만이라면 가장 높은 조회수를 가진 게시글들을 뒤에 이어붙여 반환한다.
1. 최근 1달간 업로드된 모든 게시글 중 조회수가 높은 순으로 정렬한다.
2. 이걸 인기 게시글 뒤에 덧붙여 반환한다.
3. ex) 인기게시글이 3개뿐이라면 -> 조회수 높은 게시글 7개를 뒤에 붙여 반환한다.
4. 조회수가 높은 게시글보다 조회수가 오른 게시글이 우선순위를 가지기 때문에, 조회수만 보면 자연스럽지 않은 상황이 연출될 수 있습니다.
1. 극단적인 예시를 들어보면, 모든 게시글의 조회수가 어제와 그대로인 상황에서 하나의 게시글만 조회수가 1 올랐다면 아래와 같은 응답이 반환됩니다.
```
[
{
"hit": 1, <- 1위
},
{
"hit": 7777, <- 2위
},
{
"hit": 1650, <- 3위
},
{
"hit": 1242, <- 4위
},
... …
```
> refactor: 인기 게시글 조회 내부 로직 수정

- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TrackApiTest.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- src/test/java/in/koreatech/koin/acceptance/VersionApiTest.java
-  #853 
아래 테스트 코드들을 mockMvc로 변경 & 메서드명 한글로 변경
1. Timetable
2. TimetableV2
3. Track
4. User
5. Version
- UserApiTest에서 실패한 테스트
- 이메일_요청을_확인_후_회원가입_이벤트가_발생하고_Redis에_저장된_정보가_삭제된다()
- 학생_회원가입_후_학교_이메일요청_이벤트가_발생하고_Redis에_저장된다()
- TimetableApiTest에서 문제 있는 테스트
- 시간표_삭제_동시성_예외_적절하게_처리하는지_테스트한다()
- TimetableV2ApiTest에서 문제 있는 테스트
- isMain이_false인_frame과_true인_frame을_동시에_삭제한다()
시간표 테스트에서 동시성 테스트는 트랜잭션 어노테이션이 적용되면 실패하는 것 같아 적용시키지 않았습니다. 
적용시킨 테스트와 적용 안시킨 테스트를 같이 실행하면 다른 테스트들에 영향을 줘서 실패시키는 것 같습니다.
> task: 테스트코드 mockMvc로 변경

- src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotificationFactory.java
- src/test/resources/application.yml
- close #881 
1. 상점 리뷰 등록, 신고시 알림 채널을 `코인_이벤트알림` → `코인_상점리뷰`로 변경하였습니다.
#코인_상점리뷰: https://bcsdlab.slack.com/archives/C07MU3SG7PB
> refactor: 상점 리뷰 등록, 신고시 알림 채널 변경

- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
- close #879
**1.  로직 수정**
학기에 메인시간표 1개를 필수로 두게했지만, 현재 발생한 문제는 기존 시간표 프레임 수정할때 메인시간표를 false로 변경하고 나면 메인시간표를 1개를 필수로 두어야하는 정합성에 불일치가 생겨 로직 수정했습니다.
**2. DB데이터 수정**
현재 발생한 문제로 인해 stage DB에  {user_id=1020, semester_id=10}과 {user_id=1782, semester_id=11} 두개의 데이터에서 메인시간표가 존재하지 않는 정합성 불일치가 존재합니다. 
그래서 {user_id=1020, semester_id=10}에 해당하는 id=1046데이터를 is_main=1로 변경하고 {user_id=1782, semester_id=11}에 해당하는 id=2048을 is_main=1로 변경하고자합니다.
> fix: 메인시간표 필수로 수정

- src/main/java/in/koreatech/koin/domain/community/keyword/controller/KeywordApi.java
- src/main/java/in/koreatech/koin/domain/community/keyword/controller/KeywordController.java
- src/test/java/in/koreatech/koin/acceptance/KeywordApiTest.java
1. 권한 설정을 해줬습니다.
늦게 올려서 죄송합니다ㅠ
별도의 새로운 role을 만들지 그냥 admin으로 할 지 의견 한번 씩 주시면 감사하겠습니다.
이 pr은 batch의 다음 [pr]( https://github.com/BCSDLab/KOIN_BATCH/pull/138)과 연결됩니다.
> refactor: 공지사항 알림 api admin만 호출 할 수 있게 변경

- src/main/java/in/koreatech/koin/domain/community/article/model/ArticleSearchKeyword.java
- src/main/java/in/koreatech/koin/domain/community/article/model/ArticleSearchKeywordIpMap.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleSearchKeywordIpMapRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleSearchKeywordRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- src/main/resources/db/migration/V60__alter_search_keywords_and_ip_map_unique_cascade.sql
1. 동시에 요청이 여러개가 들어올 때 중복 검사를 하지 못하고 두 개 이상이 저장 되는 것을 방지하기 위해 db에 unique 속성을 추가했습니다.
2. 삭제 할 일이 사실상 없지만 cascade를 건 이유는 혹시나 모르게 삭제 할 일이 생길 경우 db의 참조 무결성을 보장하기 위해서 안전장치 용도로 걸었습니다.
원래 동시성 제어 어노테이션이랑 같이 처리 할 생각이였는데 생각보다 동시성 제어 작업이 길어진 점과.. 따로 올리는 것이 낫겠다는 생각이 들어서 급히 올립니다.
> refactor: 많이 조회하는 키워드 테이블 제약 조건 추가

- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureResponse.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureUpdateRequest.java
- close #908 
1. 한글로 출력되고 있던 Example Value를 영어로 수정했습니다.
-> description 대신 name을 사용하는 부분이 있어서 통일시켰습니다.
간단한 수정사항이라 잔디 채우러 오셔도 됩니당
> refactor: Swagger 한글 Example value 영어로 수정

- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/dto/UserAccessTokenRequest.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- close #905
1. 토큰 파라미터를 통해 현재 사용자가 로그인중인지 확인할 수 있는 API입니다.
> feat: 로그인 여부 확인  API

- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableFrameCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableFrameUpdateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableFrameUpdateResponse.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureResponse.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
- src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
- close #916 
1. TimetableLecture Response DTO에 lecture_id를 추가했습니다.
2. TImetableFrame create시 이름을 지정할 수 있도록 Request DTO에 timetableName을 추가했습니다.
- NOT_REQUIRED로 설정해서 입력하지 않을 시 전과 같이 "시간표1"로 만들어집니다.
- timetableFrame 관련하여 DTO 내의 이름도 timetableName으로 통일했습니다.
커스텀 시간표에서 사용 예정입니다~ 승주님이 수요일까지 해달라셨는데 조금 늦었네요 ㅎ....
> feat : TimetableLecture Response 컬럼 추가 / TimetableFrame 생성 시 이름 지정 가능

- src/main/java/in/koreatech/koin/domain/shop/repository/shop/dto/ShopCustomRepository.java
- close #924
1. 모든 상점 조회시 삭제된 리뷰가 통계에 포함되지 않도록 변경하였습니다.
> hotfix: 모든 상점 조회시 삭제된 리뷰는 통계에 포함 안되도록 변경

- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
- src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
- close #933
1. 학기 삭제를 위해 모든 프레임을 삭제하는 api를 만들었습니다.
> feat: 모든 시간표 프레임 삭제 api 구현

- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
- src/main/resources/db/migration/V66__modify_column_timetable_lecture_text.sql
- close #935 
1. TimetableLecture의 class_time 컬럼의 데이터 형식을 TEXT로 변경했습니다.
- 많은 데이터를 넣는 과정에서 VARCHAR(255)의 크기가 작아서 생기는 오류가 있어서 데이터 형식을 수정했습니다.
빠리 빠리
> fix : timetableLecture class_time 데이터 형식 TEXT로 변경

- src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopsResponse.java
- src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopsResponseV2.java
- src/main/java/in/koreatech/koin/domain/shop/repository/shop/dto/ShopCustomRepository.java
- src/main/java/in/koreatech/koin/domain/shop/repository/shop/dto/ShopInfoV1.java
- src/main/java/in/koreatech/koin/domain/shop/repository/shop/dto/ShopInfoV2.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- src/test/java/in/koreatech/koin/fixture/ShopFixture.java
- close #943 
1. api응답시간을 최적화 하기 위해서 query dsl을 이용하였는데, 로직상 문제가 있어서 기존 방식으로 원복합니다.
> hotfix: isOpen로직 query dsl에서 기존 방식으로 원복

- src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitApi.java
- src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitController.java
- src/main/java/in/koreatech/koin/admin/benefit/dto/AdminModifyBenefitCategoryRequest.java
- src/main/java/in/koreatech/koin/admin/benefit/dto/AdminModifyBenefitCategoryResponse.java
- src/main/java/in/koreatech/koin/admin/benefit/exception/BenefitDuplicationException.java
- src/main/java/in/koreatech/koin/admin/benefit/repository/AdminBenefitCategoryMapRepository.java
- src/main/java/in/koreatech/koin/admin/benefit/repository/AdminBenefitCategoryRepository.java
- src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
- src/main/java/in/koreatech/koin/domain/benefit/model/BenefitCategory.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminBenefitApiTest.java
- close #941 
1. 어드민 상점 혜택 카테고리 수정 기능 추가했습니다.
명세서대로 어드민 상점 혜택 카테고리 수정 기능 추가 및 테스트 간단하게 작성하였습니다.
> feat: 어드민 상점 혜택 카테고리 수정 기능 추가

- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- src/test/resources/application.yml
1. 존재하지 않는 api를 호출할 경우 404 Not Found 응답 대신 커스텀 예외 메시지를 반환하도록 수정했습니다.
코드 라인 수 자체는 굉장히 적지만 온전한 이해를 위해서는 배경지식이 필요하기 때문에 관련 블로깅 해두었으니 리뷰하기 전에 읽어보시기를 권장드립니다.
[관련 포스팅](https://velog.io/@songsunkook/%EC%A1%B4%EC%9E%AC%ED%95%98%EC%A7%80-%EC%95%8A%EB%8A%94-API-%EC%9D%91%EB%8B%B5-%EC%BB%A4%EC%8A%A4%ED%85%80%ED%95%98%EA%B8%B0)
yml에 추가해야할 부분이 있기 때문에 머지되면 stage, prod 설정파일에 직접 추가해두겠습니다.
> feat: 존재하지 않는 api 요청 시 커스텀 응답 반환

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
1. registered_at이 null값을 반환하지 않도록 수정
> fix: article 로직 수정

- src/main/java/in/koreatech/koin/admin/notice/dto/AdminNoticeResponse.java
- src/main/java/in/koreatech/koin/admin/notice/dto/AdminNoticesResponse.java
- src/main/java/in/koreatech/koin/admin/notice/repository/AdminKoinArticleRepository.java
- src/main/java/in/koreatech/koin/admin/notice/repository/AdminKoreatechArticleRepository.java
- src/main/java/in/koreatech/koin/admin/notice/repository/AdminNoticeRepository.java
- src/main/java/in/koreatech/koin/admin/notice/service/AdminNoticeService.java
- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
1. 어드민 페이지에서 코인 공지 (단건, 리스트) 조회 시 소프트딜리트된 대상이 검색 대상에 포함되면 NPE가 발생하는 문제를 해결했습니다.
> fix: 어드민 공지 조회 API 버그 수정

- build.gradle
- src/main/java/in/koreatech/koin/domain/coop/controller/CoopApi.java
- src/main/java/in/koreatech/koin/domain/coop/controller/CoopController.java
- src/main/java/in/koreatech/koin/domain/coop/dto/ExcelResponseBuilder.java
- src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
- src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
- src/main/resources/logback-spring.xml
- close #556 
1. 영양사님께서 기간을 지정하면 식단을 엑셀형식으로 다운로드 받을 수 있는 기능을 구현했습니다
2. isCafeteria라는 Boolean 값을 통해 학생식당만 필터링 가능
3. 이미지를 넣는 방식은 찾아봐야함
- 코드가 지저분합니다..
> feat: 영양사님 엑셀 다운로드 기능 구현

- src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopSemesterResponse.java
- src/main/java/in/koreatech/koin/admin/coopShop/dto/AdminCoopSemestersResponse.java
- src/main/java/in/koreatech/koin/domain/coopshop/dto/CoopShopsResponse.java
- src/main/resources/db/migration/V77__insert_coop_shop_semester.sql
- src/test/java/in/koreatech/koin/acceptance/CoopShopApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminCoopShopApiTest.java
- close #이슈번호
1. `coopshop`에 기존 데이터가 없는 로컬에서도 동작하도록 flyway 쿼리를 수정하였습니다.
- 초기에 직접 DB에 `coopshop` 정보를 추가하면서 로컬과의 `auto_increment` `시작 id`가 차이가 나 발생하는 오류를 수정하였습니다.
> fix : coopshop 기존 데이터가 없는 로컬에서도 동작하도록 flyway 쿼리 수정

- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureResponse.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
- close #961
timetable_lecture에 lecture_id가 있을때 lecture정보만 반환시켜주며 수정로직을 만들지 않았기때문에, 정규시간표를 수정하려할때 classTime, grades, classTitle, professor데이터가 수정이 안되고 변경된 데이터로 반환이 안되는 오류가 존재합니다.
그렇기때문에 lecture_id가 있어도 데이터가 수정될 수 있게 변경했으며, response 반환 로직에서 timetable_lecture에 데이터가 null값이라면 lecture의 정보를 반환시켜주고, null값이 아니라면 timetable_lecture 데이터를 반환시켜주게 변경했습니다.
정상 작동된 스웨거 모습
> fix: PUT/timetables/lecture 로직 수정

- src/main/java/in/koreatech/koin/global/domain/notification/service/NotificationService.java
- src/main/java/in/koreatech/koin/global/domain/test/controller/TestController.java
- src/main/java/in/koreatech/koin/global/fcm/FcmClient.java
- close #이슈번호
1. 기존에 안드로이드의 fcm 알림 페이로드 전달 방식을 notification으로 appPath를 전달하는 방식에서 data로 scheme uri를 전달하는 방식으로 수정하였습니다.
- notification 페이로드는 firebase에서 알림창을 생성해서 띄워주기 때문에 딥링크와 같은 커스텀이 불가능합니다.
- 그래서 딥링크(알림 클릭을 통해 구체적인 페이지 진입)를 위해 코인 어플이 자체적으로 커스텀 알림을 생성하여 띄울 수 있도록 data 페이로드를 사용하는 방식으로 수정하였습니다.
- iOS는 notification 페이로드로도 딥링크가 가능하여 수정된 부분이 없습니다.
3. 두 방식은 하위호환성을 지키며 동시에 사용이 불가능해 기존의 방식은 삭제하였습니다.
- 해당 pr이 배포된 이후부터는 최신 버전으로 업데이트하기 전까지 알림이 오지 않습니다.
- 하위호환이 가능하려면 알림을 각 방법(notification, data)으로 두 번씩 발송을 해야하기 때문에, 하나의 방식(data)만 유지하고 홍보를 통해 새로운 버전으로 업데이트를 유도하기로 결정했습니다.
- 안드로이드 fcm 페이로드
- 기존 응답
```
{
"notification": {
"title": "식단 품절 알림",
"message": "식단이 품절되었어요ㅠ. 다른 식단 보러 가기",
"image_url": "~@#%#^&$$^T",
"click-action": "DINING"     ( ⇢  AppPath )
},
"data": {
"type": "message"
}
}
```
- 수정된 응답
```
{ …
```
> fix : 안드로이드 fcm 알림 페이로드 notification → data 로 수정

- src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEventListener.java
- src/main/java/in/koreatech/koin/domain/coop/model/CoopEventListener.java
- src/main/java/in/koreatech/koin/domain/shop/model/event/listener/ShopEventListener.java
- src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
- src/main/java/in/koreatech/koin/global/domain/test/controller/TestController.java
- src/main/java/in/koreatech/koin/global/fcm/FcmClient.java
- src/main/java/in/koreatech/koin/global/fcm/MobileAppPath.java
- close #이슈번호
1. fcm 스킴 uri 의 도메인명을 소문자로 수정하였습니다.
- ex: KEWORD?id=1 → keyword?id=1
> refactor : fcm 스킴 uri의 도메인 명 소문자 통일

- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
삭제된 게시판의 게시글 조회 시 예외를 반환하도록 수정했습니다.
> fix: 삭제된 게시판의 게시글 조회 시 예외 반환

- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
1. 일부 게시글 조회 네이티브 쿼리에 `where is_deleted = false`가 누락된 부분을 수정했습니다.
> hotfix: 네이티브 쿼리 soft delete 누락 반영 (main)

- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- close #969 
1. 조회 api의 redisson 락 점유 시간이 적어 에러가 발생한 것으로 판단해서 redisson 락 점유 시간을 증가시켰습니다
> fix: 게시글 조회 api redisson lock 시간 연장

- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
1. 쿼리 오류를 수정해서 인기게시글에 코인 게시글도 반영되도록 했습니다.
> fix: 코인 게시글은 인기 게시글에 포함되지 않는 쿼리 수정

- src/main/java/in/koreatech/koin/global/domain/test/controller/TestApi.java
- src/main/java/in/koreatech/koin/global/domain/test/controller/TestController.java
- close #이슈번호
1. 스웨거에서 테스트 알림 발송 시 필드 값 null 허용 여부(required)를 `false`로 수정했습니다.
- 기존에 사용하던 `notification 페이로드`는 `null` 값이 허용되지만,
- 새로 바꾼 `data 페이로드`는 Map 형태로 전달되기 때문에 `null`을 삽입하면 에러가 납니다.
> fix : 테스트 알림 필드 required로 수정

- src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
1. 키워드 생성 api의 redisson 락 점유 시간을 늘렸습니다. lock 점유시간을 5초로 늘린 이유는 평소 30ms가 걸리다가 공지사항 크롤링과 같이 mysql 에 값을 insert 하는 시간이 겹치면 api 시간이 4초까지 늘어나기 때문입니다.
2. 평소 따닥 관련 문제가 발생하던 키워드 삭제 api와 학생 인증 api에 redisson을 적용시켰습니다.
> feat: 키워드 생성 redisson lock 점유 시간 연장, 키워드 삭제 redisson 적용, 학생 인증 redisson 적용

- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableLectureRepositoryV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
- src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
- close #994 
- frame_id와 lecture_id를 이용해서 timetableLecture를 삭제하는 API를 추가했습니다. 
- 관련 테스트 코드 추가했습니다.
모바일 시간표에서 정규 강의 삭제 API [요청](https://bcsdlab.slack.com/archives/C06NEM6EY3W/p1730645754281849)이 있어서 작업을 진행했습니다.
강의에서 `is_deleted` 필드를 사용하지 않고, 하드 딜리트 하는 로직으로 보여서 `네이티브 쿼리`를 사용했습니다.
- JPQL 쿼리
```sql
Hibernate: 
delete 
from
timetable_lecture 
where
frame_id=? 
and lectures_id=? 
and (
timetable_lecture.is_deleted=0
)
```
- 네이티브 쿼리
```sql
Hibernate: 
DELETE 
FROM
timetable_lecture 
WHERE
frame_id = ? 
AND lectures_id = ? 
```
**메소드 네이밍이 조금 쉽지않은데,, 추천 받습니다..!**
> feat: 모바일 정규 강의 삭제 API 추가

- src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
- src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
- src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableUpdateRequest.java
- close #993 
1. 옛날 사용하던 Timetable 관련 Swagger 문서를 수정했습니다.
-> 일관성이 없어 관련 값을 알아보기 힘들다는 클라이언트의 요청이 있어, description으로 통일했습니다.
수정 전
수정 후
현재 웹에선 사용하진 않는 코드긴 한데, 모바일 커스텀 시간표 개발 중 클라이언트님들의 편의성을 위해 수정했씁니다.
그냥 진짜 간단한 수정이라서 잔디 채우셔도 됩니다.
> chore : Swagger 일관성을 위해 name -> description으로 변경

- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimeTableLecturesDeleteRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableLectureRepositoryV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
- src/test/java/in/koreatech/koin/acceptance/TimetableV2ApiTest.java
- close #998 
- timetableLecture id 리스트를 쿼리 파라미터로 받아 강의를 삭제하는 API를 추가했습니다.
- 관련 테스트 코드 추가했습니다.
- 이전 작업에서 잘못 추가된 코드를 삭제했습니다.
> feat: timetableLecture id를 리스트로 받아 삭제하는 API 추가

- src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopApi.java
- src/main/java/in/koreatech/koin/admin/shop/controller/AdminShopController.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopCategoryRequest.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopCategoryRequest.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopReviewReportStatusRequest.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopCategoryResponse.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopParentCategoryResponse.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminShopsReviewsResponse.java
- src/main/java/in/koreatech/koin/admin/shop/exception/ShopParentCategoryNotFoundException.java
- src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopCategoryRepository.java
- src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopNotificationMessageRepository.java
- src/main/java/in/koreatech/koin/admin/shop/repository/AdminShopParentCategoryRepository.java
- src/main/java/in/koreatech/koin/admin/shop/service/AdminShopService.java
- src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopCategory.java
- src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopNotificationMessage.java
- src/main/java/in/koreatech/koin/domain/shop/model/shop/ShopParentCategory.java
- src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopNotificationBufferRepository.java
- src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
- src/main/resources/db/migration/V93__alter_shop_main_categories_table_name.sql
- src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
- src/test/java/in/koreatech/koin/fixture/ShopCategoryFixture.java
- src/test/java/in/koreatech/koin/fixture/ShopNotificationMessageFixture.java
- src/test/java/in/koreatech/koin/fixture/ShopParentCategoryFixture.java
- close #1004
- 어드민 상점 카테고리를 생성하거나 수정할 때 상위 카테고리를 선택하는 기능 추가
1. 메인 카테고리의 추가로 인한 이름 충돌 방지를 위해 main_category를 parent_category로 변경
2. 드롭다운을 위해 상점의 모든 상위 카테고리를 조회하는 api 추가
3. 기존 상점 카테고리 생성, 수정 dto에 상위 카테고리 id 필드 추가
4. 기존 상점 카테고리 단일 조회 dto에 상위 카테고리 id 필드 추가
5. 기존 상점 카테고리 수정 시 카테고리명을 그대로 사용할 경우 중복예외처리하는 오류 수정
6. 테스트 코드 작성 및 기존 테스트 코드 수정
> feat: 어드민 상점 카테고리 생성, 수정시 상위 카테고리 선택 기능 추가

- src/main/java/in/koreatech/koin/admin/version/repository/AdminVersionRepository.java
- src/main/java/in/koreatech/koin/admin/version/service/AdminVersionService.java
- close #이슈번호
1. 강제업데이트 히스토리 조회 시 오름차순에서 내림차순으로 나오도록 수정했습니다.
> fix : 강제업데이트 히스토리 조회 내림차순으로 수정

- src/main/java/in/koreatech/koin/admin/user/controller/AdminUserApi.java
- src/main/java/in/koreatech/koin/admin/user/controller/AdminUserController.java
- close #1016 
1. 클라이언트 요청이 들어와서 어드민 본인의 정보를 조회하는 API를 추가했습니다.
> feat: 로그인 어드민 계정 정보 조회 API 추가

- src/main/java/in/koreatech/koin/domain/shop/cache/dto/ShopCategoryCache.java
- close #1018 
1. shopCategories ID대신 ShopcategoryMap ID가 반환되는 에러 수정
> fix: v2/shops API에서 ShopCategories ID가 잘못 반환되는 에러 수정

- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureCreateRequest.java
- close #1020 
1. 정규 강의 생성 과정에서 강의 시간이 null 값으로 들어오기 때문에 이를 확인하는 로직을 추가했습니다.
> fix: 강의 시간 null 체크 추가

- src/main/java/in/koreatech/koin/domain/shop/model/article/EventArticle.java
- src/main/resources/db/migration/V99__alter_event_articles_drop_unused_column.sql
- close #1043
1. event_articles 테이블 및 엔티티에 남아있던 미사용 컬럼을 제거하였습니다.
-
> chore: event_articles 테이블 및 엔티티의 미사용 컬럼 삭제

- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureUpdateRequest.java
- close #1024
1. 클라이언트들이 정규강의에 대해서 기본적으로 보내야 할 값의 예시를 수정하였습니다.
> fix: timetableLecture DTO swagger 수정

- src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableServiceV2.java
- src/main/java/in/koreatech/koin/global/concurrent/ConcurrencyGuard.java
- close #1013 
1. 4시에 hikariPool 문제가 발생하며 에러가 줄줄이 발생했습니다. 응답이 저렇게 오래걸린 이유는 각종 scheduled작업과, batch 작업이 맞물려서 일시적인 성능 하락으로 인한 문제로 파악하고 있습니다.
2. 해당 문제를 해결하기 위해 우선 전체적인 redisson 시간을 증가 시켰습니다.
3. redisson이 적용된 부분들에 redisson이 관할 하는 부분의 범위를 최소화시켰습니다. transaction의 범위를 줄이는 방식으로 접근했습니다.
> refactor: redisson이 관할 하는 부분 및 transaction 범위 최소화

- src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEventListener.java
> fix: 키워드 알림 메시지에서 중괄호 제거

- src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEventListener.java
- src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
- close #1078 
1. 클라이언트 분들의 요청으로 schemeUri에 무슨 키워드를 보냈는지도 추가했습니다
내일까지 배포해달라고 하셔서 리뷰 빠르게 해주시면 감사하겠습니다ㅠ
> feat: 키워드 알림 schemeUri변경

- src/main/java/in/koreatech/koin/admin/student/service/AdminStudentService.java
- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
- src/main/java/in/koreatech/koin/domain/user/model/User.java
- close #1088 
1. 학생 비밀번호 수정 메소드 추가했습니다.
기존 유저들의 비밀번호 수정에는 null이 처리가 안 되어있고, 이를 통일하기 위해 학생 정보수정에서의 비밀번호 처리를 빼는 과정에서 if 처리를 하지않아 학생 정보 수정에서 오류가 발생했습니다.
> fix: 학생 비밀번호 수정 메소드 오류처리

- src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
- close #1097 
1. shop softDelete시에 해당 shop과 관련된 review들도 softdelete 되도록 변경하였습니다.
2. 삭제된 상점 복구시에 해당 shop과 관련된 review들도 복구되도록 변경하였습니다.
- 간단한 변경입니다
> fix: shop softDelete시에 reviews도 softDelete 되도록 수정

- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableLectureResponse.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
- close #1095 
- 기존 데이터에 `, , ,`와 같은 데이터가 있으면 인덱스가 터지는 버그를 고쳤습니다.
- `,`구분자로 데이터를 자르고 공백을 지운 상태로 시간과 매핑을 하는데, 인덱스가 강의 장소 배열보다 넘치게 되는 경우가 발생해서 처리를 했습니다. 
- 리펙토링 과정에서 frame 권한 여부 확인을 frame id와 user id와 매칭하고 있어서 수정했습니다.
> fix: timetableLecture 오류 수정

- src/main/java/in/koreatech/koin/global/config/WebConfig.java
- src/main/resources/mail/change_password_config.html
- close #1100 
1. 학생이 이메일로 비밀번호를 변경 할 수 없었던 오류를 수정했습니다. 
현재 정적파일을 사용하는 곳은 학생이 이메일을 통하여 비밀번호를 수정하는 로직이 있습니다. 예전 [존재하지 않는 API 응답 커스텀하기](https://velog.io/@songsunkook/%EC%A1%B4%EC%9E%AC%ED%95%98%EC%A7%80-%EC%95%8A%EB%8A%94-API-%EC%9D%91%EB%8B%B5-%EC%BB%A4%EC%8A%A4%ED%85%80%ED%95%98%EA%B8%B0) 관련 yml 파일 수정(add-mappings = false)이 있었고, 이 과정에서 정적 파일의 경로를 찾을 수 없는 오류가 있었습니다.
WebConfig 중 `addResourceHandlers`를 추가하여 `/static`으로 통하는 정적 파일의 경로를 지정해줬습니다.
앞으로 정적 파일의 관리가 필요하다면 `/static`에 넣고 사용하시면 됩니다.
ㅜㅜ 빙빙 돌아서 오류는 해결했습니다.. 도와주신 분들 감사합니다.
> fix : 정적 파일 경로 설정 오류(학생 이메일 비밀번호 수정)

- src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/exception/TimetableLectureClassTimeNullException.java
- close #1111 
- 커스텀 강의에서 시간이 null로 들어왔을 경우 예외 처리했습니다.
> fix: 강의 시간 NPE 예외 처리

- src/main/java/in/koreatech/koin/admin/abtest/controller/AbtestApi.java
- src/main/java/in/koreatech/koin/admin/abtest/controller/AbtestController.java
- src/main/java/in/koreatech/koin/admin/abtest/dto/response/AbtestAccessHistoryResponse.java
- src/main/java/in/koreatech/koin/admin/abtest/dto/response/AbtestDevicesResponse.java
- src/main/java/in/koreatech/koin/admin/abtest/model/AccessHistory.java
- src/main/java/in/koreatech/koin/admin/abtest/service/AbtestService.java
- src/main/java/in/koreatech/koin/admin/history/aop/AdminActivityHistoryAspect.java
- close #1103
1. AB테스트 자신의 실험군 조회 API에서 각종 이슈가 발생하고 있습니다. 원인은 최초 편입된 사용자에 대해 동시에 여러 AB테스트가 적용된 페이지에서 동시에 동일 인자로 API를 요청으로 인한 DEADLOCK 발생 및 Null 데이터 삽입으로 확인했습니다. 이를 개선하기 위해 AB테스트 토큰 발급용 API를 추가하였고, 이후 클라이언트 배포 전에 AB테스트 적용 과정을 변경할 것을 요청할 예정입니다. 자세한 내용은 이슈 내용 및 슬랙 확인해주시면 감사하겠습니다!
> fix: AB테스트 토큰 발급용 API 추가

- src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
`GET /timetables`에서 6시 이후 시간은 제외하고 조회되도록 수정하였습니다.
- 문제상황
1. 커스텀 시간표 기능에서 6시 이후 시간을 만듦
2. 커스텀 시간표 기능이 아직 없는 안드로이드 폰에서 시간표를 조회
3. 시간표를 조회했을 때 6시 이후 시간이 조회되면 문제가 생김
- 작업
`TimetableResponse`에서 List<InnerTimetableResponse>에 들어갈 값을 추가하기 전에 filter를 추가하였습니다.
filter에서는 커스텀 시간표일 경우 강의 시간들을 가져와 6시 이후일 경우 추가하지 않도록 하였습니다. 
6시 이전인지 확인하는 코드
```java
if (classTime < 100) {
return classTime < 19;
} else {
int lastTwoDigits = classTime % 100;
return lastTwoDigits < 19;
}
```
- 세자리 숫자일 경우 (ex. [211, 212])
- 맨 첫글자는 요일을 의미해서 0은 월, 1은 화, 2는 수 ...
- 뒤의 두자리는 시간을 의미// 9시: 1 ~ 2,  10시: 3 ~ 4 , ... , 18시: 17~18 
- 두자리 이하 숫자일 경우 (ex. [11, 12])
- 맨 앞에 월요일을 의미하는 0이 있음
- 따라서 11, 12는 월요일 14:00~15:00를 의미
> fix: V1 시간표에서 6시 이후 시간은 제외하고 조회되도록 수정

- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableFrame.java
- src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
- src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableLectureRepositoryV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableFrameService.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
- src/test/java/in/koreatech/koin/fixture/TimeTableV2Fixture.java
- close #1102
1. POST/v2/timetables/lecture/rollback
timetable_lectures_id를 리스트값으로 받아 시간표 강의를 복구합니다.
2. POST/v2/timetables/frame/rollback
2-1. 삭제된 시간표 프레임: 삭제된 시간표 프레임과 그에 속한 강의 정보를 복구합니다. 
2-2. 삭제되지 않은 시간표 프레임: 시간표 프레임에 속한 강의 정보를 복구합니다.
3. Hard delete -> Soft delete로 변경했습니다.
> feat: 삭제된 시간표 강의 복구

- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableApiV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/controller/TimetableControllerV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableFramesResponse.java
- src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableFrameService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
- close #1106 
1. 시간표 프레임을 한번에 조회 할 수 있게 구조를 변경했습니다.
requestparam인 semester가 없을때는 아래와 같은 값을 반환하게 했습니다.
``` json
{
"semesters": {
"20242": [
{
"id": 1,
"timetable_name": "시간표1",
"is_main": false
},
{
"id": 2,
"timetable_name": "시간표2",
"is_main": true
},
{
"id": 3,
"timetable_name": "시간표3",
"is_main": false
}
],
"20241": [
{
"id": 4,
"timetable_name": "시간표1",
"is_main": false
},
{
"id": 5,
"timetable_name": "시간표2",
"is_main": true
},
{
"id": 6,
"timetable_name": "시간표3",
"is_main": false
}
]
}
}
```
> feat: 시간표 프레임 한번에 조회 구현

- src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
이전에 6시 이후 커스텀시간표는 보이지 않게 했던 코드를 제거하였습니다. 
이유: 6시 이후 시간표를 없앨 필요 없었음
> refactor: 6시 이후 시간도 보이게 다시 수정

- src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitApi.java
- src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitController.java
- src/main/java/in/koreatech/koin/admin/benefit/dto/AdminBenefitCategoriesResponse.java
- src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
- src/main/java/in/koreatech/koin/domain/benefit/dto/BenefitShopsResponse.java
- src/main/java/in/koreatech/koin/domain/benefit/repository/BenefitCategoryMapRepository.java
- src/main/java/in/koreatech/koin/domain/benefit/service/ShopBenefitService.java
- src/test/java/in/koreatech/koin/acceptance/BenefitApiTest.java
- close #1122 
1. 상점 혜택 상세보기 필드 추가
api는 기존에 있었고, 기능명세서대로 상점 혜택 상세보기 필드 추가하였습니다.
> feat: 상점 혜택 상세보기 필드 추가

- src/main/java/in/koreatech/koin/domain/bus/model/enums/ShuttleBusRegion.java
노선 지역 이름 반환 시 · 대신 ・사용 
ex: 천안·아산 -> 천안・아산
> chore: 노선 지역 이름 수정

- src/main/java/in/koreatech/koin/domain/coop/exception/DuplicateExcelRequestException.java
- src/main/java/in/koreatech/koin/domain/coop/model/ExcelDownloadCache.java
- src/main/java/in/koreatech/koin/domain/coop/repository/ExcelDownloadCacheRepository.java
- src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
1. 엑셀 다운로드 중복 요청 방지 기능입니다
2. 동일한 인자로 30초 동안 재요청을 방지하는 로직을 만들었습니다
> refactor: 엑셀 다운로드 따닥 방지

- src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
- close #1125 
- 시간표 롤백 과정에서 발생하는 버그를 수정했습니다. [관련 스레드](https://bcsdlab.slack.com/archives/C06NEM6EY3W/p1733835482261379)
- main 시간표 프레임과 main 시간표 프레임이 아닌 시간표 2개가 있음
- main 시간표를 지우면 그 다음 시간표 프레임이 main이 됨
- 그 시간표도 지우면 둘 다 main = false / is_deleted = 1 인 상태로 DB에 유지
- 롤백 API 호출하면 is_delete = 0 으로만 복구되고, main은 여전히 false
- 이때, 시간표 생성하면 다 main = false 으로 생성됨 (시간표 개수로 메인을 판단해서 생기는 문제)
- 롤백 과정에서 현재 시간표의 개수를 바탕으로 main여부를 설정하는 로직을 넣었습니다.
> fix: 시간표 프레임 롤백 로직 수정

- src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusSchedule.java
- src/main/java/in/koreatech/koin/domain/bus/service/route/ExpressBusRouteStrategy.java
- [캠퍼스팀 버스 스프린트 QA](https://docs.google.com/document/d/1mbBPfdgVnKwNOcrNkv6_wwmpEw_mCpqEGbUIUwM2G5A/edit?tab=t.0)
1. 대성 고속버스 스케줄이 반대로 출력되는 오류 수정
2. 메서드 가독성 개선
> fix: 버스 교통편 조회 대성 시간표 오류 수정

- src/main/resources/db/migration/V105__alter_lecture_semester_date_size.sql
- src/main/resources/db/migration/V106__alter_lecture_class_time_size.sql
- close #1141 
- 계절학기 삽입을 위한 lecture 컬럼 크기 변경을 했습니다. 
- semester_date의 크기를 기존 6에서 10으로 늘렸습니다 ex) `2024-여름`
- class_time의 크기를 기존 100에서 255으로 늘렸습니다,
> fix: 계절학기 삽입을 위한 lecture 컬럼 크기 변경

- src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
- src/main/java/in/koreatech/koin/domain/coop/util/CoopScheduler.java
- src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
- close #이슈번호
1. 식단 이미지 알림 로직 분리 작업을 롤백합니다
2. 안드로이드 스테이지 알림 테스트가 지금 안돼서 나중에 수정 되면 테스트 후 배포 예정입니다
> fix: 식단 이미지 알림 롤백 

- src/main/resources/db/migration/V108__add_coopshops.sql
- close #이슈번호
1. 생협 운영장 안경원, 우편취급국을 추가하였습니다.
2. 생협 운영장 운영시간 오타를 수정하였습니다.
- 대즐: 평일/평일 -> 평일/주말
- ![image](https://github.com/user-attachments/assets/4ff40ef7-d6aa-4d8a-bdbe-3257d3690cd6)
> fix : 생협 운영장 추가 및 운영시간 오타 수정

- src/main/java/in/koreatech/koin/domain/graduation/exception/CatalogNotFoundException.java
- src/main/java/in/koreatech/koin/domain/graduation/exception/CourseTypeNotFoundException.java
- src/main/java/in/koreatech/koin/domain/graduation/exception/DepartmentNotFoundException.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/CourseTypeRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/DepartmentRepository.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableLectureResponse.java
- src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
- src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
- src/test/java/in/koreatech/koin/fixture/CourseTypeFixture.java
- src/test/java/in/koreatech/koin/fixture/TimeTableV2Fixture.java
- #1140 
1. GET /v2/timetables/lecture의 응답에 이수 구분 추가
2. 이수 구분 관련 Repository, Exception 작업
3. POST /v2/timetables/lecture의 요청에서 year, department, code를 이용해서 이수 구분 id 저장
4. 테스트 코드 수정
student 테이블의 year, department와 timetable_lecture의 code를 이용해서 catalog 테이블의 id를 얻습니다.
catalog의 id를 이용해서 course_type_id를 찾아서 timetable_lecture에 저장하도록 작성했습니다.
timetable_lecture의 course_type_id를 이용해서 이수 구분을 응답으로 반환하도록 작성했습니다.
[노후화 이전 PR](https://github.com/BCSDLab/KOIN_API_V2/pull/932)
> feat: 시간표 조회 API 이수 구분 반환 추가

- src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationController.java
- src/main/java/in/koreatech/koin/domain/graduation/dto/GraduationCourseCalculationResponse.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/StandardGraduationRequirementsRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/StudentCourseCalculationRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- src/main/java/in/koreatech/koin/domain/student/exception/DepartmentNotFoundException.java
- src/main/java/in/koreatech/koin/domain/student/exception/StudentNumberNotFoundException.java
- src/main/java/in/koreatech/koin/domain/student/util/StudentUtil.java
- src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
- src/main/java/in/koreatech/koin/domain/timetableV2/repository/TimetableFrameRepositoryV2.java
- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableFrameService.java
- close #860
사용자 id를 받아서 다음과 같이 동작합니다. 
동작 과정:
**1. 학생 검증**
Student 테이블에서 해당 학생의 정보(학과, 학번 등)를 확인합니다.
학과나 학번이 누락된 경우 예외를 발생시킵니다.
**2. 시간표 데이터 조회**
학생이 수강한 모든 강의를 조회하고, 각 강의가 소속된 대학 요람 데이터(Catalog)를 가져옵니다.
강의명(lectureName), 학생의 입학 연도, 학과 정보를 바탕으로 대학 요람 정보를 조회합니다.
**3. 이수구분별 학점 계산**
조회된 Catalog 데이터를 기반으로, 각 이수구분(courseType)별로 학점을 합산합니다.
**4. 졸업 요건 비교**
학생의 학과와 입학 연도를 기준으로 StandardGraduationRequirements에서 졸업 기준 정보를 가져옵니다.
각 이수구분별 졸업 기준 학점과 계산된 학점을 비교합니다.
**5. 결과 저장 및 반환**
각 이수구분별 계산 결과를 StudentCourseCalculation 테이블에 저장하거나 업데이트합니다.
응답 객체(GraduationCourseCalculationResponse)를 생성하여 클라이언트에 반환합니다.
> feat: 졸업학점 자신이 들은 학점 보여주는 기능 구현

- src/main/java/in/koreatech/koin/domain/timetableV3/controller/SemesterControllerV3.java
- src/main/java/in/koreatech/koin/global/config/swagger/SwaggerGroupConfig.java
- close #1157
전 PR에서 누락된 스웨거 그룹에서 timetableV3패키지 경로 추가했습니다.
+controller에서 인터페이스 상속하는걸 깜빡해서 추가했습니다.
> feat: 스웨거 그룹 timetableV3 추가

- src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/LectureInfoRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableCustomLectureCreateRequest.java
- close #1165 
- start_time과 end_time에 NotNull 어노테이션을 적용했습니다.
- 학점이 null인 경우 0으로 설정했습니다.
> fix: 커스텀 강의 생성 유효성 검증 추가 

- src/main/java/in/koreatech/koin/domain/timetableV2/dto/response/TimetableLectureResponse.java
- timetableV2에서 온라인 강의(ex. 케이묵)을 반환 시 발생하는 오류를 수정했습니다.
- 온라인 강의는 classTime이 `[]`
- 앞뒤 괄호를 지우면 공백이 남고, 이를 Integer로 변환을 하게 되면 오류가 발생합니다.
> hotfix: timetableV2 온라인 강의 응답 오류 수정 (main)

- src/main/resources/db/migration/V109__alter__semester.sql
- close #1171 
- flyway 109번을 수정했습니다.
- 2025년 1학기 업데이트 쿼리가 존재하지 않아, 프로덕션에 배포될 경우 빌드에 실패하게 됩니다.
- 이를 방지 위해 109번 flyway에 업데이트 쿼리를 추가했습니다.
- [논의 스레드](https://bcsdlab.slack.com/archives/CGQK77GCB/p1736749535604459)
스테이지 서버를 내린 이후, 적용 내용을 지운 뒤 해당 PR를 머지할 계획입니다.
> fix: 2025년 1학기 업데이트 쿼리 추가

- src/main/java/in/koreatech/koin/domain/bus/dto/CityBusTimetableResponse.java
- src/main/java/in/koreatech/koin/domain/bus/model/enums/CityBusDirection.java
- src/main/java/in/koreatech/koin/domain/bus/model/mongo/CityBusTimetable.java
- src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
[슬랙](https://bcsdlab.slack.com/archives/C06NQT2TY9X/p1734775988419809)
1. 한기대 까지 오는 시간 보정
2. - 병천방면: 출발 정류장 이름 ```천안 터미널``` 반환
- 천안방면: 출발 정류장 이름 ```코리아텍``` 반환
400, 402, 405 각각 기점에서 한기대까지 오는 시간 보정
> fix: 시내버스 시간표 한기대 출발 시간 보정

- src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
- src/main/java/in/koreatech/koin/domain/owner/model/dto/OwnerRegisterEvent.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerSmsService.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerUtilService.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- close #1176 
1. redis에 있는 인증번호 삭제 로직을 email에서 phone으로 변경했습니다.
회원가입시 phone을 이용해야 하는데 email을 이용해서 redis의 key값이 null로 들어가고 있었습니다. 때문에 레디스의 데이터를 이용하는 `GET /admin/users/new-owners`에서도 오류가 발생했습니다.
> fix: 사장님 회원가입 에러 수정

- src/main/java/in/koreatech/koin/admin/owner/service/AdminOwnerService.java
- close #1181 
- 새로운 사장님 조회 로직 버그를 수정했습니다.
- 사장님 회원가입 과정에서 등록되지 않는 가게는 shopid가 null로 저장됩니다. 
- findById 메소드에 null 값이 들어가서 어드민 페이지에서 500 에러가 발생했습니다.
> fix: 새로운 사장님 조회 로직 버그 수정

- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
- src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticleRequest.java
- src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticleResponse.java
- src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticlesRequest.java
- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/article/model/LostItemArticle.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEventListener.java
- src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
- src/main/java/in/koreatech/koin/domain/community/util/KeywordExtractor.java
- src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
- src/test/java/in/koreatech/koin/acceptance/ArticleApiTest.java
- close #이슈번호
1. **분실물 게시판 QA 이슈 수정했습니다.**
- 크기 제한, null 허용(분실물 내용 공백, 사진 개수 제한, 습득 장소 단어 수 에러)
2. **게시글 조회 시 게시판별 분기 처리를 추가했습니다.**
- 웹과 모바일에서의 전체글 조회의 차이가 있어 분기를 추가했습니다.
- **모바일**: 전체 게시글 = 전체 공지 | `boardId: 4`
- **웹**: 전체 게시글 = 전체 공지 + 분실물 | `boardId: null`
3. **키워드 알림 추출 로직을 분리했습니다.**
- `article`, `keyword` 모두에서 공통으로 쓰이는 `matchKeyword`를 `KeywordExtractor`로 분리
4. **키워드 알림 FCM 페이로드에 boardId를 추가했습니다.**
- 분실물 게시글과 일반 게시글의 양식이 달라서 클라이언트측 분기 처리를 위해 추가하였습니다.
> fix: 분실물 게시판 QA 이슈 해결

- src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationApi.java
- src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationController.java
- src/main/java/in/koreatech/koin/domain/graduation/dto/CourseTypeLectureResponse.java
- src/main/java/in/koreatech/koin/domain/graduation/dto/LecturePortionResponse.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/CourseTypeRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/DetectGraduationCalculationRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/StudentCourseCalculationRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- src/main/java/in/koreatech/koin/domain/timetableV2/exception/NotFoundSemesterAndCourseTypeException.java
- src/main/java/in/koreatech/koin/domain/timetableV2/repository/LectureRepositoryV2.java
- src/main/java/in/koreatech/koin/global/config/swagger/SwaggerGroupConfig.java
- src/main/resources/db/migration/V116__add_catalog.sql
- src/main/resources/db/migration/V117__add_detect_graduation_calculation.sql
- close #1140
1. 학기와 이수구분을 입력받아 그에 알맞는 강의들을 출력할 수 있도록 했습니다.
- 학기(년도, 학기), 이수구분를 아래의 사진처럼 입력합니다.
- 그러면 같은 이수구분을 가진 수업들이 일부 정보만을 가지고 출력됩니다.
간단한 로직인데 머리에서 계속 꼬여서 여러 번 해멘 경우..
입력한 학기에서 이수구분을 확인하여 어떤 강의를 들어야하는지 출력하도록 했습니다.
그 외 레포지토리 정리랑 flyway 오류 있어서 수정했습니다. 작업 시 확인해주세요.
로직은 학기(연도+학기)와 이수구분의 이름을 입력받으면 이수구분의 이름으로 이수구분의 아이디를 찾습니다.
이 이수구분의 아이디로 카탈로그에서 모든 강의를 가져옵니다.(현재 좀 무거운데, 중복 처리 된 거 빼면 가벼워 질 것 같습니다.)
카탈로그에서 강의 코드를 가져오고, 입력받은 학기와 강의코드를 통하여 그 학기의 이수구분에 맞는 강의들을 전체 반환합니다.
이상한 점 있으면 말씀해주세요 :D
> feat : 학기와 이수구분으로 강의 찾기

- src/main/java/in/koreatech/koin/global/socket/config/WebSocketConfig.java
1. 안드로이드 라이브러리에서 연결 오류가 나는 원인으로 추정되는 설정 (SockJS) 수정
> fix : 웹 소켓 설정에서 sockjs 통신 설정 삭제

- src/main/java/in/koreatech/koin/global/config/S3Config.java
IAM user "s3"와 IAM role "EC2_to_S3"를 동시에 사용중이었습니다.
- IAM user "s3" -> accessKey, secretKey로 접근
- IAM role "EC2_to_S3" -> InstanceProfileCredentialsProvider로 접근(인스턴스에 부여된 역할에 기반한 임시 자격증명 발급)
presignedUrl은 IAM role 방식을 사용하기 때문에 권한 문제가 발생하지 않았으나, 이번에 추가된 #1175 와 기존(레거시) 이미지 업로드 방식은 IAM user 방식을 사용하여 권한없음 에러가 발생했습니다. 
자격 증명을 단일 방식으로 통일하기 위해 `s3Client` 빈 생성 시 `EC2ContainerCredentialsProviderWrapper`를 사용하도록 변경했습니다.
> feat: s3 접근에 필요한 자격 증명 방식 단일화

- src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
- src/main/java/in/koreatech/koin/global/s3/S3Utils.java
서버에서 에러가 발생했습니다. uri: GET /coop/dining/image
Exception: AmazonS3Exception
Location: AmazonHttpClient.java Line 1879
```
The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: ~~; S3 Extended Request ID: ~~; Proxy: null)
```
1. 외부 이미지가 DB에 포함된 경우 다운로드를 시도하지 않도록 예외처리했습니다.
2. s3 이미지 다운로드 로직을 `s3Utils` 클래스로 분리했습니다.
> fix: 영양사 이미지 압축 다운로드 예외처리

- src/main/java/in/koreatech/koin/global/config/S3Config.java
Reverts BCSDLab/KOIN_API_V2#1223
재발급된 aws key 정상 동작 확인을 위한 revert PR입니다.
> Revert "feat: s3 접근에 필요한 자격 증명 방식 단일화"

- src/main/java/in/koreatech/koin/global/config/S3Config.java
Reverts BCSDLab/KOIN_API_V2#1227
- 테스트 완료로 인한 롤백 (자격증명 수단: user key-> ec2 role)
- 불필요해진 accessKey, secretKey 필드 제거 
https://kim-jong-hyun.tistory.com/131
> feat: aws 자격 증명 방식 단일화 및 key 제거

- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/controller/ChatRestApi.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/controller/ChatRestController.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/exception/UserBlockException.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/model/LostItemChatUserBlockEntity.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/repository/LostItemChatUserBlockRepository.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/LostItemChatRoomInfoService.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/LostItemChatRoomUserBlockService.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/ChatRoomInfoReader.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/UserBlockAppender.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/UserBlockReader.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/UserBlockUpdater.java
- #1185
**REST 엔드포인트**
- **POST** /chatroom/lost-item/{articleId}/{chatRoomId}/block : 사용자 차단
- **DELETE** /chatroom/lost-item/{articleId}/{chatRoomId}/unblock : 사용자 차단 해제
- 채팅방 정보를 MongoDB에서 관리하기 때문에 통일성을 고려하여 MongoDB를 사용했습니다.
```mermaid
erDiagram
LOST_ITEM_CHAT_USER_BLOCK {
ObjectId id PK "MongoDB ObjectId"
Integer blocker_user_id "차단을 수행한 사용자 ID"
Integer blocked_user_id "차단된 사용자 ID"
Boolean is_active "차단 상태 (활성/비활성)"
LocalDateTime created_at "차단 생성 일시"
}
```
- 차단을 해제하는 기능이 없기 때문에 is_active는 현재 유의미하게 사용되지 않습니다.
- 클라이언트 개발 편의를 위해 차단 해제 API를 제공하였습니다.
- 게시글 신고 기능이 스테이지에 적용되면 신고 완료 처리된 게시글에 대한 채팅방 접근이 불가능하도록 하는 기능을 별도의 PR로 개발하겠습니다.
> feat : 분실물 게시글 쪽지(채팅) 사용자 차단 기능

- src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/SemesterCheckResponseV3.java
- src/main/java/in/koreatech/koin/domain/timetableV3/service/SemesterServiceV3.java
- close #1140
1. 클라이언트의 요청에 따라 GET v3/semesters/check의 Response 내의 user_id를 삭제했습니다.
간단한.. 피알..
> Chore : GET /semesters/check Response 내 user_id 삭제(졸학계)

- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
- src/main/java/in/koreatech/koin/domain/community/article/dto/ArticlesResponse.java
- src/main/java/in/koreatech/koin/domain/community/article/dto/LostItemArticlesResponse.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
1. 신고 기능은 분실물 게시글에만 존재
2. 모바일에서는 get /articles/lost-item 이용하여 분실물 게시글 조회
3. 웹사이트에서는 get /articles 이용하여 분실물 게시글 조회 (게시판 구분이 없음)
4. get /articles/lost-item 만 is_reported 필드 존재
5. 웹사이트에서 신고된 분실물을 판별하기 어려움
1. 게시글 목록 조회 응답(get /articles, get /articles/search)에 is_reported 필드 추가
2. is_reported: 게시글 중 자신의 미처리된 신고 존재 여부 반환, 게시글 블러처리 여부에 사용
> chore: 게시글 목록 조회 응답에 is_reported 필드 추가

- src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationApi.java
- src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationController.java
- src/main/java/in/koreatech/koin/domain/graduation/exception/GeneralEducationAreaNotFoundException.java
- src/main/java/in/koreatech/koin/domain/graduation/model/CatalogResult.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/GeneralEducationAreaRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- close #1140 
1. general_education_area 관련 로직 추가했습니다.
1-1 기존 GET /graduation/course-type 로직 내 추가
required를 빼놔서, 교양선택인 경우만 선택해서 드랍다운 형식으로 확인할 수 있도록 하면 괜찮을 것 같습니다.
1-2 기존 엑셀 코드 POST /graduation/excel/upload 내 추가
우리 Timetable_lecture가 드디어 교양영역을 보여줍니다.
ㅠㅠ.. 최대한 빨리 한다고 했는데.. 영~.. 느렸네요.
확인 부탁드려용.
> feat : 졸학계 엑셀 / 강의조회 로직 내 GeneralEducationArea 추가(졸학계)

- src/main/java/in/koreatech/koin/admin/owner/service/AdminOwnerService.java
- src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
- src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerRegisteredInfoResponse.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminOwnerApiTest.java
- close #1244
1. 기존에 사장님 승인이 진행될 때 redis에 저장해두었던 가게정보를 삭제하지 않도록 수정
2. 회원가입 시 redis에 임시 저장한 가게정보(가게명, 가게전화번호)를 조회하는 API 추가
3. 관련 테스트코드 수정
> feat: 사장님 회원가입 시 redis에 임시 저장한 가게정보 조회 API

- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/model/LostItemChatRoomInfoEntity.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/LostItemChatRoomInfoService.java
- src/main/java/in/koreatech/koin/global/socket/domain/chatroom/service/implement/ChatRoomInfoAppender.java
- #1185
1. 채팅방 목록 데이터 반환에서 대화가 없는 채팅방도 출력하도록 수정했습니다.
2. 채팅방 목록 데이터 반환시 가장 최근 전달된 메시지 or 채팅방 기준으로 정렬하도록 수정했습니다.
3. mongodb에 채팅방 정보 저장시 `created_at` 필드를 추가했습니다. 향후 스테이지 적용 시 스테이지 mongodb에 직접 접속하여 이미 존재하는 데이터에 대해 shell로 직접  `created_at` 필드를 임의로 추가하는 작업을 진행할 예정입니다.
> fix: 대화가 없는 채팅방 정보도 출력

- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
일반 게시글 검색 응답과 분실물 게시글 검색 응답이 달라야한다.
1. `분실물 게시글 검색 api` 추가했습니다.
> feat: 분실물 게시글 검색 api 추가

- src/main/java/in/koreatech/koin/domain/student/model/Major.java
- src/main/java/in/koreatech/koin/domain/student/model/Student.java
- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
- src/test/java/in/koreatech/koin/acceptance/AbtestApiTest.java
- src/test/java/in/koreatech/koin/acceptance/ArticleApiTest.java
- src/test/java/in/koreatech/koin/acceptance/BenefitApiTest.java
- src/test/java/in/koreatech/koin/acceptance/KeywordApiTest.java
- src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
- src/test/java/in/koreatech/koin/acceptance/SemesterApiTest.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
- src/test/java/in/koreatech/koin/acceptance/StudentApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiV3Test.java
- src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TimetableLectureV3ApiTest.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminShopReviewApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminStudentApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminTrackApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
- src/test/java/in/koreatech/koin/fixture/MajorFixture.java
- src/test/java/in/koreatech/koin/fixture/UserFixture.java
- close #1258 
- 현재 발생하고 있는 회원 탈퇴 오류를 수정했습니다.
- Student와 major, department의 영속성 전의 설정을 삭제했습니다.
- 회원 정보 수정이 안되는 문제를 임시로 수정했습니다.
- 졸학계 전용 수정 API를 추가하면서 수정할 계획입니다. 
- [논의 스레드](https://bcsdlab.slack.com/archives/C06NEM6EY3W/p1739864891360629)
- 테스트 코드 중, 학생 관련 부분에 department를 추가했습니다.
- Major은 null로 처리했습니다.
> fix:  학생 정보 수정 오류 수정

- src/main/java/in/koreatech/koin/admin/owner/dto/AdminOwnerUpdateResponse.java
- close #1271
1. AdminOwnerUpdateResponse의 gender null체크 로직 추가
- 날먹
> fix: 특정 사장님 수정 gender null체크 추가

- src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableCustomLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableCustomLectureUpdateRequest.java
- close #1235 
- timetable Api dto 중 강의 정보&시간을 리스트로 가지고 있는 필드에 NotEmpty 어노테이션을 작성했습니다.
> feat: timetable API dto 유효성 검증 어노테이션 추가

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/resources/db/migration/V134__alter_lost_item_author_cascade.sql
- close #이슈번호
1. 분실물 게시글의 author가 null일 경우 '탈퇴한 사용자'로 수정 및 분기 처리 하였습니다.
- author가 null로 작성된 게시글은 **로그인 사용자가 글 작성 후 회원 탈퇴한 경우**에만 가능한 상황이라서 '익명'에서 '탈퇴한 사용자'로 수정했습니다.
2. lostItemArticle과 User의 외래키 제약조건을 수정하였습니다.
> fix: 분실물 게시글 오류 수정

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- close #이슈번호
- `foundPlace` 빈 문자열이거나 공백만 포함된 경우 `장소 미상`으로 자동 설정되도록 변경
- 분실 장소 정보가 없는 경우에도 의미 있는 기본값을 제공하여 데이터 일관성 유지
> chore: 분실물 게시글의 foundPlace 빈 값일 경우 "장소 미상"으로 저장하도록 수정

- src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationApi.java
- src/main/java/in/koreatech/koin/domain/graduation/controller/GraduationController.java
- src/main/java/in/koreatech/koin/domain/graduation/dto/EducationLectureResponse.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- close #1210
1. 학생이 이수한 교양 강의에 대한 정보를 반환시켜주는 API입니다.
로직은 아래와 같습니다.
1. 학생이 들은 강의 목록(timetable_lecture)에서 geeral_education_area 필드가 null이 아닌 것들을 중복 제외
2. catalog 테이블에서 학생의 학번에 맞는 연도의 강의에서 geeral_education_area 필드가 중복 제외
위의 결과들을 조합해서 학생이 들어야할 교양과목중에서 어떤것을 들었는지 파악했습니다.
> feat: 현재 이수한 교양 강의 API

- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- close #1277
1. studentCourseCalculation과 detectGraduationCalculation에 userId중복을 방지하기위해 필터링 로직을 추가했습니다.
> fix: 졸업학점 계산 agree api 유저 중복 해결

- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- src/main/java/in/koreatech/koin/domain/student/dto/StudentUpdateResponse.java
- src/main/java/in/koreatech/koin/domain/student/model/StudentDepartment.java
- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
- close #1285
- 학번, 전공을 넣지 않았을 때 발생하는 NPE를 수정했습니다.
- 졸학계 로직에서 학번을 필요로 하는데, 학번이 null인 상태에서 로직을 호출했을 때 NPE가 발생하는 부분을 수정했습니다.
- 전공과 학번의 경우 변경 여부를 확인할 때 NPE가 발생하는 부분을 Objects.equals 메소드로 변경했습니다.
> fix: 학생 정보 수정 NPE 해결

- src/main/java/in/koreatech/koin/domain/graduation/aop/GraduationAspect.java
- close #1288
시간표 생성하거나 삭제해도 DB에 detectGraduationCalculation의 is_changed=1로 DB에 변경되지 않는 사항이 있어, DB에 반영될 수 있게 수정했습니다.
> fix: 졸학계 aop 수정

- src/main/java/in/koreatech/koin/domain/graduation/repository/CatalogRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/repository/StandardGraduationRequirementsRepository.java
- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- close #1287
1. 자신이 들은 학점 빈칸으로 보여주던 문제를 해결했습니다.
2. 불필요한 재계산 방지 했습니다. (DetectGraduationCalculation 활용)
* 학생의 학번/전공 변경 여부(isChanged 필드)를 감지해 변경된 경우에만 학점 재계산 수행 → 성능 최적화.
``` java
if (!detectGraduationCalculation.isChanged()) {
return getExistingGraduationCalculation(userId);
}
```
3. 중복 데이터 저장을 방지 했습니다.
* 기존 StudentCourseCalculation 데이터가 존재하면 삭제 후 새롭게 초기화하여 데이터 중복을 방지.
``` java
studentCourseCalculationRepository.deleteAllByUserId(student.getUser().getId());
```
4. 기존 데이터 즉시 반환
* getGraduationCourseCalculationResponse에서 변경 사항이 없으면 기존 데이터를 바로 반환해 불필요한 삭제 및 재계산 최소화.
* 기존 StudentCourseCalculation 데이터가 존재하면 삭제 후 새롭게 초기화하여 데이터 중복을 방지.
``` java
return GraduationCourseCalculationResponse.of(courseTypes);
```
5. 학점 매핑 연산 최적화 했습니다.
* Map<Integer, Integer>을 활용해 courseTypeId별 학점을 한 번의 매핑 과정에서 처리 → 연산 …
> fix: 자신이 들은 학점 빈칸으로 보여주던 문제 해결

- src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/LectureInfoResponse.java
- src/main/java/in/koreatech/koin/domain/timetableV3/utils/ClassTimeUtils.java
- close #1295 
- 졸학계로 생긴 timetableLecture 중 강의 시간이 null인 강의에서 생긴 NPE를 해결했습니다.
- 강의 시간과 강의 장소가 null인 경우 빈 리스트를 반환하도록 수정했습니다.
> fix: timetable NPE 해결

- src/main/java/in/koreatech/koin/global/domain/email/model/SesMailSender.java
- close #1293 
- 이메일 재전송 로직을 추가했습니다.
[참고 자료](https://docs.aws.amazon.com/ko_kr/sdk-for-java/v1/developer-guide/basics-async.html) : 이메일에 대한 예제코드는 존재하지 않았습니다..
코인에서 사용 중인 이메일 전송은 AmazonSimpleEmailServiceAsync의 sendEmailAsync 메소드를 통해 전송되고 있습니다.
AmazonSimpleEmailServiceAsync은 AWS SES의 비동기 클라이언트 인터페이스로, 비동기로 메일을 전송한다고 생각하면 편할 것 같습니다.
sendEmailAsync 메소드는 파라미터로 다음과 같은 값을 가집니다.
- SendEmailRequest : 보낼 메일에 대한 정보를 가진 객체입니다.
- AsyncHandler<SendEmailRequest, SendEmailResult> : 비동기 요청의 성공 및 실패 처리를 위한 콜백 메커니즘을 제공해주는 인터페이스라고 합니다. 
기존에는 두 번째 파라미터를 설정하지 않고, 보낼 메일에 대한 정보만을 설정했습니다. aws ses으로 메일 전송을 요청한 이후 성공 혹은 실패에 대한 정보를 얻을 수 없는 문제점이 있습니다. 현재 회원가입 과정에서 이메일 전송이 안되는 상황도 aws ses으로 요청을 했지만 내부에서 오류가 발생하고, 오류값을 핸들링하고 있지 않습니다.
AsyncHandler 인터페이스는 두 개의 메소드를 제공합니다.
- onError : 비동기 작업 중에 오류가 발생했을 때 호출됩니다.
- …
> feat: 이메일 재전송 로직 추가

- src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
- src/main/java/in/koreatech/koin/domain/student/controller/StudentController.java
- src/main/java/in/koreatech/koin/domain/student/dto/StudentWithAcademicResponse.java
- src/main/java/in/koreatech/koin/domain/student/repository/MajorRepository.java
- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
- close #1302 
1. 학생 학적 정보 수정(`/user/student/academic-info`) 문제 해결 했습니다.
- 학번 / 학부 / 전공 수정시 생기는 오류들을 해결했습니다.
- department 수정시 major도 바뀌기 때문에, major를 입력하지 않고 department를 수정하는 경우에는 가장 위에 있는 major를 선택하도록 했습니다.
2. 학생 정보 조회(학적 포함) API 작성했습니다. (GET `/user/student/me/academic-info`)
- 기본 Response 수정 시 클라이언트 오류 발생 위험이 있어, 학적 정보를 포함한 API를 추가로 작성했습니다.
생각보다 오래 걸렸네요.. 문제 있으면 말해주세여
> fix : 학생 학적 정보 수정 오류 해결 & feat : 학생 정보 조회(학적 포함)

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEvent.java
- src/main/java/in/koreatech/koin/domain/community/keyword/model/ArticleKeywordEventListener.java
- src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
- src/main/java/in/koreatech/koin/domain/community/util/KeywordExtractor.java
- close #이슈번호
1. user의 nickname이 없을 경우 '익명'으로 표시되도록 수정했습니다.
2. 내 게시글의 경우 키워드 알림이 오지 않도록 수정했습니다.
> fix : 분실물 게시판 2차 QA 이슈 해결

- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableLectureApiV3.java
- src/main/java/in/koreatech/koin/domain/timetableV3/controller/TimetableLectureControllerV3.java
- src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/TakeAllTimetableLectureResponse.java
- src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/TimetableLectureResponseV3.java
- src/main/java/in/koreatech/koin/domain/timetableV3/repository/TimetableFrameRepositoryV3.java
- src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableLectureServiceV3.java
- close #1308 
1. 학생이 이수한 모든 수업 조회 API 추가했습니다. (**GET** `/v3/timetables/main/lectures`)
- `timetableFrame` - `isMain(true)`인 학생의 모든 수업을 조회합니다.
2. 엑셀로 추가한 수업 출력 오류 문제 해결했습니다.
- 기존엔 `Lecture`에서 코드가 같은 수업 중, 마지막으로 반환받는 강의만을 가져왔습니다. -> 이 과정에서 분반과 시간이 안 맞는 문제가 생겼습니다. (01분반을 수강했으나, 04분반을 수강했다고 함)
- `Lecture`를 가져오는 과정에서, 모든 `Lecture`를 가져오고 추후 분반으로 이를 가져와 학생의 수업에 맞는 수업을 가져오게 하였습니다. 분반을 찾지 못한 경우에는 첫 번째 `Lecture`를 가져옵니다.
3. 교양선택 - 교양선택 매핑 문제 해결했습니다.
- 현재 가지고 있는 교양선택에는 다양한 선택지가 있습니다.(`general_education_area`)
- 이 과정에서 `general_education_area`를 가진 수업들은, `course_type`이 "교양선택"으로 매핑되며 교양선택 - 자연과 인간처럼 선택할 수 있습니다.
- 그냥 교양선택인 수업들은 `general_education_area`가 `null`이므로, 이를 처리하기 위해 "교양선택" - "교양선택" 입력시 `general_education_area_id`가 `null`인 수업들을 출력하도록 했습니다.
- 그대로 교양선택만 입력하면, `course_type`이 "교양선택"인 수업들이 모두 출력됩니다. …
> feat : 학생이 이수한 모든 수업 조회 / 엑셀로 추가한 수업 출력 오류 / 교양선택 매핑해결

- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- src/main/java/in/koreatech/koin/global/exception/package-info.java
- close #1310 
Java의 Integer 타입은 32비트 정수를 나타내며, 표현 가능한 범위는 -2,147,483,648 ~ 2,147,483,647
입력된 값 1232132132131231231은 이 범위를 초과하여 역직렬화(Deserialization) 중 오류가 발생
JSON 데이터에서 Integer 타입으로 매핑 시, 숫자가 너무 커서 overflow가 발생하여 역직렬화에 실패
~1. `Integer` 대신 `Long, BigInteger, String` 사용을 고민했으나, 이보다 큰 숫자가 들어올 가능성 + 매번 정수값 처리 방식 필요.~
~2. `@Max` 과 같은 어노테이션은 JSON 역직렬화 시점에는 적용되지 않음.~
**3. GlobalExceptionHandler에 handleHttpMessageNotReadable 메서드 오버라이딩을 통해 적절하게 에러를 핸들링하도록 구현.**
`Not annotated parameter overrides @NonNullApi parameter` 다수의 경고메세지 발생
부모 클래스에서 @NonNullApi로 인해 non-null로 간주되는 파라미터를 오버라이드할 때, 자식 메서드에 명시적 null 어노테이션이 없어 발생하는 경고
`package-info.java`는 해당 패키지의 문서화와 패키지 수준의 어노테이션을 선언하는 특수한 파일
`@NonNullApi`와 `@NonNullFields`를 붙이면, 해당 패키지 내의 모든 클래스에서 기본적으로 파라미터와 리턴값이 `non-null`로 간주됨
코드 일관성과 null 안전성이 향상되어 불필요한 …
> fix: handleHttpMessageNotReadable 메서드 오버라이딩을 통해 int overflow 에러 핸들링

- src/main/java/in/koreatech/koin/domain/community/article/model/LostItemArticle.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- close #이슈번호
1. 분실물 게시글 조회 시 is_deleted=1(삭제된 게시글)도 함께 조회되는 버그를 수정했습니다.
- type이 있는 경우 네이티브 쿼리를 통해 조회하는데, 이 때 @Where(is_deleted=0) 어노테이션이 동작하지 않아 발생했습니다.
> fix: 분실물 게시글 조회 시 is_deleted 미적용 버그 수정

- src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
- src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureUpdateRequest.java
- close #1330 
1. 정규 강의 수정시, lecture_id가 null인 경우 NPE가 발생하는 문제를 해결했습니다.
- lecture_id가 null이면 lecture.getName()을 가져오지 못하므로, 기존 classTitle을 사용하도록 했습니다.
잘 부탁드립니당
> fix : 정규 강의 수정 lecture NPE 문제 해결

- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- close #1333
현재 agree api를 사용하지 않은상태에서 학생 정보를 수정했을때, 계산테이블의 정보만 초기화되고 detect테이블의 정보는 초기화가 되지 않아 추후 agree api를 사용할때 문제가 발생합니다.
그래서 학생 정보를 수정할때 데이터가 이미 존재하는지 확인 후 계산테이블의 정보 초기화시킬수 있도록 수정했습니다.
> fix: 졸학계 계산 테이블 초기화 오류 수정

- src/main/resources/db/migration/V136__alter_graduation_calculation_unique_cascade.sql
- src/main/resources/db/migration/V136__alter_user_and_standard_graduation_requirements_unique_cascade.sql
- close #1335
동시 요청으로 인해 가끔 student_course_calculation과 detect_graduation_calculation에 중복으로 데이터가 들어오는 경우가 존재하기때문에, 중복 데이터를 방지하기 위해 유니크 제약조건을 걸었습니다.
> fix: 졸학계 계산 테이블 유니크 제약조건 추가

- src/main/java/in/koreatech/koin/domain/graduation/aop/GraduationAspect.java
- close #1341 
- 변경 감지 aop의 포인트 컷을 추가했습니다.
- timetableFrame을 모두 삭제하는 api, timetableLecture를 삭제하는 방식이 다른 api를 추가했습니다.
- 엑셀 업로드 직후, 바로 계산되도록 추가했습니다.
> feat: 졸업학점 계산기 변경 감지 aop 포인트 컷 추가

- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- close #1345 
1. 학적 정보를 수정할 경우, 학생이 가지게 되는 기준 학점 테이블 내의 값이 중복 삽입되는 오류를 해결했습니다.
- 오류 값으로 처리해 본 결과, 로컬 내에서는 문제가 발생하지 않았습니다. 스테이지에서는 이러한 오류가 계속 발생하는 것으로 보아, 서버 -> DB 반영하는 과정에서 DELETE가 진행되지 않은 상황에 값이 삽입 됐다고 생각했습니다.
- 그 문제를 해결하기 위해 flush와 clear를 이용하여 즉시 DELETE 쿼리 실행 및 이전 데이터를 참조하지 않도록 했습니다.
서버가 너무 아파요
> fix : 학적 정보 중복 삽입 문제 해결

- src/main/java/in/koreatech/koin/domain/student/model/redis/StudentTemporaryStatus.java
- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
- src/test/java/in/koreatech/koin/acceptance/StudentApiTest.java
- close #1350 
- 회원 가입 시, major를 지정해주는 로직을 추가 했습니다.
- 인증 api에서 department가 존재할 경우, department와 연관된 major 중 첫 번째를 지정해줍니다.
- 관련 테스트 코드 수정했습니다.
> feat: 회원가입 인증 시 major 지정

- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- close #1357 
1. 성적에 F가 있는 경우, 졸업학점 계산기 내에서 TimetableLecture에 들어가지 않도록 했습니다.
- U에 대해서는 처리가 되어있었는데, F에 대해서는 처리가 안 되어있기에 처리했습니다.
성적표 흔쾌히 주신 원빈님(PL) 감사합니다
> fix : (졸학계) F학점 수업 처리 추가

- src/main/java/in/koreatech/koin/_common/exception/ErrorResponse.java
- close #1369 
1. 에러 코드 int -> String로 복구
> hotfix: error code string으로 변경

- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
- close #1374 
1. ArticleApi의 deleteLostItemArticle 메소드 auth의 STUDENT누락을 추가했습니다.
- 7글자
> fix: ArticleApi deleteLostItemArticle auth의 STUDENT 누락 추가

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- close #1378 
- 탈퇴한 사용자의 분실물 게시글의 author에서 발생하는 NPE를 해결했습니다.
- 탈퇴한 사용자의 분실물 게시글의 반환값으로 "탈퇴한 사용자"를 반환하도록 로직을 수정했습니다.
> fix: 단일 분실물 게시글 조회 NPE 수정

- src/main/java/in/koreatech/koin/socket/domain/chatroom/service/LostItemChatRoomInfoService.java
- close #1390 
- 채팅방을 모두 조회할 때, 탈퇴한 사용자의 채팅방은 출력하지 않도록 로직을 추가했습니다.
- 탈퇴한 사용자의 분실물 게시글에서 쪽지 보내기를 눌렀을 때, 예외 처리를 했습니다.
> fix: 탈퇴한 사용자의 분실물 채팅에서 발생하는 버그 수정

- src/main/java/in/koreatech/koin/domain/shop/controller/ShopReviewApi.java
- src/main/java/in/koreatech/koin/domain/shop/exception/OneReviewPerDayException.java
- src/main/java/in/koreatech/koin/domain/shop/repository/review/ShopReviewRepository.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
- src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
- #1398 
- 사용자가 동일한 상점에 하루 내 최대 한 번만 리뷰를 남길 수 있도록 검증 로직을 구현했습니다.
- 검증 실패 시 400 Bad Request 예외를 반환합니다.
- 기능 검증을 위한 테스트 코드를 추가했습니다.
- [테스트 관련 이슈](https://www.notion.so/1c09ae650b5980b8b21cdaad20a0d078)
> feat: 상점 리뷰 하루 한번으로 제한하기

- src/main/java/in/koreatech/koin/admin/banner/repository/AdminBannerRepository.java
- src/main/java/in/koreatech/koin/admin/banner/service/AdminBannerService.java
- src/main/java/in/koreatech/koin/domain/banner/model/Banner.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminBannerApiTest.java
- close #1395 
- 배너 삭제 시 우선순위 조정 로직을 구현했습니다.
- 삭제하는 배너가 활성화 상태이면서 우선순위가 있는 경우, 해당 배너와 같은 배너 카테고리에 있으면서 우선순위가 낮은 배너들의 우선순위를 수정합니다.
- 관련해서 테스트 코드 작성했습니다.
이전 PR에서 구현에 필요한 부분 긁어왔습니다. 이 부분 빼고 보시면 될 것 같습니다.
> feat: 어드민 배너 삭제 시 우선순위 조정 로직 구현

- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
- src/main/java/in/koreatech/koin/domain/community/article/controller/LostItemReportApi.java
- src/main/java/in/koreatech/koin/domain/community/article/controller/LostItemReportController.java
- src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
- src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
- src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
- src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/model/UserType.java
- src/main/java/in/koreatech/koin/integration/fcm/notification/controller/NotificationApi.java
- src/main/java/in/koreatech/koin/integration/fcm/notification/controller/NotificationController.java
- src/main/java/in/koreatech/koin/integration/s3/controller/UploadApi.java
- src/main/java/in/koreatech/koin/integration/s3/controller/UploadController.java
- src/main/java/in/koreatech/koin/socket/domain/chatroom/controller/ChatRestApi.java
- src/main/java/in/koreatech/koin/socket/domain/chatroom/controller/ChatRestController.java
- close #1404 
1. 일반인 UserType : `GENERAL` 을 추가했습니다.
2. 일반인은 `공지사항 알림, 학식 좋아요, 리뷰, 푸시알림, 주문 전화 리뷰 푸시알림, 파일업로드, 분실물, 분실물 쪽지` 권한을 가집니다.
3. 학생은 `졸업학점계산기, 학생 정보, 리뷰, 시간표, 학기정보` 권한을 추가로 갖고 있습니다.
> feat: 일반인 유저타입 추가

- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- close #1380 
- 현재 /articles/hot api는 첫 화면에 표시되므로 한달기준으로 요청 수 6번 째에 해당할 정도로 많이 사용되는 api
- 하지만 기능 내용에 비해 latency가 높은 것으로 보임
- 여러 요청들을 확인해보니 41개의 쿼리가 나가고있음
- 기존 로직
```java
List<Article> cacheList = hotArticleRepository.getHotArticles(HOT_ARTICLE_LIMIT).stream()
.map(articleRepository::getById)
.collect(Collectors.toList());
```
list를 stream으로 돌며 getById를 호출하고있음
-> n+1문제 발생
- 이를 배치 쿼리를 통해 한번에 불러와서 n+1 문제를 해결하였음
- Map을 이용하여 id와 Article들을 재매핑하여 기존의 정렬 효과도 유지
하지만 이를 통해 해결해도 여전히 많은 쿼리가 발생함을 확인
-> 확인해보니 Article 엔티티에 LAZY로딩인 여러 엔티티들이 엮여있음
- 이들이 지연로딩되면서 많은 쿼리가 n+1으로 반복되는 것으로 확인
- LAZY로딩으로 연결된 엔티티들을 페치조인을 사용하여 한번에 가져옴
- 이를 통해 findAllByIdIn에서 발생하는 LAZY로딩 문제를 해결함
- ToOne 관계만 페치조인하므로 컬럼 개수가 기하급수적으로 증가하는 문제는 발생하지 않음
- findMostHitArticles 메소드에도 동일한 LAZY로딩 문제 발생
- 기존의 네이티브 쿼리에서 JPQL로 변경하고 LIMIT를 사용하지 못하는 …
> refactor: 인기게시글 목록 조회 n+1, 지연로딩 문제해결

- src/main/java/in/koreatech/koin/admin/history/aop/AdminActivityHistoryAspect.java
- src/main/java/in/koreatech/koin/admin/history/enums/DomainType.java
- src/main/java/in/koreatech/koin/admin/history/enums/HttpMethodType.java
- close #1428 
- 어드민 히스토리에는 API 요청 메소드를 통해 추가, 수정, 삭제를 반환합니다.
- PATCH 요청이 없어서 에러가 발생했고, 이를 추가했습니다.
- 어드민 히스토리는 도메인 enum과 API 요청 PATH를 비교해서 히스토리의 도메인을 반환합니다.
- 배너와 배너 카테고리의 enum이 존재하지 않아 히스토리에 어드민 도메인으로 처리됐습니다.
- 이를 추가하고, AOP에서 처리하도록 로직을 추가했습니다.
히스토리 코드를 처음 보는 분이 계실텐데, 코드 자체가 쉽지 않습니다.
이후에 코드를 갈아 엎을 생각이라서, 수정된 부분만 확인해주시면 감사하겠습니다.
> feat: 어드민 히스토리 PATCH 요청 추가 및 도메인 추가

- .github/workflows/pr-reviewers-by-label.yml
- src/main/java/in/koreatech/koin/admin/benefit/service/AdminBenefitService.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/socket/domain/session/service/UserSessionService.java
- src/main/java/in/koreatech/koin/socket/interceptor/ConnectInterceptor.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- close #1434 
1. 리뷰어 자동 지정이 PR이 열렸을 때도 동작되도록 수정한다.
2. 잘못된 요청 매핑 수정
> fix: 리뷰어 자동 지정이 PR이 열렸을 때도 동작되도록 수정한다.

- src/main/java/in/koreatech/koin/domain/banner/dto/response/BannersResponse.java
- src/test/java/in/koreatech/koin/acceptance/BannerApiTest.java
- close #1436 
- 클라이언트 로깅을 위해 Normal Banner API 응답값에 배너 이름을 추가했습니다.
- 겸사겸사 Normal API에 requireMode를 설정했습니다.
> feat: Normal Banner API 배너 이름 응답값 추가

- src/main/java/in/koreatech/koin/domain/owner/service/OwnerSmsService.java
- src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/dto/UserLoginRequestV2.java
- src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
- close #1406 
1. 전화번호/Id 혼용 방식의 로그인 API를 추가하였습니다.
- 전화번호 양식은 하이픈(-)을 제외한 형태입니다. ex) 01011112222
- 에러코드
- 404 에러: 아이디(전화번호)가 존재하지 않을 경우
- 400 에러: 비밀번호가 일치하지 않을 경우
> feat: 통합 로그인 API 구현

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminNoticeApiTest.java
- close #1467
- 많은 데이터를 처리하는 작업이 아님에도 P95 LATENCY가 높은 것으로 보임
- 확인해보니 18개의 쿼리가 실행되고있음
- ToOne관계 페치조인, ToMany관계(attachment) 하나의 컬렉션이므로 같이 페치조인 진행
- 페이징 사용하지 않으므로 문제X
- getById 자체를 변경하였으므로 게시글 단건 조회와 관련된 다른 api들도 같이 개선될 것으로 보임
- 해당 로직은 이전과 이후 게시글을 직접 사용하는 것이 아닌, 게시글의 id만 response로 전달하기위한 용도로 보임
- 따라서 article을 페치조인하여 엔티티를 가져오는 것보다 그냥 DB에서 id만 가져오는 로직으로 수정
- 기존엔 getById가 findById를 호출하고 있었고, 같은 트랜잭션 내에서 수행되므로 soft delete를 수행해도 아직 flush(commit)되지 않아서 기존 테스트코드의 getById를 호출해도 1차캐시에 해당 ID가 있기때문에 isDeleted가 1으로 변경된 DB에 접근하지 않음. 따라서 Article 엔티티가 @Where(clause = "is_deleted=0")임에도 불구하고 해당 엔티티를 불러올 수 있었음.
- 하지만 JPQL로 getById로직을 변경하게 되면서, JPQL을 사용하였기 때문에 1차캐시를 거치지 않고 무조건적으로 DB에서 가져오게 됨. 따라서, is_deleted=1이 되어버린 deletedArticle은 조회되지 않아서 게시글을 찾을 수 없다는 예외가 발생하여 테스트 실패.
- is_deleted=1도 포함하여 조회하는 …
> refactor: 게시글 단건 조회 Lazy Loading, N+1 문제 해결 및 로직 수정

- src/main/java/in/koreatech/koin/domain/user/model/UserEventListener.java
- src/main/java/in/koreatech/koin/domain/user/model/UserVerificationStatus.java
- src/main/java/in/koreatech/koin/domain/user/service/UserVerificationService.java
- close #1465 
1. 인증 번호 요청 시 슬랙 알림 정상적으로 전송하도록 버그 수정했습니다.
2. 인증 완료 후 잘못된 코드 요청 시 400 반환하도록 버그 수정했습니다.
```mermaid
sequenceDiagram
participant Client
participant Server
participant RedisRepository as UserVerificationStatusRedisRepository
Client->>Server: verifyCode(phoneNumberOrEmail, verificationCode)
Server->>RedisRepository: getById(phoneNumberOrEmail)
RedisRepository-->>Server: verificationStatus
alt 상태가 없음 (404)
Server->>Client: 404 Not Found (상태가 존재하지 않습니다.)
else 상태 있음
Server->>Server: isCodeMismatched(verificationCode)
alt 인증 코드 일치하지 않음
Server->>Client: KoinIllegalArgumentException("인증 번호가 일치하지 않습니다.")
else 인증 코드 일치
Server->>Server: isVerified()
alt 이미 인증 완료
Server->>Client: 아무 작업도 하지 않음
else 인증 안됨
Server->>Server: markAsVerified()
Server->>RedisRepository: save(verificationStatus) …
```
> fix: 인증 완료 후 잘못된 코드 요청 시 400 반환

- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/dto/validation/CheckLoginIdDuplicationRequest.java
- src/main/java/in/koreatech/koin/domain/user/exception/DuplicationLoginIdException.java
- src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
- close #이슈번호
1. 회원가입 시 아이디 중복 확인 API를 추가하였습니다.
2. 아이디 중복 확인과 아이디 존재 여부 확인 메서드의 구분이 어려워 이름을 일부 수정했습니다.
> feat: 회원가입 시 아이디 중복 확인 api 추가

- src/main/java/in/koreatech/koin/domain/student/controller/StudentApi.java
- src/main/java/in/koreatech/koin/domain/student/controller/StudentController.java
- src/main/java/in/koreatech/koin/domain/student/dto/StudentRegisterRequestV2.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserVerificationApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserVerificationController.java
- src/main/java/in/koreatech/koin/domain/user/dto/FindIdResponse.java
- src/main/java/in/koreatech/koin/domain/user/dto/GeneralUserRegisterRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/ResetPasswordByEmailRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/ResetPasswordBySmsRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/validation/ExistsByUserIdRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/validation/MatchUserIdWithEmailRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/validation/MatchUserIdWithPhoneNumberRequest.java
- src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
- src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- close #이슈번호
1. 1차 스프린트에서 사용된 로그인 id의 필드명을 `userId` -> `loginId`로 수정하였습니다.
2. 1차 스프린트에서 작성한 회원가입 api의 uri를 `/v2/user/general` -> `/v2/user`로 수정하였습니다.
> refactor: loginId 필드명 및 회원가입 API URI 수정

- src/main/resources/db/migration/V147__add_versions_type_isprevious_index.sql
- close #1485 
- 프로덕션의 API 중 8번째로 자주 호출됨
- 로직은 단순히 type과 previous를 where 조건으로 사용해 조회하고있음
- 실제로 요청부터 응답까지의 시간이 병목이라고 할 만큼 오래걸리지는 않음
- 테이블의 행의 개수가 24개로 매우 적음 (프로덕션)
- 클러스터링 인덱스만 존재
- 자주 쓰는 다른 API 에서도 해당 쿼리 호출
- where 조건에 type과 previous를 사용하여 조회하지만 별도의 인덱스가 생성되어 있지 않음.
- type마다 previous가 0인 행은 단 하나임, 따라서 선택도가 매우 높음
- 하지만 행의 개수가 매우 적어서 full table scan이 index scan을 사용하는 것보다 빠를 수 있음.
- {type, previous}의 복합 인덱스를 생성하여 직접 비교확인해보기로 함
- 풀 테이블 스캔 발생, 테이블 스캔 시간 약 9.59ms
- 인덱스 사용, 약 0.006ms 소요
- 짧은 시간이므로 반복 수행하였음
- 풀 테이블 스캔 발생, 테이블 스캔 시간 평균 0.105ms
- 인덱스 사용, 평균 0.0069ms
- versions 테이블의 데이터의 cud가 자주 일어나지는 않으며, 따라서 cud 발생 시 인덱스 추가에 따른 비용은 크지 않을 것으로 보임.
- 인덱스의 크기가 크지않으므로 디스크 영향도 크지 않을 것임.
- 계속 데이터가 추가되어 누적되는 테이블이고, 이 인덱스의 효과는 행이 추가될 수록 기하급수적으로 커짐
> feat: versions 테이블에 복합인덱스(type, is_previous)추가

- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- close #1490 
1. is_deleted가 쿼리에 중복으로 적용되던 오류를 발견하여 제거했습니다.
> fix: 중복된 is_deleted 삭제

- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/dto/RegisterUserRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/UserRegisterRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/validation/CheckNicknameDuplicationRequest.java
- src/main/java/in/koreatech/koin/domain/user/model/User.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
- src/main/java/in/koreatech/koin/domain/user/service/UserVerificationService.java
- close #1487
1. 닉네임 중복 체크 API 유효성 검사를 추가했습니다. (정규식 추가)
2. 인증 상태를 확인하는 모든 메서드에서 실패 시 인증 캐시를 소모하는 오류를 해결했습니다.
- 인증 상태를 가장 마지막에 검사하는 방식으로 해결했습니다.
3. 인증 확인 메서드 이름 변경했습니다. (checkVerified -> consumeVerification)
- 기존 메서드 명(checkVerified)은 자칫 읽기 전용 메서드로 오해할 수 있어 수정했습니다.
- 인증 상태를 소모하는 사이드 이펙트가 잘 드러나도록 이름 변경했습니다.
4. 기타 적절하지 못한 변수 이름 수정했습니다.
5. 이메일 중복 검증 시 null 처리 하도록 수정했습니다.
> fix: 유저 회원가입 실패 시 인증 캐시를 소모하는 오류를 해결한다.

- src/main/java/in/koreatech/koin/integration/fcm/notification/model/NotificationSubscribeType.java
- src/test/java/in/koreatech/koin/acceptance/NotificationApiTest.java
- close #1492 
1. 마케팅 알림 구독 타입 추가
이미 기존에 기능이 있어서 간단하게 만들었는데, 리팩터링이 필요해보이네요
> feat: 마케팅 알림 구독 타입 추가

- src/main/java/in/koreatech/koin/domain/club/model/Club.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubAdmin.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubCategory.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubLike.java
- src/main/resources/db/migration/V150__add_club_category_table.sql
- src/main/resources/db/migration/V151__add_club_table.sql
- src/main/resources/db/migration/V152__add_club_admin.sql
- src/main/resources/db/migration/V153__add_club_like.sql
- close #1513 
- 코인 동아리 테이블을 추가했습니다.
- club, club_admin, club_like, club_category
- 이번 스프린트에서 사용하는 qna는 구현 중 변경이 생길 수도 있을 것 같아, 작업 담당자 분께서 구현해주시면 감사하겠습니다.
피그마와 백엔드 테이블 설계 문서를 보고 작성했습니다. 혹시나 빠트린 부분, 이상한 부분 코멘트 남겨주시면 감사하겠습니다.
동아리 연락처가 추가 됐는데, 이를 club 테이블에 역정규화로 넣어야 할지 별도의 테이블로 빼야할지 고민입니다.. 의견 주시면 감사하겠습니다..!
> feat: 코인 동아리 테이블 추가

- src/main/resources/db/migration/V154__add_club_qna_table.sql
- close #1515
- club_qna 테이블을 추가하였습니다
- 작성자가 탈퇴하면 SET NULL로 설정하여 user_id가 null이 되도록 했습니다.
- 방식은 parent_id 필드를 두어 최상위 댓글은 null로두고 그 외의 댓글들은 자식의 형태로 두고자합니다.
- 따라서 user_id와 parent_id는 nullable하게 설정하였습니다.
- parent_id는 자기참조 관계로 club_qna 테이블을 참조합니다.
> feat: club_qna 테이블 추가

- src/main/java/in/koreatech/koin/domain/test/TestApi.java
- src/main/java/in/koreatech/koin/domain/test/TestController.java
- close #1521 
- 클라이언트 요청으로 코인 공지 테스트를 위한 API를 추가했습니다.
- 테스트 패키지에 dev Profile 추가했습니다.
> feat: 코인 공지 테스트 API 추가

- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/CreateQnaRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/QnasResponse.java
- src/main/java/in/koreatech/koin/domain/club/exception/ClubNotFoundException.java
- src/main/java/in/koreatech/koin/domain/club/exception/ClubQnaNotFoundException.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubQna.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubAdminRepository.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubQnaRepository.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
- src/main/java/in/koreatech/koin/web/config/SwaggerGroupConfig.java
- src/main/resources/db/migration/V154__add_club_qna_table.sql
- src/test/java/in/koreatech/koin/unit/ClubTest.java
- close #1510
- parentId를 null로 요청하면 첫 QNA
- parentId에 부모 qna의 id를 넣어서 요청하면 대댓글 형식으로 생성됨
- 생성 시 관리자 인경우 qna에 is_admin을 true로해서 생성
- 추후 관리자가 변경되어도 유지할 수 있도록 하기 위함 
- 작성자 본인일 경우에만 x(삭제표시)를 보이게할 수 있도록 authorId를 함께 반환
- 닉네임은 있는경우 반환, 없는경우 student의 익명 닉네임을 반환
- 중간 댓글의 경우 삭제되어도 트리의 구조를 해치지 않도록 is_deleted를 통해 클라이언트가 '삭제된 댓글입니다' 표시할 수 있도록 함
- 관리자 댓글인 경우 구분할 수 있도록 isAdmin 필드 추가 
- 대댓글 형태로 재귀하여 반환하도록 하였음
```java
댓글 1
├── 댓글 1-1
│   ├── 댓글 1-1-1
│   │   └── 댓글 1-1-1-1
│   └── 댓글 1-1-2
├── 댓글 1-2
└── 댓글 1-3
댓글 2
└── 댓글 2-1
└── 댓글 2-1-1
```
- 관리자는 모든 QNA 삭제 가능, 그 외에는 본인의 QNA만 삭제 가능
- 부모 QNA (맨 처음 QNA)인 경우 삭제 시 hard delete, 자식까지 cascade
- 자식 QNA인 경우 is_deleted 처리하여 부모, 자식 트리 형태가 깨지지 않고 유지될 수 있도록 함
- 조회 반환 값에서 is_deleted = true로 반환하여 클라이언트 화면에서는 '삭제된 댓글입니다'로 표시
- 아직 테스트코드 작성 못했습니다 ㅠㅠ
> feat: 동아리 QNA API

- src/main/java/in/koreatech/koin/domain/student/dto/RegisterStudentRequestV2.java
- src/main/java/in/koreatech/koin/domain/student/dto/UpdateStudentRequestV2.java
- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
- src/main/java/in/koreatech/koin/domain/user/dto/RegisterUserRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/UpdateUserRequest.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- close #1534 
1. 아이디, 학번, 비밀번호, 이름의 정규식을 추가하였습니다.
2. 마케팅 수신 동의 주석 해제 및 임시 디바이스 토큰 값을 추가하였습니다.
> fix: 1차 QA 이슈 해결

- src/main/java/in/koreatech/koin/admin/club/dto/request/CreateAdminClubRequest.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubCategoryApi.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubCategoryController.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/CreateClubRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/UpdateClubIntroductionRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/UpdateClubRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubCategoriesResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubHotResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/GetClubByCategoryResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/QnasResponse.java
- src/main/java/in/koreatech/koin/domain/club/exception/ClubLikeNotFoundException.java
- src/main/java/in/koreatech/koin/domain/club/exception/DuplicateClubLikiException.java
- src/main/java/in/koreatech/koin/domain/club/model/Club.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubHot.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubQna.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubSNS.java
- src/main/java/in/koreatech/koin/domain/club/model/redis/ClubCreateRedis.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubCategoryRepository.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubLikeRepository.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubSNSRepository.java
- src/main/java/in/koreatech/koin/domain/club/repository/redis/ClubCreateRedisRepository.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubCategoryService.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubScheduleService.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
- close #1526 
오랜만에 코딩 하니까 힘드네요
동아리 생성 요청 부분은 
이런식으로 redis에 올라갑니다
PatchMapping으로 수정기능 구현하려다가 1시간이 날아갔습니다
포기하고 PutMapping으로 하니까 바로 되네요
여러분은 PutMapping 쓰세요..
> feat: 1526-normal 동아리

- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/QnasResponse.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubQna.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
- close #1545 
1. QNA 생성 시 질문은 사용자만, 답변은 관리자만 가능하도록 수정
2. QNA 삭제 시 자식인경우에도 hard deleted 되도록 수정 (기존엔 부모인경우만 hard delete 및 자식에 전파)
3. QNA 조회 시 isDeleted와 isAdmin을 반환하지 않음
4. 관련 swagger 명세 수정
- 다 머지되면 admin 표현을 manager로 다 변경하고 develop으로 머지해야할 것 같네요.
- flyway도 다 머지 끝나면 정리한번 해야할 거 같습니다
- 대표 동아리 API는 변경 사항이 없어서 그대로 사용합니다.
- 우선 isAdmin이나 isDeleted는 확장성을 위해 남겨놨습니다.
> feat: 동아리 QNA 기획 수정사항 반영

- src/main/java/in/koreatech/koin/_common/event/ClubCreateEvent.java
- src/main/java/in/koreatech/koin/admin/club/service/AdminClubService.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/CreateClubRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/EmpowermentClubManagerRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
- src/main/java/in/koreatech/koin/domain/club/exception/AlreadyManagerException.java
- src/main/java/in/koreatech/koin/domain/club/model/redis/ClubCreateRedis.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubAdminRepository.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/ClubEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/model/SlackNotificationFactory.java
- close #1527 
1. 동아리 관리자 권한 위임 API 추가
2. 동아리 생성 요청 시 슬랙에 알림 오도록 추가
> feat: 동아리 관리자 권한 위임 기능 추가

- src/main/java/in/koreatech/koin/infrastructure/s3/client/CloudFrontClientWrapper.java
- close #1553 
- CloudFront의 path에는 인코딩된 url이 필요
- UTF-8 인코딩을 진행하고 +로 인코딩된 공백을 %20으로 대체, %2F로 인코딩된 슬래시를 /으로 복원
- 3줄
> fix: CloudFront path변환 UTF-8인코딩 및 공백보정, 슬래시 보정 추가

- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubHotResponse.java
- src/main/java/in/koreatech/koin/domain/club/model/redis/ClubHotRedis.java
- close #1558
- ClubHotRedis에서 clubId를 추가로 관리하도록 했습니다.
- 인기 동아리 조회 시 해당 동아리로 바로 이동할 수 있도록 clubId를 추가로 반환하도록 했습니다.
> feat: ClubHotRedis에 clubId추가

- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
- src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubManagersResponse.java
- src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubsResponse.java
- src/main/java/in/koreatech/koin/admin/club/service/AdminClubService.java
- close #1561 
- 코인 동아리 관련 dto에 있는 동아리 활성화 변수명을 `isActive`으로 통일했습니다.
> fix: 코인 동아리 활성화 여부 변수명 통일

- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
- close #1568 
- 카테고리 별 동아리 조회 응답값에 좋아요 수를 추가했습니다.
- 응답값 필드명을 수정했습니다.
- 스웨거 설정을 변경했습니다.
> feat: 카테고리 별 동아리 조회 응답값 좋아요 수 필드 추가

- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- src/main/java/in/koreatech/koin/domain/timetableV3/dto/response/LectureInfoResponse.java
- timetable에서 발생하는 NPE를 수정했습니다.
- 졸업학점 계산기 엑셀 업로드 과정에서 정규강의가 아닌 강의는 임의로 생성되서 timetable_lecture에 저장
- 이 과정에서 온라인 강의 같은 수업의 classTime이 Null로 들어갔음
- 온라인 강의의 classTime은 `[]`으로 들어가야 하므로, 생성 로직 수정
- 응답값 반환과정에서도 빈 리스트 처리
> hotfix: Timetable NPE 수정 (main)

- src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubResponse.java
- src/main/java/in/koreatech/koin/admin/club/dto/response/AdminPendingClubResponse.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
- src/main/java/in/koreatech/koin/domain/club/enums/ClubSortType.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
- close #1572 
- 코인 어드민 동아리 API 변경사항을 적용했습니다.
- 변수명을 isActive로 통일시켰습니다.
- 동아리 신청자 이름을 응답값에 추가했습니다.
- 일반 동아리 API 변경사항을 적용했습니다.
- 검색 조건 요청값을 ENUM으로 관리하도록 수정했습니다.
일반 동아리 API 코드가 뭔가 쉽지 않은 느낌이 듭니다.. 
QuaryDSL을 써야할지 다른 방법이 있는지 여쭙고 싶습니다.
> fix: 코인 어드민 동아리 & 일반 동아리 API 변경사항 적용

- src/main/java/in/koreatech/koin/admin/club/controller/AdminClubApi.java
- src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubManagersResponse.java
- src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubResponse.java
- src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubsResponse.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubManager.java
- close #1576 
- 코인 어드민 동아리 API 수정사항을 반영했습니다.
- `GET /admin/clubs/{clubId}`의 contract 변수명을 contact으로 변경했습니다.
- `GET /admin/clubs/{clubId}`의 반환값에 동아리 위치를 추가했습니다.
- 응답값 중 동아리 관리자의 이름이 없는 경우, `미등록`으로 응답하도록 수정했습니다.
> fix: 코인 어드민 동아리 수정사항 반영

- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
- close #1581 
1. updatedAt을 반환DTO에 추가하였습니다.
> feat: 동아리 상세조회에 업데이트 일자 추가

- src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
- close #1591
- account_number 컬럼이 accountNumber로 되어있던 문제 해결
- 1줄
> fix: shop 엔티티 db와 column name 불일치 해결

- src/main/java/in/koreatech/koin/admin/shop/service/AdminShopMenuService.java
- src/main/java/in/koreatech/koin/infrastructure/s3/service/ImageDeleteService.java
- close #1563
- 도메인 서비스에서 이미지 수정, 삭제시에 imageDeleteService의 메소드를 호출하면 되도록 구성
→ 일반 삭제, 수정은 s3에서 삭제되어도 최대 24시간까지 url로 접근 가능
- 여러 이미지 수정 : publishImagesModifyEvent(엔티티에 저장된 이미지리스트, 새이미지url 리스트, 엔티티 이미지url getter)
- 여러 민감한 이미지 수정 : publishSensitiveImagesModifyEvent(위와동일)
```java
imageDeleteService.publishImagesModifyEvent(menu.getMenuImages(), request.imageUrls(), MenuImage::getImageUrl);
```
- 여러 이미지 삭제 : publishImagesDeletedEvent(엔티티에 저장된 이미지 리스트, 엔티티 이미지url getter)
- 여러 민감한 이미지 삭제 : publishSensitiveImagesDeletedEvent(위와동일)
```java
imageDeleteService.publishImagesDeletedEvent(menu.getMenuImages(), MenuImage::getImageUrl);
```
- 단일 이미지 수정 : publishImageDeletedEvent(이전이미지, 새이미지)
- 단일 민감한 이미지 수정 : publishSensitiveImageDeletedEvent(위와동일)
```java …
```
> feat: S3 이미지 삭제, 수정 시 반복되는 로직 imageDeleteService로 분리 후 모듈화 추가

- src/main/java/in/koreatech/koin/socket/domain/chatroom/service/LostItemChatRoomInfoService.java
- src/main/java/in/koreatech/koin/socket/domain/session/service/implement/UserReader.java
- close #1584
1. 채팅방 조회 시 사용자가 존재하지 않을 경우 404 응답하는 오류를 수정했습니다.
@DHkimgit  혹시 추가로 고려해야할 사항이 있다면 알려주세요.
> fix: 채팅방 조회 시 404 응답 오류 수정

- src/main/java/in/koreatech/koin/admin/abtest/useragent/UserAgentArgumentResolver.java
- close #1602 
- 플랫폼 별 리프레쉬 토큰 사전작업으로 UserAgentArgumentResolver에서 iOS를 판별할 수 있도록 작업을 했습니다.
> feat: UserAgentArgumentResolver iOS 판별 추가

- src/main/java/in/koreatech/koin/domain/club/dto/response/QnasResponse.java
- close #1605
- 탈퇴한 회원의 QNA 조회 시에 author_id를 null로 반환하고, nickname을 탈퇴한 회원으로 반환하도록 수정했습니다.
> fix: Club 탈퇴한 회원의 Qna 조회 시 NPE 해결

- src/main/java/in/koreatech/koin/admin/club/service/AdminClubService.java
- close #1608 
1. 어드민 동아리 생성요청 승인 시 누락되었던 SNS 저장 로직을 추가했습니다
> fix: 어드민 동아리 생성 승인 시 SNS 저장 로직 추가

- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubManagerDecideRequest.java
- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubUpdateRequest.java
- close #1619 
- 어드민 API를 통해 만든 동아리 활성화 기본값을 `true` 으로 변경했습니다.
- 동아리 이름, 위치, 직책, SNS에 이모지를 작성하지 못하도록 검증 어노테이션을 추가했습니다.
> fix: 코인 동아리 QA 2차 반영

- src/main/java/in/koreatech/koin/_common/exception/GlobalExceptionHandler.java
- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubManagerDecideRequest.java
- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubUpdateRequest.java
- close #1621 
- NotEmoji 어노테이션에서 뱉은 에러 메시지를 상황에 맞게 수정했습니다.
- handleMethodArgumentNotValid 에러 메시지를 개행으로 묶었습니다.
> fix: 코인 동아리 NotEmoji 에러 메시지 수정

- src/main/java/in/koreatech/koin/domain/notification/eventlistener/ArticleKeywordEventListener.java
- src/main/java/in/koreatech/koin/domain/notification/eventlistener/CoopEventListener.java
- src/main/java/in/koreatech/koin/domain/notification/eventlistener/NotificationEventListener.java
- src/main/java/in/koreatech/koin/domain/notification/eventlistener/ShopEventListener.java
- src/main/java/in/koreatech/koin/domain/notification/service/NotificationService.java
- src/main/java/in/koreatech/koin/domain/shop/cache/ShopsCacheRefreshListener.java
- src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
- src/main/java/in/koreatech/koin/infrastructure/email/eventlistener/EmailEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/naver/eventlistener/NaverSmsEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/s3/eventlistener/S3EventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/ClubEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/LostItemReportEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/OwnerEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/ReviewEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/StudentEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/UserEventListener.java
- src/main/java/in/koreatech/koin/socket/domain/notification/service/MessageReceivedEventListener.java
- close #1631 
1. TransactionalEventListener가 BEFORE_COMMIT 상태여서 transactional readonly 이 전파되는 오류해결
2. 테스트시 빈 생성 방지
> hotfix: TransactionalEventListener BEFORE_COMMIT readonly 오류 핫픽스 (main)

- src/main/java/in/koreatech/koin/domain/notification/eventlistener/ArticleKeywordEventListener.java
- src/main/java/in/koreatech/koin/domain/notification/eventlistener/CoopEventListener.java
- src/main/java/in/koreatech/koin/domain/notification/eventlistener/NotificationEventListener.java
- src/main/java/in/koreatech/koin/domain/notification/eventlistener/ShopEventListener.java
- src/main/java/in/koreatech/koin/domain/notification/service/NotificationService.java
- src/main/java/in/koreatech/koin/domain/shop/cache/ShopsCacheRefreshListener.java
- src/main/java/in/koreatech/koin/domain/shop/service/NotificationScheduleService.java
- src/main/java/in/koreatech/koin/infrastructure/email/eventlistener/EmailEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/naver/eventlistener/NaverSmsEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/s3/eventlistener/S3EventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/ClubEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/LostItemReportEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/OwnerEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/ReviewEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/StudentEventListener.java
- src/main/java/in/koreatech/koin/infrastructure/slack/eventlistener/UserEventListener.java
- src/main/java/in/koreatech/koin/socket/domain/notification/service/MessageReceivedEventListener.java
- close #1631 
1. TransactionalEventListener가 BEFORE_COMMIT 상태여서 transactional readonly 이 전파되는 오류해결
2. 테스트시 빈 생성 방지
> hotfix: TransactionalEventListener BEFORE_COMMIT readonly 오류 핫픽스 (develop)

- src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
- src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopController.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shopinfo/OrderableShopInfoDetailResponse.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shopinfo/OrderableShopInfoSummaryResponse.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopBaseInfo.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopDetailInfo.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopOpenStatus.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopsFilterCriteria.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopsResponse.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopsSortCriteria.java
- src/main/java/in/koreatech/koin/domain/order/shop/exception/OrderableShopNotFoundException.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/domain/OrderableShopInfoSummary.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/domain/ShopBaseDeliveryTipRange.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/domain/ShopBaseDeliveryTips.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/domain/ShopMenuOrigins.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/entity/OrderableShop.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/entity/ShopBaseDeliveryTip.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/entity/ShopOperation.java
- src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopListCustomRepository.java
- src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopListQueryRepository.java
- src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopRepository.java
- src/main/java/in/koreatech/koin/domain/order/shop/service/OrderableShopInformationService.java
- src/main/java/in/koreatech/koin/domain/order/shop/service/OrderableShopListService.java
- src/main/java/in/koreatech/koin/domain/shop/model/menu/MenuOrigin.java
- src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
- src/main/java/in/koreatech/koin/web/config/SwaggerGroupConfig.java
- src/main/resources/db/migration/V163__alter_shops_add_column_introduction_notice.sql
- src/main/resources/db/migration/V164__add_shop_menu_origin.sql
- #1644 
```mermaid
classDiagram
class shop_menu_origin {
+INT UNSIGNED id PK
+INT UNSIGNED shop_id 
+TEXT ingredient
+TEXT origin
+TINYINT(1) is_deleted
+TIMESTAMP created_at
+TIMESTAMP updated_at
}
%% Index
note for shop_menu_origin "Index: idx_shop_menu_origin_shop_id ON shop_id"
``` 
- 6.12 수정사항 : 1:N 관계로 변경, 재료:원산지 형태로 저장. shop_id 유니크 제약조건 제거
```json
{
"shop_id": 2,
"orderable_shop_id": 1,
"name": "가장 맛있는 족발",
"is_delivery_available": true,
"is_takeout_available": false,
"minimum_order_amount": 19000,
"rating_average": 4.3,
"review_count": 33,
"minimum_delivery_tip": 2500,
"maximum_delivery_tip": 4500
}
```
- 단순 조회 쿼리(영속성 유지 필요 없음) + 복수의 @OneToOne 관계로 인한 비효율 문제로 jpql dto 프로젝션으로 구현했습니다.
```json
{
"shop_id": 11,
"orderable_shop_id": 2,
"name": "굿모닝살로만치킨",
"address": "충청남도 천안시 동남구 병천면 …
```
> feat: 주문 가능 상점 정보 단건 조회 API 추가

- src/main/java/in/koreatech/koin/domain/student/dto/RegisterStudentRequestV2.java
- src/main/java/in/koreatech/koin/domain/student/dto/UpdateStudentRequestV2.java
- src/main/java/in/koreatech/koin/domain/user/dto/UserRegisterRequest.java
- src/main/java/in/koreatech/koin/domain/user/dto/UserUpdateRequest.java
> fix: 유저와 학생 회원가입 및 업데이트 유효성 검사 통일

- src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
- src/main/java/in/koreatech/koin/domain/club/repository/redis/ClubHitsRedisRepository.java
- src/main/java/in/koreatech/koin/domain/club/scheduler/ClubScheduler.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubScheduleService.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
- close #1663 
- 동아리 기능 사용률이 높아짐
- 동아리 상세조회 시 조회수 카운팅으로 인해 매번 쓰기를 수행하는 것은 반복적인 DB 부하
- 또한 인기 동아리인 경우 여러명이 동시에 접근할때 동시성 문제도 발생할 수 있음
- 이는 기존의 비관적 락 방식(SELECT → UPDATE)에서 앞서 단순 UPDATE 방식으로 변경해 락 점유를 개선한 바 있음
- 하지만, 여전히 row-level lock으로 인한 병목 발생
- 조회수는 정합성, 실시간성이 매우 중요한 부분은 아님
- 반복적인 DB 쓰기로 인한 부하를 줄일 수 있음 
- 10분마다 스케줄링을 통해 조회수 일괄 갱신 
- 조회 트래픽 급증시에도 안정적 처리
- 동시성 문제 해결
- Redis의 INCR는 원자적으로 작동 
- 추후 인기 동아리 관리와 여러 캐싱통계 활용 가능
- 조회가 발생하는 경우 redis에 INCR로 카운팅
- 10분마다 스케줄링 수행
- 조회가 발생한 key를 통해 Id를 추출
- Id가 여전히 유효한 지 쿼리하여 유효한 Id만 남김
- 해당 Id들에 대해 조회수 갱신 수행
- 배치 시간 내에 redis에 저장된 id의 동아리가 삭제될 수 있음
-  Id가 여전히 유효한 지 쿼리하여 유효한 Id만 남기고 로직 수행하도록 개선
- 갱신중간에 실패할 수 있음
- try-catch를 통해 로깅 및 다음 스케줄링 시 재시도하도록 구성
- 고려하지 못한 예외가 있다면 리뷰 부탁드립니다!
> refactor: 동아리 조회수 갱신 로직을 redis 스케줄링 방식으로 변경

- src/main/java/in/koreatech/koin/_common/exception/GlobalExceptionHandler.java
- src/main/java/in/koreatech/koin/domain/order/address/controller/AddressApi.java
- src/main/java/in/koreatech/koin/domain/order/address/controller/AddressController.java
- src/main/java/in/koreatech/koin/domain/order/address/dto/AddressSearchRequest.java
- src/main/java/in/koreatech/koin/domain/order/address/dto/AddressSearchResponse.java
- src/main/java/in/koreatech/koin/domain/order/address/dto/RoadNameAddressApiResponse.java
- src/main/java/in/koreatech/koin/domain/order/address/exception/AddressApiException.java
- src/main/java/in/koreatech/koin/domain/order/address/exception/AddressErrorCode.java
- src/main/java/in/koreatech/koin/domain/order/address/service/AddressService.java
- src/main/java/in/koreatech/koin/domain/order/address/service/client/RoadNameAddressClient.java
- src/test/resources/application.yml
- #1496 
1. 행정안전부 주소기반산업지원서비스 도로명주소 검색 API 호출 (https://business.juso.go.kr/addrlink/openApi/searchApi.do)
- 외부 API 호출 재미있어요
> feat: 도로명 주소 API 추가

- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
- close #1699
1. `post /v2/users/students/me`: 학부 수정 시 다른 유저 정보(ex: 성별, 이름 등) 미수정 오류 수정
2. [관련 쓰레드](https://bcsdlab.slack.com/archives/C08GSHWASLC/p1751096882710819)
1. `updateStudentInfo(student, request.studentNumber(), request.major());` 메소드 내부에 `entityManager.clear()` 동작이 포함
2. User JPA 엔티티 detached
3. 더티체크를 하지 못해 User 변경사항이 업데이트 안됨
기존의 `Student 정보 수정(clear) -> User 정보 수정` 
`User 정보 수정 -> Student 정보 수정(clear)` << 이렇게 순서 변경
> fix: 사용자 정보 수정 미반영 오류 수정

- src/main/java/in/koreatech/koin/_common/code/ApiResponseCode.java
- src/main/java/in/koreatech/koin/_common/exception/GlobalExceptionHandler.java
- src/main/java/in/koreatech/koin/domain/order/delivery/controller/DeliveryApi.java
- src/main/java/in/koreatech/koin/domain/order/delivery/controller/DeliveryController.java
- src/main/java/in/koreatech/koin/domain/order/delivery/dto/UserOffCampusDeliveryAddressValidateRequest.java
- src/main/java/in/koreatech/koin/domain/order/delivery/service/DeliveryAddressValidator.java
- src/main/java/in/koreatech/koin/domain/order/delivery/service/DeliveryService.java
- src/test/java/in/koreatech/koin/unit/domain/address/DeliveryAddressValidatorTest.java
- #1718 
- requestLogging 메서드에서 생성된 errorTraceId를 ErrorResponse에서 반환
> feat: 교외 배달 주소 검증 API 추가

- src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
- src/main/java/in/koreatech/koin/domain/order/cart/dto/CartResponse.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/OrderableShop.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/OrderableShopImage.java
- src/main/resources/db/migration/V193__add_orderable_shop_image_table.sql
- close #1704 
- 장바구니 조회 API에 이미지(상점, 메뉴) 응답값을 추가했습니다.
레거시인지 모르겠는데, 상점 이미지의 경우 리스트로 관리가 되고 있더라구요
썸네일을 위해 링크 하나만 던져줘야 할까요..? (메뉴도 동일 / 아침에 여쭤보겠읍니다 )
> feat: 장바구니 조회 API 이미지 응답값 추가

- src/main/java/in/koreatech/koin/_common/event/ClubRecruitmentChangeEvent.java
- src/main/java/in/koreatech/koin/_common/model/MobileAppPath.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubRecruitmentSubscriptionRepository.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
- src/main/java/in/koreatech/koin/domain/notification/eventlistener/ClubRecruitmentEventListener.java
- src/main/java/in/koreatech/koin/domain/notification/model/NotificationFactory.java
- close #1734 
- 모집 생성, 수정 시 이벤트발행
- 이벤트 리스너에서 알림 보냄 
- 특정 동아리 모집알림 구독 API 구현
- 특정 동아리 모집알림 구독취소 API 구현
- 특정 동아리 상세조회 API에서 유저의 특정 동아리 모집알림 구독여부를 같이 반환해주는 것 추가 필요 (완료)
> feat: 동아리 모집 알림 추가 및 특정 동아리 모집알림 구독/구독취소 API

- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubEventsResponse.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubEventSubscriptionRepository.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
- src/main/java/in/koreatech/koin/domain/notification/model/NotificationFactory.java
- close #1740 
- 특정 동아리 행사 전체조회 API에서 유저의 각 행사 구독여부를 함께 반환하도록 추가했습니다.
- 모집 알림 scheme를 club-recruitment?id={clubid}로 변경했습니다.
-
> feat: 특정 동아리 행사 전체조회 반환값에 구독여부 추가 및 모집 알림 scheme 변경

- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubEventResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubEventsResponse.java
- close #1773 
- 동아리 행사 조회 시 `행사 상태` 응답값을 수정했습니다.
- 예시와 달리, enum의 name이 아닌 displayname으로 반환하는 로직을 수정했습니다.
- API 설명도 수정했습니다.
> fix: 동아리 행사 조회 응답값 수정

- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubUpdateRequest.java
- close #1779 
- 동아리 대표 전화번호 검증 로직을 추가했습니다.
> feat: 동아리 대표 전화번호 검증 추가

- src/main/java/in/koreatech/koin/domain/timetableV2/service/TimetableLectureService.java
- src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
- close #1784 
1. 일단 급한 불을 끄기 위해 동시성 처리 어노테이션을 걸어두었습니다.
- 추후 리팩터링하며 isDeleted 를 삭제하든, isDeleted된 강의가 있으면 전환하든 해야합니다.
- niginx로 rateLimit을 2일 내로 추가해두겠습니다.
> hotfix: 시간표 강의 추가 동시성 방지 어노테이션 추가 (develop)

- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubEventCreateRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubEventModifyRequest.java
- close #1803 
1. INVALID_CLUB_EVENT_RERIOD가 작동하지 않는 문제를 수정했습니다.
오류 코드 만들고 적용 안 시킨 사람이 있다?
> fix: 동아리 행사 생성/수정 시작-종료날짜 입력 오류 수정

- src/main/java/in/koreatech/koin/domain/club/model/ClubBaseInfo.java
- close #1820
- 동아리 전체 조회 시 모집 D-day 계산 로직을 수정했습니다.
- `endDate - startDate`가 아닌 `endDate - now`으로 수정해야 정상적으로 디데이 계산이 됩니다.
> fix: 동아리 전제 조회 시 모집 D-day 계산 로직 수정

- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubRecruitmentResponse.java
- src/main/java/in/koreatech/koin/domain/club/enums/ClubRecruitmentStatus.java
- src/main/java/in/koreatech/koin/domain/club/enums/ClubSortType.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubBaseInfo.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubRecruitment.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubRecruitmentDday.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubListQueryRepository.java
- close #1822
- 동아리 전체 조회 시 정렬 로직을 수정했습니다.
- 모집 마감 순에서 제대로 정렬이 안되는 문제가 발생했습니다.
- `case end`으로 우선 순위를 주고, 정렬하도록 수정했습니다. (주석 참고)
```sql
select
c1_0.id,
c1_0.name,
c4_0.name,
c1_0.likes,
c1_0.image_url,
abs(sign(?))=abs(sign(?)),
c1_0.is_like_hidden,
c2_0.start_date,
c2_0.end_date,
c2_0.is_always_recruiting 
from
club c1_0 
left join
club_recruitment c2_0 
on c2_0.club_id=c1_0.id 
join
club_category c4_0 
on c4_0.id=c1_0.club_category_id 
where
c2_0.id is not null 
and (
c2_0.end_date>=? 
or c2_0.is_always_recruiting=?
) 
and lower(replace(c1_0.name,' ','')) like ? escape '!' 
and c1_0.is_active=? 
order by
datediff(c2_0.end_date,current_date),
c2_0.is_always_recruiting desc
- 동아리 모집 D-Day, 상태 계산 로직을 리펙토링했습니다.
- 상태 계산 로직의 경우 enum 내부로 옮겼습니다.
- D-Day의 경우 `ClubRecruitmentDday` 개념 객체를 만들어서 내부에 …
```
> fix: 동아리 전체 조회 시 정렬 로직 수정

- .github/workflows/flyway-dangerous-sql-validator.yml
- src/main/java/in/koreatech/koin/_common/code/ApiResponseCodesOperationCustomizer.java
- src/main/java/in/koreatech/koin/_common/exception/CustomException.java
- src/main/java/in/koreatech/koin/domain/user/model/User.java
- src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
- src/main/java/in/koreatech/koin/domain/user/verification/model/VerificationCode.java
- src/main/java/in/koreatech/koin/domain/user/verification/model/VerificationCount.java
- src/main/java/in/koreatech/koin/infrastructure/config/FcmConfig.java
- src/main/resources/logback-spring.xml
- close #1830 
1. SQL 검증 실패 시 파일 위치 및 SQL문 출력
PR에 포함된 Flyway SQL에서 위험한 명령(DROP, RENAME 등)이 감지되면, 해당 파일 경로와 문제가 된 SQL문을 출력합니다.
2. 에러 스택 트레이스 추가
GitHub Actions 실패 시 발생한 오류에 대해 에러 메시지와 함께 스택 트레이스를 출력합니다.
이를 사용하지 않을 경우, try-catch문으로 CustomError를 반환하였을 때, catch한 Error의 로그가 출력되지 않아 디버깅이 어려워질 우려가 있기에 추가하였습니다.
3. Swagger 성공 응답값 표시
기존에는 200 응답이 "string"으로 잘못 표시되던 문제를 수정했습니다.
4. 로컬환경에서 fcm과 slack 연동 실패로 인한 콘솔창이 오류 로그로 채워지는 것을 방지하였습니다.
> refactor: SQL 검증 실패 시 파일위치 및 SQL문 출력, 에러 스택 트레이스 추가, Swagger 성공 응답값 표시

- src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
- 동아리 검색어에 따른 연관검색어 조회 쿼리를 수정했습니다.
- 공백, 대소문자 구분이 되는 오류를 수정했습니다.
> hotfix: 동아리 검색어에 따른 연관검색어 조회 쿼리 수정 (main)

- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
- src/main/java/in/koreatech/koin/domain/club/model/Club.java
- src/main/java/in/koreatech/koin/domain/club/model/redis/ClubCreateRedis.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubListQueryRepository.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
- close #1848 
- 검색할 때 대소문자, 띄어쓰기 구분 없이 검색되어야함
- 해당 조건을 만족하면서 충분한 성능
- 검색에서 공백 삭제, 소문자로 변환하여 DB의 동아리명과 비교
- 동아리명은 공백이 포함될 수 있음
- 동아리명은 대소문자가 섞여있을 수 있음
→ 기존 로직은 올바르게 동작하지 않음
- DB에서 name을 비교할 때 쿼리로 REPLACE로 공백제거 및 LOWER로 소문자화해서 비교
- 이는 쿼리에 로직처리를 위임한 것이므로 바람직하지 못함
- 또한 기존의 의도인 index RangeScan을 타지못해서 매우 비효율적임
- 쿼리에 위임하지 않으면서 성능까지 챙길 방안
- 동아리 생성, 수정 시 동아리명이 정규화된 형태(공백제거, 소문자화)를 진행한 컬럼을 추가로 관리
- 동아리 검색, 연관검색시 이 컬럼(normalizedName)을 이용하여 검색
- normalizedName에 대한 index추가 (index RangeScan을 위한)
- 검색 결과는 기존 동아리명으로 제공할 수 있음
→ index RangeScan을 활용할 수 있고 query의 정규화 처리를 하지 않아도 됨
-
> refactor: 동아리 검색&연관검색 기능 개선

- src/main/java/in/koreatech/koin/_common/exception/CustomException.java
- src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
- src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
- src/main/java/in/koreatech/koin/domain/order/cart/dto/CartAddItemCommand.java
- src/main/java/in/koreatech/koin/domain/order/cart/dto/CartAddItemRequest.java
- src/main/java/in/koreatech/koin/domain/order/cart/dto/CartItemsCountSummaryResponse.java
- src/main/java/in/koreatech/koin/domain/order/cart/dto/CartUpdateItemRequest.java
- src/main/java/in/koreatech/koin/domain/order/cart/model/Cart.java
- src/main/java/in/koreatech/koin/domain/order/cart/model/CartMenuItem.java
- src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
- src/main/java/in/koreatech/koin/domain/order/cart/service/CartService.java
- src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
- src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopController.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopCategoryFilterCriteria.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuOptionGroup.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/entity/menu/OrderableShopMenuOptionGroupMap.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/ShopOperation.java
- src/main/java/in/koreatech/koin/domain/order/shop/usecase/OrderableShopSearchUseCase.java
- src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
- src/test/java/in/koreatech/koin/unit/domain/cart/CartServiceTest.java
- src/test/java/in/koreatech/koin/unit/domain/cart/CartTest.java
- src/test/java/in/koreatech/koin/unit/domain/order/ShopOpenScheduleServiceTest.java
- src/test/java/in/koreatech/koin/unit/fixutre/CartFixture.java
- src/test/java/in/koreatech/koin/unit/fixutre/CartMenuItemFixture.java
- src/test/java/in/koreatech/koin/unit/fixutre/OrderableShopFixture.java
- src/test/java/in/koreatech/koin/unit/fixutre/OrderableShopMenuFixture.java
- src/test/java/in/koreatech/koin/unit/fixutre/OrderableShopOpenInfoFixture.java
- #1842 
```json
{
"itemTypeCount": 0,
"totalQuantity": 0
}
```
- 상점의 배달/포장 가능 여부와 관계 없이 장바구니에 담긴 상품의 종류와 총 수량 정보를 반환합니다.
- EX) 담긴 상품의 종류가 2개고 각각 3개, 4개의 수량 이라면
- **itemTypeCount** : 2
- **totalQuantity** : 7
```java
@Schema(description = "메뉴 개수", example = "1", requiredMode = REQUIRED)
@NotNull(message = "quantity는 필수값입니다.")
@Min(value = 1, message = "수량은 최소 1 입니다.")
@Max(value = 10, message = "수량은 최대 10 입니다.")
Integer quantity
```
> feat: 장바구니(CartService) 단위 테스트 작성 + 담긴 상품 수량 정보 API 등

- src/main/java/in/koreatech/koin/domain/community/lostitem/chatroom/service/LostItemChatRoomInfoService.java
- src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
- src/main/java/in/koreatech/koin/domain/order/cart/dto/CartMenuItemEditResponse.java
- src/main/java/in/koreatech/koin/domain/order/cart/dto/CartUpdateItemRequest.java
- src/main/java/in/koreatech/koin/domain/order/cart/model/CartMenuItem.java
- src/main/java/in/koreatech/koin/domain/order/cart/service/CartService.java
- src/test/java/in/koreatech/koin/unit/domain/cart/CartServiceTest.java
- #1859 
---
* 옵션 변경 페이지에서 수량까지 변경할 수 있어야 함
* 장바구니 옵션 변경용 메뉴 조회 API `quantity` 응답 필드 추가
* 장바구니 상품의 가격 및 옵션 구성 변경 API `quantity` 요청 필드 추가
---
* 
---
> refactor: 비즈니스 2차 QA (장바구니 상품 수정 API)

- src/test/java/in/koreatech/koin/unit/domain/community/lostitem/chatroom/service/LostItemChatRoomInfoServiceTest.java
- src/test/java/in/koreatech/koin/unit/fixutre/LostItemArticleFixture.java
- src/test/java/in/koreatech/koin/unit/fixutre/LostItemChatFixture.java
- #1798 리팩터링 과정에서 코드가 잘못 수정되었으나, 테스트 코드 누락으로 인해 오류를 사전에 발견하지 못하여 스테이지 환경에서 장애가 발생함 (25/08/02)
- 동일한 문제의 재발 방지를 위해 LostItemChatRoomInfoService에 대한 테스트 코드를 추가함
- 관련 이슈: #1861
---
- LostItemChatRoomInfoService의 getOrCreateChatRoomId 메서드에 대한 단위 테스트 추가
- ✅ 기존 채팅방 조회 시나리오
- ✅ 새 채팅방 생성 시나리오 (첫 번째 채팅방, N번째 채팅방)
- ✅ 예외 상황 처리 (자기 자신과의 채팅, 탈퇴 사용자 게시글)
- 정상 케이스 3개, 예외 케이스 2개로 주요 비즈니스 로직 검증
- Mock을 활용한 의존성 격리 및 행위 검증(verify) 포함
---
* 
---
> feat: 분실물 채팅방 생성 및 조회 서비스 테스트 코드 작성

- src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
- src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
- src/main/java/in/koreatech/koin/domain/order/cart/model/Cart.java
- src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/entity/shop/OrderableShop.java
- #1866 
---
* 장바구니 검증 API OrderType 조건 추가
- 주문 타입이 배달(OrderType.DELIVERY) 일 경우
- 상점이 현재 주문 가능 상태(영업 중) 인지 검증
- 장바구니에 담긴 상품의 총 금액이 상점의 최소 주문 금액을 충족하는지 검증
- 주문 타입이 포장(OrderType.TAKE_OUT) 일 경우
- 상점이 현재 주문 가능 상태(영업 중) 인지 검증
---
* 
---
> fix: 비즈니스 3차 QA - 장바구니 검증 API 주문 타입 조건 추가

- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- src/main/java/in/koreatech/koin/domain/community/keyword/model/UserNotificationStatus.java
- src/main/java/in/koreatech/koin/domain/community/keyword/repository/UserNotificationStatusRepository.java
- src/main/java/in/koreatech/koin/domain/community/keyword/service/KeywordService.java
- src/main/java/in/koreatech/koin/domain/notification/eventlistener/ArticleKeywordEventListener.java
* 키워드 알림 중복 발송 문제 발생
- close #1875 
---
* 아직 알림을 보내지 않은 게시글에 대해서만 알림을 보내도록 수정
* 게시글 키워드 알림을 보낸 것을 모두 저장하도록 수정
* 그렇기에 최신 게시글이 DB에 저장되었는지만 필터링하면 중복 방지 가능
---
* 추후 eventListener의 비즈니스로직을 정리해야함
---
> hotfix: 키워드 알림 중복 발송 문제 해결 (main)

- src/test/java/in/koreatech/koin/acceptance/AcceptanceTest.java
- src/test/java/in/koreatech/koin/acceptance/domain/BusApiTest.java
- src/test/java/in/koreatech/koin/acceptance/domain/DiningApiTest.java
- src/test/java/in/koreatech/koin/acceptance/domain/KeywordApiTest.java
- src/test/java/in/koreatech/koin/acceptance/domain/OwnerShopApiTest.java
- src/test/java/in/koreatech/koin/acceptance/domain/ShopReviewApiTest.java
- src/test/java/in/koreatech/koin/acceptance/domain/StudentApiTest.java
- src/test/java/in/koreatech/koin/acceptance/support/DBInitializer.java
- DBInitializer 클래스의 initIncrement 메소드에서 AUTO_INCREMENT 초기화를 수행
- 현재 조건이 `AUTO_INCREMENT >= 1` 로 설정되어 있어, 실제로 데이터가 삽입되지 않은 테이블까지 불필요하게 롤백
- 이로 인해 각 테스트 메소드 종료 시마다 모든 테이블에 `ALTER TABLE %s AUTO_INCREMENT = 1` 쿼리가 실행되어 테스트 속도 저하
- AUTO_INCREMENT 값이 1보다 큰 테이블만 대상으로 롤백하도록 로직 개선
- DBInitializer 클래스의 truncateAllTable 메소드에서 테이블 TRUNCATE 수행
- 현재 조건이 모든 테이블에 대해 TRUNCATE를 수행
- 이로 인해 각 테스트 클래스 종료 시 마다 모든 테이블에 `TRUNCATE TABLE` 쿼리가 실행되어 테스트 속도 저하
- 데이터가 들어간 테이블에 대해서만 TRUNCATE 쿼리가 실행되게 하여 로직 개선
- close #1874
---
```sql
Hibernate:
SELECT
TABLE_NAME
FROM
INFORMATION_SCHEMA.TABLES
WHERE
TABLE_SCHEMA = 'test'
AND AUTO_INCREMENT >= 1
Hibernate:
ALTER TABLE abtest AUTO_INCREMENT = 1
Hibernate:
ALTER TABLE abtest_variable AUTO_INCREMENT = 1
Hibernate:
ALTER TABLE access_history AUTO_INCREMENT = 1
...
```
- 각 …
> refactor: 인수 테스트 과정에서 불필요한 DB 초기화 쿼리 실행 개선

- src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopRepository.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopEventService.java
* 요청이 많지 않음에도 P95 LATENCY가 높음
* 확인해보니 한번의 요청당 동일한 쿼리가 72번 발생함 
- close #1887 
---
* Shop과 EventArticle이 OneToMany 관계로 Lazy로딩 되어 n+1 문제가 발생하였습니다.
* 상점 조회시 이벤트도 함꼐 조회 (fetch join)하도록 수정하였습니다.
---
* Stage에서 성능 체크하여 여기에 기록하겠습니다.
---
> refactor: 모든 상점 이벤트 조회 쿼리 개선

- src/test/java/in/koreatech/koin/unit/domain/order/OrderableShopMenuOptionsTest.java
* OrderableShopMenuOptions 클래스의 단위테스트를 추가한다.
- close #1898
---
* OrderableShopMenuOptions 클래스의 단위테스트를 추가했습니다.
---
* 옵션 그룹에서 동일 옵션에 대한 선택이 복수로 이뤄지는 경우 기능이 동작하는데,  해당 기능이 의도적인 동작인지 궁금합니다.
*(아래코드에서 라면을 2개 선택해도 정상적으로 기능함)
```java
// 필수 옵션 그룹 2 (최소 2개, 최대 3개 선택) 여기서 라면만 2개 골라도 정상적으로 동작됨
requiredOptionGroup2 = OrderableShopMenuFixture.createMenuOptionGroupWithEmptyMenuOption(
orderableShop, "국물", 2, 3, true, 2);
requiredOption3 = OrderableShopMenuFixture.createMenuOption(
requiredOptionGroup2, "라면", 2000, 3);
requiredOption4 = OrderableShopMenuFixture.createMenuOption(
requiredOptionGroup2, "우동", 1500, 4);
requiredOption5 = OrderableShopMenuFixture.createMenuOption(
requiredOptionGroup2, "떡국", 2500, 5);
```
---
> feat: OrderableShopMenuOptions 단위 테스트 추가

- src/main/java/in/koreatech/koin/admin/history/aop/AdminActivityHistoryAspect.java
* [프로덕션 배포](https://github.com/BCSDLab/KOIN_API_V2/pull/1905) 이후 코인 어드민이 로그인 안 되는 상황 발생
---
* 코인 어드민 히스토리 AOP 포인트 컷 수정
* [코인 어드민 패키지 분리 작업](https://github.com/BCSDLab/KOIN_API_V2/pull/1882)을 진행했음
* 코인 어드민 히스토리의 경우 개인 정보(비밀번호)가 포함된 요청, GET 요청을 제외한 모든 API에 대해 기록
* 패키지 경로 & GetMapping 어노테이션을 통해서 해당 케이스를 제외 시켰음
* 코인 어드민 패키지가 변경됨에 따라 AOP 경로에서 제외되고, 코인 어드민 로그인 API가 히스토리 AOP를 타게 됨
* 로그인 과정에서는 AuthContext의 userId가 null이기 때문에 조회 오류 발생
-> 변경된 패키지 경로로 코인 어드민 히스토리 AOP 포인트 컷을 수정
---
* 향후 진행 사항
* 현재 API Path, 패키지 경로를 통해서 로직이 분기되어 있음
* 이를 해결하기 위해 코인 어드민 히스토리 로깅 전용 어노테이션을 구현하여, 해당 문제 해결
---
> hotfix: 코인 어드민 로그인 오류 수정 (main)

- src/main/java/in/koreatech/koin/domain/payment/model/entity/Payment.java
- close #1923 
---
* Payment Enum 필드에 걸려있는 Size 어노테이션을 삭제했습니다.
* Enum의 경우 Size 어노테이션이 작동하지 않습니다.
---
* 
---
> fix: Payment 필드 유효성 검증 어노테이션 수정

- src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerRegisterByPhoneRequest.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerSmsService.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerValidator.java
- src/test/java/in/koreatech/koin/acceptance/domain/OwnerApiTest.java
* 유저테이블 부분적 분리 작업 과정에서 사장님의 전화번호는 owner 테이블의 account 컬럼에 저장하도록 변경
* 기존 회원 가입 로직에서 owner 테이블의 account가 아닌 users 테이블의 phone_number을 통해 유니크 검사 & users 테이블에 전화번호가 저장되고 있었음
* users 테이블에 insert 과정에서 유니크 에러 발생
- close #1919
---
* 사장님 전화번호 유효성 검증 로직을 수정했습니다.
* 엔티티 변환 과정에서 user 테이블에 전화번호가 저장되지 않도록 수정했습니다.
---
* 
---
> fix: 사장님 회원가입 전화번호 검증 수정

- src/main/java/in/koreatech/koin/domain/order/model/Order.java
- src/main/java/in/koreatech/koin/domain/payment/model/entity/Payment.java
- src/main/java/in/koreatech/koin/domain/payment/model/redis/TemporaryPayment.java
- src/main/java/in/koreatech/koin/domain/payment/service/PaymentCancelService.java
* 결제 취소 과정에서 order 테이블의 결제 취소 관련 컬럼을 업데이트 수행하지 않고 있음
- close #1938 
---
* order 테이블의 status(주문상태), canceled_at(취소 일시), canceled_reason(취소 사유)를 업데이트 하도록 수정
---
* 
---
> fix: 결제 취소 로직 수정

- src/main/java/in/koreatech/koin/domain/order/model/Order.java
- src/main/java/in/koreatech/koin/domain/order/model/OrderDelivery.java
- src/main/java/in/koreatech/koin/domain/order/model/OrderInfo.java
- src/main/java/in/koreatech/koin/domain/order/model/OrderSearchCriteria.java
- src/main/java/in/koreatech/koin/domain/order/model/OrderStatus.java
- src/main/java/in/koreatech/koin/domain/order/model/OrderTakeout.java
- src/main/java/in/koreatech/koin/domain/order/order/controller/OrderApi.java
- src/main/java/in/koreatech/koin/domain/order/order/controller/OrderController.java
- src/main/java/in/koreatech/koin/domain/order/order/controller/OrderTestApi.java
- src/main/java/in/koreatech/koin/domain/order/order/controller/OrderTestController.java
- src/main/java/in/koreatech/koin/domain/order/order/dto/request/OrderSearchCondition.java
- src/main/java/in/koreatech/koin/domain/order/order/dto/request/OrderSearchPeriodCriteria.java
- src/main/java/in/koreatech/koin/domain/order/order/dto/request/OrderStatusCriteria.java
- src/main/java/in/koreatech/koin/domain/order/order/dto/request/OrderTypeCriteria.java
- src/main/java/in/koreatech/koin/domain/order/order/dto/response/OrdersResponse.java
- src/main/java/in/koreatech/koin/domain/order/order/service/OrderService.java
- src/main/java/in/koreatech/koin/domain/order/order/service/OrderTestService.java
- src/main/java/in/koreatech/koin/domain/order/repository/OrderRepository.java
- src/main/java/in/koreatech/koin/domain/order/repository/OrderSearchQueryRepository.java
- src/main/java/in/koreatech/koin/domain/payment/repository/PaymentRepository.java
- src/main/java/in/koreatech/koin/global/code/ApiResponseCode.java
- 지난 주문 페이지에서 사용할 주문 내역 리스트 조회 API 추가
- close #1940 
---
* 주문 내역 리스트 조회 API를 추가했습니다.
* 필터링 조건은 `조회 기간, 주문 상태, 주문 정보(주문 타입)` 입니다.
* 페이지네이션 API으로 요청을 받아서 페이지네이션으로 작업했습니다.
---
* 사진에 주소가 나와있는데, 해당 부분은 제외될 부분입니다.
---
> feat: 주문 내역 리스트 조회 API 추가

- src/main/java/in/koreatech/koin/domain/order/order/dto/response/InprogressOrderResponse.java
* 현재 sprint에 사용되는 두개의 API (/order, /order/in-progress)의 응답값(변수명)이 달라 /order/in-progress API의 변수명을 통일함.
- close #1959 
---
* 응답값(변수명)을 통일하기 위해 변수명 변경하였습니다.
---
*
---
- [] 테스트 코드 포함됨
> fix: 활성화된 주문 조회 API 응답값(변수명) 통일

- src/main/java/in/koreatech/koin/domain/order/order/model/OrderDelivery.java
- src/main/java/in/koreatech/koin/domain/order/order/model/OrderTakeout.java
- src/main/java/in/koreatech/koin/domain/order/order/service/OrderTestService.java
* 현재 confirming이 아닐 경우 null을 허용하지 않으나, status를 바꾸는 API에서 고려가 되지 않았기 때문에 confirming이 아닐 떄 예상 시각이 null이면 localTime을 넣도록 변경함
- close #1966 
* OrderDelivery, OrderTakeout 쪽에 예상 시각(estimated_packaged_at, estimated_arrival_at)을 변경하는 로직 추가
---
* 
---
- [] 테스트 코드 포함됨
> fix: confirming이 아닐 때 예상 시각이 null이면 localTime을 넣도록 변경

- src/main/java/in/koreatech/koin/domain/payment/controller/PaymentApi.java
- src/main/java/in/koreatech/koin/domain/payment/dto/request/TemporaryDeliveryPaymentSaveRequest.java
- src/main/java/in/koreatech/koin/domain/payment/service/PaymentService.java
- 임시 배달 결제 정보 저장 API의 교내 배달 주소 검증 과정에서 클라이언트에서 인자로 넘기는 address 를 그대로 사용하면 검증 오류가 발생
```java
@JsonNaming(value = SnakeCaseStrategy.class)
public record TemporaryDeliveryPaymentSaveRequest(
@Schema(description = "배달 주소", example = "충청남도 천안시 동남구 병천면 충절로 1600", requiredMode = REQUIRED)
@NotBlank(message = "배달 주소는 필수 입력사항입니다.")
String address
```
- `address` 값에 `충청남도 천안시 동남구 병천면 충절로 1600 한국기술교육대학교 제1캠퍼스 생활관 104동` 이나 `충청남도 천안시 동남구 병천면 충절로 1600 한국기술교육대학교 제1캠퍼스 생활관` 을 넘겨주고 있는 상황. 
- 검증에 사용하는 외부 API에서 해당 주소를 정상적인 주소로 판단하지 못하는 문제 발생
1. 임시 결제 정보 저장 API Request에 교내배달, 교외배달 타입 필드 추가해서 교내 배달인 경우 검증 생략하기
2. 검증 외부 API에서 정상적인 주소로 판단하는 `충청남도 천안시 동남구 병천면 충절로 1600 한국기술교육대학교` 값을 넘길 수 있는 필드 추가하기
- 2번 의 경우 DB에 불필요한 데이터를 추가해야 하는 작업 필요. 배달 타입 필드를 클라이언트 내부에서 관리하고 있으므로 1번 방법을 사용하기로 결정함.
- close #1967
---
* 임시 결제 정보 …
> feat: 임시 배달 결제 정보 저장 API 배달 타입 요청값 추가

- src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentConfirmResponse.java
- src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentResponse.java
- 클라이이언트 요청으로 결제 조회 API 응답값을 추가했습니다.
- close #1957 
---
* `POST /payments/confirm, GET /payments/{paymentId}` 응답값에 `배달비, 메뉴 총 금액, 주문 가능 상점 ID`를 추가했습니다.
---
* 
---
> feat: 결제 조회 API 응답값 추가

- src/main/java/in/koreatech/koin/domain/order/order/dto/response/OrdersResponse.java
- src/main/java/in/koreatech/koin/domain/order/order/model/OrderDelivery.java
- src/main/java/in/koreatech/koin/domain/order/order/model/OrderInfo.java
- src/main/java/in/koreatech/koin/domain/order/order/repository/OrderSearchQueryRepository.java
- src/main/java/in/koreatech/koin/domain/payment/controller/PaymentApi.java
- src/main/java/in/koreatech/koin/domain/payment/dto/request/TemporaryDeliveryPaymentSaveRequest.java
- src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentConfirmResponse.java
- src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentResponse.java
- src/main/java/in/koreatech/koin/domain/payment/model/domain/DeliveryPaymentInfo.java
- src/main/java/in/koreatech/koin/domain/payment/model/redis/TemporaryPayment.java
- src/main/java/in/koreatech/koin/domain/payment/service/PaymentService.java
- src/main/java/in/koreatech/koin/domain/payment/service/TemporaryPaymentService.java
- src/main/resources/db/migration/V225__alter_order_delivery_add_column.sql
- 클라이언트 요청으로 위,경도 요청값 추가
- close #1955
---
* POST /payments/temporary/delivery 요청값에 위도, 경도 값을 추가했습니다.
* order_delivery_v2 테이블에 주문 주소의 위도, 경도 컬럼을 추가했습니다.
* 주문 조회 응답값에 주문 주소의 위도, 경도 값을 추가했습니다.
---
* 
---
> feat: 임시 결제 저장 정보 저장 API 위,경도 요청값 추가

- src/main/java/in/koreatech/koin/domain/order/order/model/OrderDelivery.java
- src/main/java/in/koreatech/koin/domain/payment/dto/request/TemporaryDeliveryPaymentSaveRequest.java
* order_delivery_v2 테이블의 위도, 경도 컬럼이 nullable
* OrderDelivery의 위도, 경도 컬럼에 Notnull 어노테이션이 걸려있어서 에러 발생
- close #1973 
---
* OrderDelivery 클래스 위도, 경도 컬럼에 걸려있는 NotNull 어노테이션을 삭제했습니다.
---
* 
---
> fix: 위도, 경도 유효성 검증 어노테이션 삭제

- src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
- src/main/java/in/koreatech/koin/domain/notification/eventlistener/CoopEventListener.java
- src/main/java/in/koreatech/koin/domain/notification/repository/NotificationSubscribeRepository.java
- src/main/java/in/koreatech/koin/domain/notification/service/NotificationService.java
* 식단 품절 API (PATCH /coop/dining/soldout)에서 알림 구독자를 조회하는 과정에서 알림 구독자 수만큼 쿼리가 발생
* 확인 결과, 모든 식단 알림 구독자를 조회 이후 품절 식단(아침, 점심, 저녁) 알림을 구독했는 지 추가 조회함으로써 추가 쿼리 발생
- close #2010 
---
```java
var notifications = notificationSubscribeRepository
.findAllBySubscribeTypeAndDetailTypeIsNull(DINING_SOLD_OUT).stream()
.filter(subscribe -> notificationSubscribeRepository.existsByUserIdAndSubscribeTypeAndDetailType(
subscribe.getUser().getId(),
DINING_SOLD_OUT,
detailType
))
```
* `findAllBySubscribeTypeAndDetailTypeIsNull` 메소드로 식단 알림 구독 리스트 1차 조회
* 알림 구독 리스트에서 (user_id, subscrib_type, detail_type)를 통해 품절 식단 알림 구독자 리스트를 2차 조회
* subscrib_type : DINING_SOLD_OUT
* detail_type : 아침, 점심, 저녁
* 이 과정에서 알림 구독자 수만큼 쿼리 발생
``` java
@Query("""
SELECT DISTINCT ns
FROM NotificationSubscribe ns
JOIN FETCH ns.user u
WHERE …
```
> refactor: 식단 품절 알림 구독자 조회 로직 개선

- src/main/java/in/koreatech/koin/domain/order/order/controller/OrderApi.java
- src/main/java/in/koreatech/koin/domain/order/order/dto/response/InprogressOrderResponse.java
- src/main/java/in/koreatech/koin/domain/payment/controller/PaymentApi.java
- src/main/java/in/koreatech/koin/domain/payment/dto/response/PaymentResponse.java
- src/main/java/in/koreatech/koin/domain/payment/service/PaymentQueryService.java
* 주문 조회(/order/in-progress) 시 상점 id를 반환하도록 한다.
* 결제 단건 조회(/payments/{paymentId}) 시 예상 시간과 주문 상태를 반환하도록 한다.
- close #2011 
---
* 주문 조회 시 상점 id도 반환하도록 추가하였습니다.
* 결제 단건 조회 시 예상 시간(estimated_at)과 주문 상태(order_status)를 반환하도록 추가하였습니다.
---
* 결제 단건 조회의 응답 body 필드 설명을 추가하였습니다.
---
> feat: 주문 진행 상황 조회 시 상점 id 반환, 결제 단건 조회 시 예상시간 및 주문 상태 반환

- src/main/resources/logback-spring.xml
* 코인 프로젝트는 `logs/app.log`에 INFO 레벨 이상의 로그를 찍고 있음
* 하나의 파일에 지속적으로 로그를 찍고 있다보니, 파일의 용량이 커지고 있는 상황
* 2025년 9월 30일 기준 : 스테이지 (약 235MB), 프로덕션 (약 12.37GB)
* 최근 발생하고 있는 EC2 용량 부족 문제 해결과 향후 로그를 확인하는 과정에서 발생할 수 있는 불편함을 해소하기 위해 logback 파일 롤링 도입
- close #2019 
---
* Appender를 `FileAppender`에서 `RollingFileAppender`으로 수정했습니다.
* RollingPolicy의 경우 한 달을 주기로 롤링, 최대 12개까지 보관할 수 있도록 설정했습니다. 
* 롤링된 파일은 `.gz`으로 압축해서 관리됩니다.
---
* Appender : log의 출력 대상과 형식을 설정
* ConsoleAppender : 콘솔에 로그를 출력
* FileAppender : 파일에 로그를 저장
* RollingFileAppender : 여러개의 파일로 순환 저장 (FileAppender 상속)
* SMTPAppender : 로그를 메일로 보낸다.
* DBAppender : DB에 로그를 쌓는다.
* RollingPolicy : 로그 보관 정책
* TimeBasedRollingPolicy : 시간을 기준으로 롤링
* SizeAndTimeBasedRollingPolicy : 시간을 기준으로 롤링하면서 용량 제한 가능
* FixedWindowRollingPolicy : 파일 번호를 붙여 롤링
* 속성 : …
> feat: logback 롤링 도입

- src/main/java/in/koreatech/koin/domain/order/order/controller/OrderApi.java
- src/main/java/in/koreatech/koin/domain/order/order/dto/response/InprogressOrderResponse.java
* 기존에는 shop_id를 반환했으나, orderable_shop_id를 반환하도록 변경함.
- close #2023
---
* 진행 중인 주문 정보 조회(/order/in-progress)의 응답 결과 중 shop_id를 orderable_shop_id로 변경함.
---
* 
---
- [] 테스트 코드 포함됨
> feat: 진행 중인 주문 조회 시 주문 가능한 상점 ID를 응답하도록 변경

- src/main/java/in/koreatech/koin/domain/order/order/controller/OrderApi.java
* order swagger description LAST_6_MONTHS 수정
- close #2029
---
* LAST_6_MONTHS이 3개월로 잘못표기되어있는부분 수정
---
* 
---
> refactor: order swagger description LAST_6_MONTHS 수정
