- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/dto/EmailCheckExistsRequest.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/main/resources/application-test.yml
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- close #17 
1. 이메일의 중복을 체크합니다.
- 중복이면 422 반환
- 잘못된 입력이면 400 반환
1. 파라미터가 `email`이 아닌 `address`인 이유가 있나요?
> feat: 이메일 중복 체크

- build.gradle
- src/main/java/in/koreatech/koin/domain/user/model/User.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/main/java/in/koreatech/koin/global/config/PasswordConfig.java
- src/test/java/in/koreatech/koin/acceptance/AuthApiTest.java
- close #209 
1. 로그인 시 passwordEncoder를 활용하도록 수정했습니다.
회원가입 이어서 구현하겠습니다
> refactor: passwordEncoder 활용하도록 수정

- src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableApi.java
- src/main/java/in/koreatech/koin/domain/timetable/controller/TimetableController.java
- src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableRequest.java
- src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
- src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableUpdateRequest.java
- src/main/java/in/koreatech/koin/domain/timetable/dto/UpdateTimeTableRequest.java
- src/main/java/in/koreatech/koin/domain/timetable/exception/TimeTableNotFoundException.java
- src/main/java/in/koreatech/koin/domain/timetable/model/TimeTable.java
- src/main/java/in/koreatech/koin/domain/timetable/repository/SemesterRepository.java
- src/main/java/in/koreatech/koin/domain/timetable/repository/TimeTableRepository.java
- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- close #28
- close #31
- close #32
- close #33
- close #34
1. 시간표를 생성합니다.
2. 시간표를 삭제합니다.
3. 시간표를 수정합니다.
4. 시간표를 조회합니다.
1. request 이용 방식과 service계층에서 dto를 entity로 변경하는 부분에서 이렇게 하는게 올바른건지 봐주시면 감사하겠습니다.
2. 삭제나 수정부분을 entity를 변경하는 방식으로 했는데 맞게 한 방식인지 애매한것같습니다.
> feat: 시간표 기능 구현

- src/main/java/in/koreatech/koin/domain/user/model/UserType.java
> feat: 영양사 권한 추가

- src/main/java/in/koreatech/koin/domain/timetable/repository/SemesterRepository.java
- src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- close #267 
1. 학기를 최신순으로 반환하게 만들었습니다
2. get semesters 테스트 내용을 추가 작성했습니다
> fix: 학기 최신 순으로 반환

- build.gradle
- close #275 
1. build.gradle에 spring actuator를 추가
로컬에서 잘 확인이 되었다.
2. yaml파일 설정을 통해 자세한 healthcheck가능
build-server에 yaml파일 추가시 자세한 health-check가 가능하다.(disk,mongo,sql,redis등)
코드는 아래와 같다.
_management:
endpoint:
health:
show-details: always_
위와 같이 자세한 healthcheck가 가능해진다
1. up의 healthcheck기능확인
2. 자세한 healthcheck도입여부
> feat: spring actuator 추가

- src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopApi.java
- src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopController.java
- src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
- close #280 
1. 상점 이름을 공백으로하고 상점을 생성할 시 상점의 초성 생성 과정에서 StringIndexOutOfBounds가 발생하는 에러를 수정했습니다.
2. @RequestBody에 @Vaild옵션을 안넣은것을확인하여 추가했습니다.(저의 실수)
좀 더 꼼꼼히 코드를 작성할 필요가 있어보이네요..
> fix: 상점 생성 서버에러(@Valid 추가)

- src/main/java/in/koreatech/koin/domain/user/model/Student.java
- src/main/java/in/koreatech/koin/domain/user/repository/StudentRepository.java
- src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
- close #283 
1. 사용자를 조회할 때 기준이 되는 값을 student테이블의 id에서 User 테이블의 id를 활용하도록 변경했습니다.
-
> refactor: 조회 방식 수정

- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- close #287 
1. logout 시 권한이 학생으로만 제한되어있어 사장님, 영양사에 대한 권한을 추가해줬습니다.
> refactor: 로그아웃, 탈퇴에 대한 권한 수정

- src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
- src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopEventsResponse.java
- src/main/java/in/koreatech/koin/domain/shop/model/EventArticle.java
- src/main/java/in/koreatech/koin/domain/shop/repository/EventArticleRepository.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- close #297 
1. `GET /shops/{shopId}/events` API를 구현했습니다.
@20HyeonsuLee , @johnny19991006 와 몹프로그래밍으로 작업했습니다
테스트 방식을 약간 변경해봤습니다 :)
> feat: 가게 이벤트 정보 조회

- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- src/main/resources/logback-spring.xml
- close #305 
1. logback에 stage추가
2. 백틱에 개행 추가(모바일 가독성 이슈)
> feat: slack 알림 메시지 수정

- src/main/java/in/koreatech/koin/domain/user/dto/StudentResponse.java
- close #303 
1. getGender()의 null 값에 대한 처리 추가
-> ordinal() 사용 시 null 값에 대한 NPE 발생
이런 실수를 ..😢
> fix : userGender null 값 처리 추가

- src/main/java/in/koreatech/koin/domain/land/service/LandService.java
- src/main/java/in/koreatech/koin/domain/member/controller/MemberApi.java
- src/main/java/in/koreatech/koin/domain/member/controller/MemberController.java
- src/main/java/in/koreatech/koin/domain/member/controller/TrackApi.java
- src/main/java/in/koreatech/koin/domain/member/controller/TrackController.java
- src/main/java/in/koreatech/koin/domain/member/dto/MemberResponse.java
- src/main/java/in/koreatech/koin/domain/member/dto/TrackResponse.java
- src/main/java/in/koreatech/koin/domain/member/dto/TrackSingleResponse.java
- src/main/java/in/koreatech/koin/domain/member/exception/MemberNotFoundException.java
- src/main/java/in/koreatech/koin/domain/member/exception/TrackNotFoundException.java
- src/main/java/in/koreatech/koin/domain/member/model/Member.java
- src/main/java/in/koreatech/koin/domain/member/model/TechStack.java
- src/main/java/in/koreatech/koin/domain/member/model/Track.java
- src/main/java/in/koreatech/koin/domain/member/repository/MemberRepository.java
- src/main/java/in/koreatech/koin/domain/member/repository/TechStackRepository.java
- src/main/java/in/koreatech/koin/domain/member/repository/TrackRepository.java
- src/main/java/in/koreatech/koin/domain/member/service/MemberService.java
- src/main/java/in/koreatech/koin/domain/member/service/TrackService.java
- src/test/java/in/koreatech/koin/acceptance/MemberApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TrackApiTest.java
- close #142 
- close #143 
- close #144 
1. BCSDLab 회원 전체조회, 단건조회를 구현했습니다.
잘부탁드려요
> feat: get member

- src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
- src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- src/main/java/in/koreatech/koin/domain/user/model/User.java
- close #312 
1. 특정 상점 전체 메뉴 조회시 없는 상점번호를 조회하면 서버에러가 발생하는 문제를 해결했습니다.
2. 없는 상점 조회시 예외를 던지게 처리했습니다.
짧은 코드 리뷰 잘부탁드립니다~!
> fix: 없는 상점 조회 시 예외 발생

- src/main/java/in/koreatech/koin/domain/owner/model/OwnerAttachment.java
- close #314 
1. 첨부파일 사진 url entity의 연관관계를 수정했습니다.
한줄 리뷰 부탁드립니다.
> fix: 상점 사장님 회원가입 서버에러 수정

- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerRegisterRequest.java
- src/main/java/in/koreatech/koin/domain/owner/model/OwnerAttachment.java
- close #314 
1. owner, attachments의 관계 수정
이번에도 짧은 리뷰 부탁드립니다...
> fix: 상점 사장님 회원가입 에러 수정

- src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
- src/main/java/in/koreatech/koin/global/auth/ExtractAuthenticationInterceptor.java
1.인터셉터에서 Authorization의 token을 검증하고 추출하는 부분에서 문자열 시작 부분 체크를 "Bearer" -> "Bearer "로 수정했습니다.
> Fix: bearerToken 추출 오류 수정

- src/main/java/in/koreatech/koin/domain/ownershop/service/OwnerShopService.java
- src/main/java/in/koreatech/koin/domain/shop/model/Shop.java
- close #318 
1. 사장님 가게 정보 수정 시 delete -> insert라는 순서가 예상대로 실행되지 않는 문제가 있었습니다.
- 이에 수정 시 entityManager를 주입하여 Flush를 수행해줬습니다.
연관관계 머리아프네요
> fix: 사장님 가게정보 수정 오류

- src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
> refactor: 식단 조회 API DTO 필드명 변경

- src/main/java/in/koreatech/koin/global/config/LocalDateTimeAttributeConverter.java
- close #334 
1.회원의 auth_expired_at와 reset_expired_at의 밀리초 파싱 부분에 문제가 발생하여 수정했습니다.
> fix: AttributeConverter 오류 수정

- src/main/java/in/koreatech/koin/domain/user/dto/StudentUpdateResponse.java
- close #356 
1. 작업하며 누락된 userGender Null 처리 추가했습니다.
어디서 병합하면서 누락된 거 같은데, 잘 모르겠네요..
> fix : 삭제된 userGender null 로직 추가

- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/main/java/in/koreatech/koin/global/auth/AuthArgumentResolver.java
- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- close #354 
1. 회원 승인 여부에 대한 검증로직을 추가했습니다.
> fix: isAuthed 검증 추가

- src/main/java/in/koreatech/koin/domain/user/model/UserDeleteEvent.java
- src/main/java/in/koreatech/koin/domain/user/model/UserEventListener.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotificationFactory.java
회원 탈퇴시 해당하는 유저타입을 추가하였습니다.
ex) korea23@koreatech.ac.kr님이 탈퇴하셨습니다. -> korea23@koreatech.ac.kr(학생)님이 탈퇴하셨습니다.
> feat: 회원 탈퇴시 유저타입 추가

- src/main/java/in/koreatech/koin/domain/bus/controller/BusApi.java
- src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
- src/main/java/in/koreatech/koin/domain/bus/dto/BusCourseResponse.java
- src/main/java/in/koreatech/koin/domain/bus/repository/BusRepository.java
- src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
- src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
- close #100 
1. 버스의 모든 경로 조회 기능을 구현했습니다.
> feat : 버스 코스 조회 구현

- src/main/java/in/koreatech/koin/global/exception/ErrorResponse.java
- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- close #373 
1. 예외 발생 시 예외 메시지, 코드, 시간을 반환해주도록 반환 포맷을 수정했습니다.
> refactor: 예외형태 수정

- src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
- close #376 
1. 잘못 작성된 namedQuery 수정했습니다
지난 PR 에서
- https://github.com/BCSDLab/KOIN_API_V2/pull/367/files
namedQuery를 잘못 수정했었네요 죄송합니다.
> fix: Repository Named Query수정

- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
1. 비밀번호가 틀렸을 때 반환하는 메시지를 간소화했습니다.
> refactor: 비밀번호가 틀렸을 때 반환하는 메시지 간략화

- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- close #396 
1. 권한을 확인하는 로직을 추가했습니다.
> fix: 로그인에 권한 확인 로직 추가

- src/main/java/in/koreatech/koin/domain/user/service/StudentService.java
- close #390 
1. 정보 수정간 사용하던 본인 닉네임에 중복(409)이 발생하던 점에 대해 예외처리 구문에 오류가 발생하지 않도록 수정했습니다. 
잘 부탁드립니당
> feat : PUT user/student/me 현재 사용 닉네임 처리 로직 추가

- src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusTimetable.java
> feat : depart json 네이밍 변경

- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/test/java/in/koreatech/koin/acceptance/AuthApiTest.java
- close #398
1. 상태코드 200에서 201로 변경했습니다.
> fix: POST/user/refresh 반환코드 수정

- src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopsResponse.java
스웨거에는 예시가 이상하게 잡혀있어서 테스트할 때 당황했습니다.
원래 브랜치를 판 목적과 다른 PR이다보니 브랜치명을 신경못썼네요;; 다음부터는 꼭 확인하겠습니다
> refactor: 스웨거 DTO 예시 수정

- src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopMenuResponse.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopResponse.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopsResponse.java
- close #418 
1. Menu, Shop쪽 dto예시를 적절히 변경했습니다!
dto예시 작성을 꼼꼼히 해야겠다는 생각이 들었습니다
> chore: dto 예시 및 설명 추가

- src/main/resources/db/migration/V12__alter_menu_categories_update_category_name.sql
- close #422
1. flyway를 이용해 기존 db에 존재하던 데이터를 수정했습니다.
2. 이벤트 메뉴 -> 추천 메뉴 / 대표 메뉴 -> 메인 메뉴
카테고리 이름 변경하기로 했을때 같이 진행했어야 하는 작업인데 늦어졌네요 ..ㅠ
> feat: 메뉴 카테고리 이름 기획에 맞게 수정

- src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
- close #426 
1. 품절 알림 문구를 수정하였습니다.
- {A}코너가 품절되었습니다.
- 다른 코너 보러 가기.
> fix : 품절 알림 문구 수정

- src/main/java/in/koreatech/koin/domain/admin/land/controller/AdminLandApi.java
- src/main/java/in/koreatech/koin/domain/admin/land/controller/AdminLandController.java
- src/main/java/in/koreatech/koin/domain/admin/land/dto/AdminLandResponse.java
- src/main/java/in/koreatech/koin/domain/admin/land/dto/AdminLandsResponse.java
- src/main/java/in/koreatech/koin/domain/admin/land/repository/AdminLandRepository.java
- src/main/java/in/koreatech/koin/domain/admin/land/service/AdminLandService.java
- src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
- src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
- src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
- src/main/java/in/koreatech/koin/global/model/Criteria.java
- src/test/java/in/koreatech/koin/acceptance/AdminLandApiTest.java
- close #10 
1. GET /admin/lands 마이그레이션 작업 진행하였습니다.
2. domain.community의 Criteria 클래스를 같이 사용하기 위해 global.model 패키지로 클래스 이동 후 일부 메서드 오버로딩하여 작업 진행하였습니다.
첫 PR 올려봅니다. 테스트코드와 java17에 익숙하지 않아 실수나 놓치는 부분이 많을것이라 예상되는데, 잘 부탁드립니다!
> feat: GET /admin/lands 기능 구현

- src/main/java/in/koreatech/koin/domain/timetable/dto/TimeTableResponse.java
- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- close #439
1. 해당 학기 총 학점 조회
2.  전체 학기 총 학점 조회
> feat: 시간표 총 학점 조회

- src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
- close #456 
1. 시간표를 불러올때 캐시확인로직이 version 테이블의 updated_at을 비교하고 있었습니다
2. 레디스에 키가 존재하는지 확인하는 방식으로 변경했습니다
제발!!
> fix: 시외버스 시간표 캐시확인로직 변경

- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerVerifyRequest.java
- src/main/java/in/koreatech/koin/domain/owner/dto/VerifyPhoneRequest.java
> refactor: dto 수정

- src/main/java/in/koreatech/koin/domain/land/dto/LandResponse.java
- src/main/java/in/koreatech/koin/domain/land/dto/LandsGroupResponse.java
- src/main/java/in/koreatech/koin/domain/land/dto/LandsResponse.java
- src/main/java/in/koreatech/koin/domain/land/model/Land.java
- src/test/java/in/koreatech/koin/acceptance/LandApiTest.java
- close #465 
1. String으로 반환되는 좌표값을 Double로 수정했습니다.
> fix: land dto 자료형 수정

- src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
- src/main/java/in/koreatech/koin/domain/owner/model/OwnerPhoneRequestEvent.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerService.java
- src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotificationFactory.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- close #472 
1. 상점 사장님 문자 인증 발송 시 slack에 알림을 발송하도록 하였습니다.
2. 호환성을 위해 phone을 위한 EventListener를 별도로 작성하였습니다.
리뷰 잘부탁드립니다!
> feat: 상점 사장님 문자인증 발송 시 slack알림 발송

- src/main/java/in/koreatech/koin/domain/user/repository/UserTokenRepository.java
- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- close #488 
1. 표준예외 핸들링 추가
2. IAE -> KoinIAE로 변경
> fix: handler 추가 및 IAE 변경

- Dockerfile
> fix: timezone 설정

- src/main/java/in/koreatech/koin/domain/bus/dto/BusTimetableResponse.java
- src/main/java/in/koreatech/koin/domain/bus/model/SchoolBusTimetable.java
- src/main/java/in/koreatech/koin/domain/bus/model/city/CityBusCache.java
- src/main/java/in/koreatech/koin/domain/bus/model/express/ExpressBusCache.java
- src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
- src/main/java/in/koreatech/koin/domain/bus/util/BusScheduler.java
- src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
- src/main/java/in/koreatech/koin/domain/bus/util/ExpressBusOpenApiClient.java
- src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
1. main 브랜치에 머지된 내용 develop에도 반영하기 위해 PR 올렸습니다.
> hotfix: 버스 API 응답시간 개선 및 응답 스키마 불일치 해결(develop)

- src/main/java/in/koreatech/koin/admin/land/controller/AdminLandApi.java
- src/main/java/in/koreatech/koin/admin/land/controller/AdminLandController.java
- src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsRequest.java
- src/main/java/in/koreatech/koin/admin/land/execption/LandNameDuplicationException.java
- src/main/java/in/koreatech/koin/admin/land/repository/AdminLandRepository.java
- src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
- src/main/java/in/koreatech/koin/domain/land/model/Land.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
- src/test/java/in/koreatech/koin/fixture/LandFixture.java
- close #11 
1.어드민API에서 복덕방 수정하는 API작성하였습니다.
물론 어려운 로직은 아닙니다만 첫 코드pr이니 꼼꼼히 체크 부탁드립니다
> Feat: 어드민 복덕방 생성 API

- src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationSubscribe.java
- src/main/resources/db/migration/V14__alter_notification_subscribe_unique.sql
- close #이슈번호
1. notification_subscribe에 복합 unique(user_id, subscribe_type, detail_type)를 추가했습니다.
> fix : notification_subscrdibe 복합 unique 추가

- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/resources/db/migration/V15__delete_notification_subscribe.sql
> develop to main

- src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- src/main/resources/logback-spring.xml
- close #516 
1. 상점, 상점메뉴 생성, 수정 시 카테고리 개수 최소검증 추가
2. GlobalExceptionHandler 인자 잘못 선언되어있는것 수정
3. DateParseException 좀더 상위 예외 잡도록 수정
4. slack 메시지의 [Stage] 제거
메시지 포맷 변경 위주의 PR입니다 :)
> fix: 에러 반환값 수정

- src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- src/main/resources/db/migration/V15__delete_notification_subscribe.sql
- src/main/resources/logback-spring.xml
> develop -> main

- src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
- src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- src/main/resources/db/migration/V15__delete_notification_subscribe.sql
- src/main/resources/logback-spring.xml
> hotfix: 시내버스 스케줄 빈값이 올 경우 빈배열 반환

- src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
- src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/global/exception/GlobalExceptionHandler.java
- src/main/resources/db/migration/V15__delete_notification_subscribe.sql
- src/main/resources/logback-spring.xml
- close #이슈번호
1. json을 바꾸는 과정에서 예외가 생기는 것 같습니다
> fix: 시내버스 getAsString() 오류로 인한 삭제 

- src/main/java/in/koreatech/koin/domain/bus/util/CityBusOpenApiClient.java
- close #이슈번호
1. 디벨롭에 적용이 되지 않아 다시 pr 날립니다..!
> fix: json getAsString 오류로 인한 삭제

- src/main/java/in/koreatech/koin/domain/user/dto/StudentRegisterRequest.java
1. 학생 회원가입 시에 전화번호 정규식 패턴을 추가로 허용해줬습니다.
브랜치 명 오타나서 수정 했는데 pr이 취소 되는지는 몰랐네요..
추가로 놓친 부분 있으면 말씀해주시면 감사하겠습니다
> hotfix: 학생 회원 가입 시에 전화번호 형식 추가 허용

- Dockerfile
- close #이슈번호
컨테이너 안에서의 정밀한 측정을 위해 데이터독 APM 추가
> feat: 데이터독 APM설정 추가

- src/main/java/in/koreatech/koin/domain/bus/util/BusScheduler.java
- close #이슈번호
1. @Scheduled와 @Transactional을 같이 사용하면 생기는 문제 같습니다
2. @Scheduled 쪽에서 try-catch를 추가했습니다. 
https://joychae.tistory.com/35
> 버스 openApi 에러 수정

- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberApi.java
- src/main/java/in/koreatech/koin/admin/member/controller/AdminMemberController.java
- src/main/java/in/koreatech/koin/admin/member/dto/AdminMemberResponse.java
- src/main/java/in/koreatech/koin/admin/member/repository/AdminMemberRepository.java
- src/main/java/in/koreatech/koin/admin/member/service/AdminMemberService.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminMemberApiTest.java
- close #47 
1. GET /admin/members/{id} API 추가하였습니다.
단순 조회 기능으로 크게 고민한 개발 내용은 없습니다. 자잘한 수정사항들(Swagger 관련, JWT 관련) 추가하여 리뷰 요청 드립니다.
> feat: GET /admin/members/{id} api 추가

- Dockerfile
- close #이슈번호
1. 도커 이미지가 무거워져서 jdk를 alpine으로 변경하였습니다
2. 로컬 및 스테이지 환경에서 테스트를 완료하였습니다
> Refactor : 도커 이미지 크기 간소화

- src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
- src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
- close #587 
1. 상점 오픈 시간을 일주일 모두 받도록 수정하였습니다.
> fix: dto @NotNull 어노테이션 추가

- src/main/java/in/koreatech/koin/global/domain/notification/model/NotificationFactory.java
- close #이슈번호
1. 품절 알림 문구에서 마지막 점을 삭제했습니다.
> fix : 품절 알림 문구 점(.) 삭제

- src/main/java/in/koreatech/koin/admin/land/controller/AdminLandApi.java
- src/main/java/in/koreatech/koin/admin/land/controller/AdminLandController.java
- src/main/java/in/koreatech/koin/admin/land/repository/AdminLandRepository.java
- src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
- src/main/java/in/koreatech/koin/domain/land/model/Land.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminLandApiTest.java
- close #12 
1. 어드민 복덕방 삭제 API를 구현하였습니다.
2. 테스트 코드 및 로컬스웨거로 테스트를 완료하였습니다
> Feature: 어드민 복덕방 삭제

- src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
- src/main/java/in/koreatech/koin/domain/owner/dto/OwnerRegisterRequest.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- close #613 
1. 호환성을 유지하기 위해서 오너 회원가입 휴대폰번호 양식을 롤백하였습니다.
작업할 때 기존 api는 건들이지 말았어야하는데 능지이슈로 건들여버렸네요...ㅠ 다시 롤백합니다!
> refactor: 호환성 유지하기 위한 오너 회원가입 휴대폰번호 양식 롤백

- src/main/resources/db/migration/V19__update_coop_id_and_change_not_null.sql
- src/main/resources/db/migration/V19__update_coop_id_with_user_email.sql
- src/main/resources/db/migration/V20__alter_coop_id_column_not_null.sql
- close #617 
1. coop 테이블의 coop_id 값에 NOT NULL 처리 및 user_id 기준 email 값이 들어가도록 했습니다.
앞 timetable flyway 추가 때문에 어떻게 할까 헀는데, 빠르게 선행 가능 할 작업 같아서 번호를 땡겼습니다.
> feat : coop_id 관련 flyway 추가

- src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerShopController.java
- src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyShopRequest.java
- src/main/java/in/koreatech/koin/global/validation/DayOfWeekValidator.java
- src/main/java/in/koreatech/koin/global/validation/ValidDayOfWeek.java
- close #623 
1. 운영 요일 형식을 검증하는 커스텀 어노테이션을 작성했습니다
2. InnerRecord에 @Valid어노테이션을 추가했습니다.
> fix: 상점 수정, 삭제시 운영 요일 형식 검증

- src/main/resources/db/migration/V26__alter_timetable_lecture_timetable_id.sql
- close #647 
1. flyway 26번을 수정했습니다.(timetable_id -> frame_id)
시간표 api를 추가하며 수정한 부분이 적용되지 않아서 오류가 발생했습니다.
협업하는 과정에서 오류가 생긴 부분을 빠르게 캐치하지 못 했네요.. 오류 펑펑 터져서 죄송합니당
> fix : flyway 오류 수정

- src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminUserApiTest.java
1. main<-develop 충돌 해결
develop에서 새 브랜치 따와서 origin main pull땡겨와서 충돌 해결했는데 잘 될지는 미지수네요
> main<-develop 충돌 해결

- src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
- close #685 
1. TimeTableResponse의 schema 이름을 수정해봤습니다.
지푸라기 잡는 심정으로 하나씩 수정해보겠습니다
> fix : Timetable Response 값 수정

- src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
- src/main/java/in/koreatech/koin/domain/timetable/dto/TimetableResponse.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
1. 복구 시키고 Lecture Response에서 id를 삭제해봤습니다.
잘 부탁드립니다
> fix : timetableResponse 복구 및 LectureResponse Lecture id 삭제

- src/main/java/in/koreatech/koin/domain/timetable/dto/LectureResponse.java
- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
- src/main/java/in/koreatech/koin/domain/timetableV2/repository/LectureRepositoryV2.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
1. Lecture/Semester V2 Repository를 사용했습니다.
잘 부탁드립니다
> chore : Repository 수정 및 수정 코드 복구

- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
1. 기존 레거시 코인에서 전에 추가한 강의 정보가 없는 사용자가 학기를 조회시 자동으로 frame이 생성되게 로직을 변경했습니다.
> feat: 조회시 프레임 없으면 생성

- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
1. 시간표 생성시 전체를 반환하는 것으로 수정했습니다.
신경써주신 모든 분들 정말 감사합니다ㅠ
> feat: 시간표 생성시 전체 반환

- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
1. readonly = true로 인해 저장이 잘 안되고 있어서 transactional 어노테이션과 레포에 저장 하는 로직을 추가했습니다
> hotfix: getTimetables 메서드에서 TimetableFrame 저장 에러 수정

- src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
- close #692 
Redis의 shopId로부터 mysql의 Shop 데이터를 갖고오는 로직에서, mysql에 shopId가 없을때 404에러를 반환하여 페이지가 뜨지 않고 있습니다. 그래서 mysql에 해당하는 shopId 없을땐 null로 반환하게 로직 수정하였습니다.
> fix: 인증 요청 사장님 페이지네이션

- src/main/java/in/koreatech/koin/domain/coopshop/model/CoopOpen.java
- close #이슈번호
1. CoopShop 조회 시 모든 CoopOpen이 조회되도록 `Lazy`에서 `Eager`로 수정하였습니다.
> fix : CoopShop 조회 시 CoopOpen 즉시로딩 수정

- src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
- src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
- src/main/java/in/koreatech/koin/domain/dining/dto/DiningLikeRequest.java
- src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
- src/main/java/in/koreatech/koin/domain/dining/exception/DuplicateLikeException.java
- src/main/java/in/koreatech/koin/domain/dining/exception/LikeNotFoundException.java
- src/main/java/in/koreatech/koin/domain/dining/model/Dining.java
- src/main/java/in/koreatech/koin/domain/dining/model/DiningLikes.java
- src/main/java/in/koreatech/koin/domain/dining/repository/DiningLikesRepository.java
- src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
- src/main/resources/db/migration/V33_add_dining_like_table.sql
- src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
- src/test/java/in/koreatech/koin/fixture/DiningFixture.java
- close #715 
1. 식단 좋아요 기능을 구현했습니다
2. 식단 좋아요 취소 기능을 구현했습니다
3. 식단을 불러올때 `likes`를 같이 불러오도록 해줬습니다
flyway가 헷갈리는데 저거 맞나 봐주세요ㅠㅠ
> feat: 식단 좋아요/취소 기능 구현 

- src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
- src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
- src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
- src/main/resources/db/migration/V33_add_dining_like_table.sql
- src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
- close #715 
1. 인증이 안된다는 문제를 깨달아 @Auth 로 헤더에 토큰을 받아오게 했습니다
제발 돼라!
> fix: 식단 좋아요 사용자 인증 추가

- src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
- src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
- src/main/java/in/koreatech/koin/domain/dining/dto/DiningResponse.java
- src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
- src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
- close #719 
1. 식단을 불러올때 사용자의 토큰을 받아 좋아요 여부를 같이 불러오는 작업을 진행했습니다
> feat: 좋아요 여부 판단 isLiked 추가

- .github/SCRIPT/check_flyway_version.py
- .github/workflows/flyway-check.yml
- src/main/resources/db/migration/V37__shop_review_menus_restrict_change_cascadeㅇㄴㅁㅇㅁㄴ_.sql
- close #723 
1. flyway 충돌 확인을 위한  workflow yml, 파이썬 스크립트 추가
> feat: flyway버전 충돌 확인

- src/main/java/in/koreatech/koin/domain/shop/controller/ShopApi.java
- src/main/java/in/koreatech/koin/domain/shop/controller/ShopController.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewResponse.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ShopReviewsResponse.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopReviewService.java
- src/test/java/in/koreatech/koin/acceptance/ShopReviewApiTest.java
- close #752 
1. 단일 리뷰를 조회하는 API를 작성했습니다.
> feat: 단일 리뷰 조회 API작성

- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
- close #777
1. 기존 api로 커스텀 시간표를 가져오려 할때 발생한 에러로 null 처리를 해줬습니다.
2. 라인 포맷팅 해줬습니다.
> fix: timetable에 null 처리 로직 추가

- src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
- src/main/java/in/koreatech/koin/domain/coopshop/service/CoopShopService.java
- close #
1. DB에 있는 운영시간 기준으로 하면 이미지 업로드 알림이 안올것 같아서 1시간전까지 인정하도록 바꿨습니다
> feat: 식단 이미지 업로드 알림 운영시간 오픈시간 1시간전까지 운영

- src/main/resources/db/migration/V43__drop_unused_tables_and_column.sql
- close #772
1. 안쓰는 테이블, 컬럼을 삭제하는 flyway버전을 추가했습니다.
2. 사용하지 않고 있는 테이블을 전부 삭제하도록 하였는데 혹시나 사용중인게 있다면 말씀해주세요.
> feat: 안쓰는 테이블, 컬럼 삭제

- src/main/java/in/koreatech/koin/domain/shop/dto/CreateCategoryRequest.java
> develop 머지시 젠킨스 빌드되는 웹훅 테스트

- src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
- src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
> refactor: api path 변경

- src/main/java/in/koreatech/koin/domain/community/model/ArticleKeyword.java
1. last used at을 db상으로 timestamp를 타입으로 했는데 varchar를 기대한다는 에러가 나서 엔티티상에 타입을 명시해줬습니다.
> fix: last used at 엔티티 상에 타입 명시

- src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
- src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
> deploy: api path 변경사항 롤백

- src/main/java/in/koreatech/koin/domain/community/controller/CommunityApi.java
- src/main/java/in/koreatech/koin/domain/community/controller/CommunityController.java
- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
> rollback: api path rollback

- src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/repository/BoardRepository.java
- src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
- src/test/java/in/koreatech/koin/acceptance/CommunityApiTest.java
1. `boardRepository`와 `articleRepository`를 헷갈려서 페이징이 적용되지 않는 버그가 있어 수정했습니다.
> hotfix: 게시판 페이징 미적용 버그 수정

- src/main/java/in/koreatech/koin/admin/land/dto/AdminLandsResponse.java
- src/main/java/in/koreatech/koin/domain/dining/controller/DiningApi.java
- src/main/java/in/koreatech/koin/domain/dining/controller/DiningController.java
- src/main/java/in/koreatech/koin/domain/dining/dto/DiningSearchResponse.java
- src/main/java/in/koreatech/koin/domain/dining/model/DiningPlace.java
- src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
- src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
- src/test/java/in/koreatech/koin/acceptance/DiningApiTest.java
- src/test/java/in/koreatech/koin/fixture/DiningFixture.java
- close #555 
1. 영양사 월간 조회에서 검색 기능을 구현했습니다
2. 필터링 다중 선택이 가능하도록 만들었습니다
3. 현재 날짜로부터 최근 1년 내의 결과만 가져오도록 해줬습니다
- 이상한 부분 있으면 말해주세용
> feat: 영양사 월간 조회 검색 기능 구현

- src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopReviewReportStatusRequest.java
- src/main/java/in/koreatech/koin/domain/timetable/dto/SemesterCheckResponse.java
- src/main/java/in/koreatech/koin/domain/timetable/service/SemesterService.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/TimetableLectureUpdateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
> 비즈니스팀 요류수정 배포 develop → main

- src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateMenuRequest.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminCreateShopRequest.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyMenuRequest.java
- src/main/java/in/koreatech/koin/admin/shop/dto/AdminModifyShopRequest.java
- src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopsRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/CreateMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/dto/ModifyMenuRequest.java
- src/main/java/in/koreatech/koin/domain/shop/exception/MenuIllegalSingleException.java
- src/main/java/in/koreatech/koin/global/validation/SingleMenuPrice.java
- src/main/java/in/koreatech/koin/global/validation/SingleMenuPriceValidator.java
- src/test/java/in/koreatech/koin/acceptance/OwnerShopApiTest.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminShopApiTest.java
- close #815 
- close #822 
1. admin권한으로 shop 생성 및 수정 시 오류 해결
2. 단일 메뉴 검증 오류 해결
3. 테스트 수정
옛날에 코드 작성할때 실수했던것같네요. 실수를 줄여나가도록하겠습니다.
> fix: vaild 처리 안되는 오류 해결

- src/main/java/in/koreatech/koin/domain/community/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/service/CommunityService.java
[슬랙 메시지 링크](https://bcsdlab.slack.com/archives/C06NQT2TY9X/p1724928654438559?thread_ts=1724906852.374389&cid=C06NQT2TY9X)
지난번에 정규화를 위해 게시글 조인을 넣었으나 쿼리 속도가 너무 안좋아져서 롤백합니다.
> rollback: 성능 향상을 위해 게시글 조인 쿼리 제거

- src/main/java/in/koreatech/koin/domain/community/model/Article.java
- src/main/java/in/koreatech/koin/global/config/LocalDateAttributeConverter.java
- close #834 
1. `VARCHAR(255)`를 LocalDate로 Converter 추가
> fix: LocalDate 컨버터 추가

- src/main/java/in/koreatech/koin/domain/community/model/Article.java
> fix: column definition 추가

- src/main/java/in/koreatech/koin/global/config/LocalDateAttributeConverter.java
> fix: fomatter 수정

- src/main/resources/db/migration/V49__update_article_is_notice.sql
- close #839 
1. koreatech_articles 테이블에 is_notice 컬럼 데이터 수정
찐찐막
> fix: is_notice 업데이트 flyway 추가

- src/main/java/in/koreatech/koin/domain/community/model/Article.java
- src/main/java/in/koreatech/koin/global/config/LocalDateAttributeConverter.java
- close #841 
1. 과거 데이터 포맷 불일치 문제 수정
> fix: LocalDateAttributeConverter 포맷 추가

- src/main/java/in/koreatech/koin/domain/community/article/service/CommunityService.java
- close #845 
1. `registeredAt` 기준 정렬로 수정
> fix: registeredAt 기준 정렬 수정

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/resources/db/migration/V54__create_index_registered_at_and_id.sql
- close #858 
1. 게시글 조회 속도 최적화를 위한 인덱스 추가
> refactor: 게시글 조회 속도 최적화

- src/main/resources/logback-spring.xml
- close #이슈번호
1. datadog 로깅을 위해 logback을 수정하였습니다.
> feat : datadog 로깅을 위한 logback 수정

- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
> fix: 쿼리 버그 수정

- src/main/java/in/koreatech/koin/domain/dining/repository/DiningRepository.java
- src/main/java/in/koreatech/koin/domain/dining/service/DiningService.java
- close #이슈번호
1. 기존에 1년 이내의 식단만 검색했는데 요청이 있어 전체 식단 검색으로 변경합니다. 
단 3줄!
> feat: 식단 검색 1년 -> 전체기간으로 변경

- src/main/java/in/koreatech/koin/domain/version/model/Version.java
- src/main/resources/db/migration/V63__alter_table_versions_alter_column_is_previous.sql
- close #이슈번호
1. boolean 값 매핑을 위해 is_previous 자료형을 수정하였습니다.
> fix : version 테이블의 is_previous 컬럼 자료형 수정

- src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitApi.java
- src/main/java/in/koreatech/koin/admin/benefit/controller/AdminBenefitController.java
- close #991
1. 오랜만의 어드민 작업이라 admin 제한을 실수를 수정했습니다.
> fix: 혜택카테고리 및 혜택상점 어드민 제한

- src/main/java/in/koreatech/koin/global/fcm/FcmClient.java
- close #914 
1. 상세페이지 이동을 위해 ios가 받는fcm에 schemeUri를 추가했습니다. 향후 작업 간 참고해주시면 감사하겠습니다.
fcm을 보냄에 있어 놓친 부분이 있다면 말씀해주시면 감사하겠습니다.
> refactor: ios가 받는 fcm에 schemeUri 추가

- src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopsResponseV2.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- close #917
1. 모든 상점 조회 V2의 opens필드 제거
> feat: 모든 상점 조회 opens필드 제거

- src/main/resources/logback-spring.xml
- close #이슈번호
1. Error 발생 시 slack 으로 알림을 발송합니다.
> refactor: slack 알림발송 추가

- src/main/resources/db/migration/V78__update_article_attachments_uk.sql
Reverts BCSDLab/KOIN_API_V2#952
> Revert "fix: 공지사항 첨부파일 유니크 키 추가"

- src/main/resources/db/migration/V80__delete_duplicate_article_attachments.sql
- src/main/resources/db/migration/V81__update_article_attachments_uk.sql
- close #951 
1. 저번에 중복 데이터로 인해 실패했던 flyway입니다.
2. 키 추가하기 전에 중복 데이터를 제거하는 flyway를 추가했습니다.
> Fix: 게시글 첨부파일 복합 키 추가 2차전

- src/main/java/in/koreatech/koin/domain/community/article/dto/ArticleResponse.java
- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- close #979 
1. response에 url 추가
- 코인 공지는, null 반환
> feat: 공지사항 바로가기 url Response 추가

- src/main/resources/db/migration/V93__add_menu_search_keyword_table.sql
- close #1011 
1. flyway V93 버전 충돌을 해결했습니다.
> fix: flyway 버전 충돌 해결

- src/main/java/in/koreatech/koin/domain/shop/dto/shop/ShopsSortCriteria.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- close #1022
1. 주변상점에서 내림차순으로도 정렬할수있게 수정했습니다.
> feat: 주변상점 내림/오름차순 정렬 기능 추가

- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleApi.java
- src/main/java/in/koreatech/koin/domain/community/article/controller/ArticleController.java
- src/main/java/in/koreatech/koin/domain/community/article/model/redis/ArticleHitUser.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/redis/ArticleHitUserRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
게시글 조회 시 ip 당 1시간에 1번만 조회수가 오르도록 수정했습니다.
> feat: 게시글 조회수 증가 제한 로직 추가

- .github/workflows/flyway-check.yml
- close #1054
1. flyway 충돌 감지 복구
> chore: flyway 충돌 감지 복구

- src/main/resources/db/migration/V18__alter_user_email_column_nullable.sql
- src/main/resources/db/migration/V1__init.sql
- close #1057
1. flyway version checksum에러를 해결했습니다.
> fix: flyway version checksum문제 해결

- src/main/java/in/koreatech/koin/domain/shop/dto/shop/response/ShopsResponseV2.java
- src/test/java/in/koreatech/koin/acceptance/ShopApiTest.java
- close #1062
1. 모든 상점 조회 V2 API의 opens필드를 추가했습니다!
> feat: 모든 상점 조회 v2 opens 필드 추가

- src/main/java/in/koreatech/koin/domain/timetable/model/Lecture.java
- src/main/java/in/koreatech/koin/domain/timetable/model/Semester.java
- src/main/java/in/koreatech/koin/domain/timetable/repository/LectureRepository.java
- src/main/java/in/koreatech/koin/domain/timetable/service/TimetableService.java
- src/main/java/in/koreatech/koin/domain/timetableV2/repository/LectureRepositoryV2.java
- src/main/resources/db/migration/V104__alter_lecture_class_time.sql
- src/main/resources/db/migration/V105__add_semester_id_column.sql
- src/main/resources/db/migration/V106__update_semester_id.sql
- src/main/resources/db/migration/V107__alter_fk_lectures_on_semester.sql
- src/test/java/in/koreatech/koin/acceptance/TimetableApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TimetableFrameApiTest.java
- src/test/java/in/koreatech/koin/acceptance/TimetableLectureApiTest.java
- src/test/java/in/koreatech/koin/fixture/LectureFixture.java
- close #1113 
해당 [PR](https://github.com/BCSDLab/KOIN_API_V2/pull/1065)에서 행했던 작업을 롤백했습니다.
- flyway를 삭제했습니다. (104 ~ 107)
- 연관관계를 삭제했습니다. (lecture과 semester의 관계)
- 테스트 코드를 수정했습니다. (이전 코드로 롤백)
> fix: 데이터베이스 롤백을 위한 작업 삭제

- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- close #이슈번호
1. 버스 긴급공지 조회 테이블을 수정하였습니다.
- koreatech_articles -> new_articles
> fix : 버스 긴급공지 조회 테이블 수정(koreatech_articles -> new_articles)

- .github/workflows/reviewer.json
- close #1161 
- reviewer.json을 최신화 했습니다.
> docs: reviewer.json 최신화

- src/main/java/in/koreatech/koin/global/config/swagger/SwaggerGroupConfig.java
- close #1188 
- 스웨거 그룹화 과정에서 미포함된 api를 그룹화했습니다.
- 관련해서 bcsd api 그룹에 포함시켰습니다.
> feat: 미포함 API 스웨거 그룹화

- gradle.properties
> feat: gradle cache 활성화

- src/main/java/in/koreatech/koin/domain/graduation/model/Catalog.java
- src/main/java/in/koreatech/koin/domain/graduation/model/CourseType.java
- src/main/java/in/koreatech/koin/domain/graduation/model/GeneralEducationAreaCourseTypeMap.java
- src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
- src/main/resources/db/migration/V111__add_course_type.sql
- src/main/resources/db/migration/V118__add_catalog.sql
- src/main/resources/db/migration/V122__alter_fk_general_education_area_id_on_timetable.sql
- src/main/resources/db/migration/V123__add_general_education_area_course_type_map.sql
- general_education_area_id와 course_type_id가 연관된 테이블 추가했습니다.
- catalog 테이블에서 general_education_area_id 제거했습니다.
- timetable_lecture에 general_education_area_id 추가했습니다.
- course_type 테이블에 year 추가했습니다.
> fix: 졸업학점 계산기 관련 flyway 수정

- src/main/java/in/koreatech/koin/domain/bus/controller/BusController.java
- src/main/java/in/koreatech/koin/domain/bus/service/BusService.java
- src/main/java/in/koreatech/koin/domain/bus/service/CityBusService.java
- src/main/java/in/koreatech/koin/domain/bus/service/ExpressBusService.java
- src/main/java/in/koreatech/koin/domain/bus/service/ShuttleBusService.java
- src/main/java/in/koreatech/koin/domain/bus/util/BusCacheScheduler.java
- src/main/java/in/koreatech/koin/domain/bus/util/BusCacheService.java
- src/main/java/in/koreatech/koin/domain/bus/util/converter/BusStationEnumConverter.java
- src/main/java/in/koreatech/koin/domain/bus/util/converter/BusTypeEnumConverter.java
- src/main/java/in/koreatech/koin/global/config/WebConfig.java
- src/test/java/in/koreatech/koin/acceptance/BusApiTest.java
- close #이슈번호
- `ShuttleBusService` 를 `BusService` 분리
- `CityBusService` 를 만들기
- `ExpressBusService` 내에 있는 `storeRemainTimeByRatio` 분리
- `BusCacheService` 하나 만들어서 분리
- `BusScheduler` → `BusCacheSceduler` 로 네이밍 변경
> Refactor : 버스 리팩토링 

- src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
> fix: 영양사 이미지 압축 다운로드 생략 기준 변경

- src/main/java/in/koreatech/koin/admin/user/enums/TrackType.java
- src/main/java/in/koreatech/koin/admin/user/model/Admin.java
- src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
- close #1230 
- TrackType enum에 보안 트랙을 추가했습니다.
- 겸사겸사 어드민 리펙토링 진행했습니다.
> feat: TrackType enum에 보안 트랙 추가

- src/main/java/in/koreatech/koin/domain/graduation/model/Catalog.java
- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- close #1140 
1. 관련 로직에 대한 간단한 주석 몇 개 추가했습니다.
2. 코드 리팩토링 조금 진행했습니다.
간단한 사항이랑 엔티티 수정 부분 조금 있습니다.
괜찮은 지 한 번만 봐주세여
> rafactor & docs : 엑셀 관련 로직 설명 추가 및 리팩토링

- src/main/java/in/koreatech/koin/domain/bus/service/model/route/ShuttleBusRouteStrategy.java
- src/main/java/in/koreatech/koin/domain/bus/service/shuttle/ShuttleBusRepository.java
- src/main/java/in/koreatech/koin/domain/bus/service/shuttle/model/ShuttleBusRoute.java
- src/main/java/in/koreatech/koin/domain/bus/service/shuttle/model/ShuttleBusSimpleRoute.java
- close #1236
1. 가장 빠른 교통편 조회 db 의존성 변경
`bus_timetables -> shuttlebus_timetables`
``` mermaid
sequenceDiagram
participant BusRouteCommand
participant ShuttleBusRouteStrategy
participant VersionRepository
participant ShuttleBusRepository
participant ScheduleInfo
BusRouteCommand->>ShuttleBusRouteStrategy: findSchedule(command)
ShuttleBusRouteStrategy->>VersionRepository: getByTypeAndIsPrevious(SHUTTLE, false)
VersionRepository-->>ShuttleBusRouteStrategy: Version (semesterType)
ShuttleBusRouteStrategy->>ShuttleBusRouteStrategy: convertDateToDayOfWeek(command)
ShuttleBusRouteStrategy-->>ShuttleBusRouteStrategy: dayOfWeek
ShuttleBusRouteStrategy->>ShuttleBusRepository: findBySemesterType(semesterType, dayOfWeek)
ShuttleBusRepository-->>ShuttleBusRouteStrategy: List<ShuttleBusSimpleRoute>
loop …
```
> refactor: 가장 빠른 교통편 조회 DB 의존성 변경

- src/main/java/in/koreatech/koin/domain/owner/dto/sms/OwnerRegisterByPhoneRequest.java
- src/main/java/in/koreatech/koin/domain/owner/model/OwnerShop.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerEmailService.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerSmsService.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerUtilService.java
- src/main/java/in/koreatech/koin/domain/shop/repository/shop/ShopRepository.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- close #1242
- 요청 시 상점이름 필수로 변경
- 요청 시 상점 전화번호 필드 추가 및 필수로 설정
- 가게번호가 010-4192-1174의 형태와 051-555-5555형태 모두 가능하므로 10자리, 11자리 모두 가능하도록 함
- 회원가입 시 redis에 저장되는 정보에 가게번호, 가게명 추가 및 ttl 2시간에서 24시간으로 변경
> feat: 사장님 회원가입 요청 시 가게 전화번호 관련 추가

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- close #이슈번호
1. articles의 author가 null일 경우 '익명'으로 표시되도록 수정했습니다.
> refactor: articles의 author 필드 값 null 대체

- src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
- src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- close #1266 
1. body값이 있으나, GetMapping으로 되어있어 발생하는 TypeError를 PostMapping으로 수정하였습니다.
> fix: 사업자 등록번호 잘못된 요청 매핑 어노테이션 수정

- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
- src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
- src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
- close #1268
- 회원가입 과정에서 학과를 입력하지 않을 경우, 이메일 인증과정에서 오류가 발생하는 것을 해결했습니다.
- 입력하지 않은 경우, 인증 로직에서 department를 조회하는 로직을 제외시켰습니다.
- 추가로, 사용자의 학번이 없는 경우 시간표 강의 추가 과정에서 이수구분을 추가하는 로직에서 NPE가 발생하는 부분도 해결했습니다.
> fix: 학과를 입력하지 않고 회원가입을 할 경우 발생한 오류 해결

- src/main/java/in/koreatech/koin/domain/owner/model/OwnerEventListener.java
- src/main/java/in/koreatech/koin/global/domain/slack/model/SlackNotificationFactory.java
- close #1279 
1. 가게 가입시 슬랙 알림에 가게이름 안나오는 오류를 수정했습니다.
2. redis에 저장해놓기 때문에 이를 통해 출력되도록했습니다.
> fix: 가게 가입시 슬랙 알림에 가게이름 안나오는 오류 수정

- src/main/java/in/koreatech/koin/domain/owner/controller/OwnerApi.java
- src/main/java/in/koreatech/koin/domain/owner/controller/OwnerController.java
- src/test/java/in/koreatech/koin/acceptance/OwnerApiTest.java
- close #1297
1. ModelAttribute를 삭제하고 RequestBody추가
> fix: 사업자 등록번호 중복 검증 필드 미인식 문제 해결

- src/main/java/in/koreatech/koin/domain/ownershop/controller/OwnerEventApi.java
- src/main/java/in/koreatech/koin/domain/ownershop/dto/OwnerShopEventsResponse.java
- close #1300 
1. QA에서 이벤트를 최신순으로 정렬해서 보여달라는 의견 수렴
> refactor: QA에서 이벤트를 최신순으로 정렬해서 보여달라는 의견 수렴

- src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
- src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
- src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureUpdateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
- timetable 졸학계 로직을 주석처리 했습니다.
> fix: 졸학계 로직 주석 처리

- src/main/java/in/koreatech/koin/domain/timetableV2/dto/request/TimetableLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV2/factory/TimetableLectureCreator.java
- src/main/java/in/koreatech/koin/domain/timetableV2/model/TimetableLecture.java
- src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureCreateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV3/dto/request/TimetableRegularLectureUpdateRequest.java
- src/main/java/in/koreatech/koin/domain/timetableV3/service/TimetableRegularLectureServiceV3.java
- 프로덕션 배포 이후, 주석처리를 진행한 부분을 롤백했습니다. [주석 PR](https://github.com/BCSDLab/KOIN_API_V2/pull/1316)
> fix: 졸학계 로직 주석 처리 원복

- src/main/java/in/koreatech/koin/domain/bus/service/model/route/ShuttleBusRouteStrategy.java
- src/main/java/in/koreatech/koin/domain/bus/service/shuttle/ShuttleBusRepository.java
- close #이슈번호
1. 셔틀버스 도착 시각이 출발 시각으로 출력되는 버그를 수정했습니다.
> hotfix: 셔틀버스 도착 시각 수정 (main)

- src/main/java/in/koreatech/koin/domain/graduation/service/GraduationService.java
- close #1354 
1. 원래 catalog의 학점을 기준으로 학생이 들은 학점을 계산했었는데 이를 시간표에서의 학점을 기준으로 계산하게 변경했습니다.
> refactor: 졸학계 학점 계산을 시간표에 있는 학점을 기준으로 계산하게 변경

- src/main/java/in/koreatech/koin/admin/land/controller/AdminLandController.java
- src/main/java/in/koreatech/koin/admin/land/dto/AdminLandResponse.java
- src/main/java/in/koreatech/koin/admin/land/service/AdminLandService.java
- src/main/java/in/koreatech/koin/domain/land/model/Land.java
- close #1365 
1. `double size = null` 의 구조라 NPE 발생
2. `double -> Double` 로 변환 (primitive type을 wrapper class로 boxing)
3. 간단한 코드 순서 정렬
> fix: admin land NPE 해결

- src/main/java/in/koreatech/koin/domain/student/service/StudentService.java
- 학적 정보 업데이트 과정에서 department가 null 값이 들어올 경우, NPE가 터지는 부분을 해결했습니다
> hotfix : 학적 정보 업데이트 NPE 해결 (main)

- src/main/java/in/koreatech/koin/web/config/SwaggerGroupConfig.java
- close #1400 
- 패키지 정리로 인해 스웨거 그룹화 설정 파일 경로를 수정했습니다.
- 소켓 API 그룹을 추가했습니다.
> fix: 스웨거 그룹화 설정 파일 수정

- .github/assign_label_reviewers.yml
- src/main/java/in/koreatech/koin/_common/apiloadbalancer/ApiLoadBalance.java
- src/main/java/in/koreatech/koin/_common/apiloadbalancer/ApiLoadBalancer.java
- src/main/java/in/koreatech/koin/domain/bus/service/cache/BusCacheService.java
- src/main/java/in/koreatech/koin/domain/bus/service/express/client/PublicExpressBusClient.java
- src/main/java/in/koreatech/koin/domain/bus/service/express/client/StaticExpressBusClient.java
- src/main/java/in/koreatech/koin/domain/bus/service/express/client/TmoneyExpressBusClient.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserApi.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/dto/PhoneCheckExistsRequest.java
- src/main/java/in/koreatech/koin/domain/user/exception/DuplicationPhoneNumberException.java
- src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
- src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
- src/main/java/in/koreatech/koin/integration/email/exception/DuplicationEmailException.java
- src/test/java/in/koreatech/koin/acceptance/UploadServiceTest.java
- src/test/java/in/koreatech/koin/acceptance/UserApiTest.java
- src/test/java/in/koreatech/koin/fixture/UserFixture.java
- close #1403 
1. 중복 전화번호 검증 api를 작성했습니다.
> feat: 중복 전화번호를 검증한다.

- src/main/java/in/koreatech/koin/domain/banner/controller/BannerCategoryApi.java
- src/main/java/in/koreatech/koin/domain/banner/controller/BannerCategoryController.java
- src/main/java/in/koreatech/koin/domain/banner/dto/response/BannerCategoriesResponse.java
- src/main/java/in/koreatech/koin/domain/banner/repository/BannerCategoryRepository.java
- src/main/java/in/koreatech/koin/domain/banner/service/BannerCategoryService.java
- src/main/java/in/koreatech/koin/integration/s3/controller/UploadApi.java
- src/test/java/in/koreatech/koin/acceptance/BannerCategoryApiTest.java
- close #1417 
- Normal 배너 조회 API를 추가했습니다.
- 관련 테스트 코드 추가했습니다.
- 업로드 API 스웨거 설명을 수정했습니다.
> feat: Normal 배너 조회 API 추가

- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- close #1419 
- 누락된 map import를 추가하였습니다
> fix: 누락된 import추가

- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- close #1421 
- stage 반영 후 성능이 기대치만큼 나오지 않아 수정사항을 롤백했습니다.
- 다시 찾아보겠습니다
> fix: 인기 게시글 조회 로직 롤백

- .github/workflows/pr-check-title.yml
- .github/workflows/pr-reviewers-by-label.yml
- close #1425 
1. fix: pr title refactor 제한 추가
> fix: pr title refactor 제한 추가

- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- close #1423 
- 새 로직을 다시 적용했습니다
기존로직 latency
새 로직 latency
- 제가 스테이지 끼리 비교안하고 프로덕션이랑 비교를해서 혼동했습니다...
- 확실한 성능 향상이 있는 것으로 보입니다.
- 스테이지 서버 생각보다 안좋네요..
> refactor: 인기 게시글 조회 새 로직 적용

- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- close #1454 
1. 어드민 분리로 인해 Article 엔티티에 ToOne 관계로 Koin Article이 추가됨
2. 이에 따라 n+1문제가 재발생한 것을 koin article을 페치조인에 포함시켜 개선
- 1줄
> refactor: fetch join에 koinNotice 추가

- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- close #1456 
1. hot article의 다른 부분에도 KoinNotice를 fetch join에 추가할 필요가 있어서 수정했습니다.
(두 부분 중 하나 누락했었음)
- 1줄
> refactor: fetch join에 koinNotice 추가2

- src/main/java/in/koreatech/koin/domain/user/dto/validation/CheckLoginIdDuplicationRequest.java
- src/main/java/in/koreatech/koin/web/config/SwaggerGroupConfig.java
- close #이슈번호
1. 스웨거 유저팀 그룹에 Department API를 추가하였습니다.
> fix: Department 스웨거 문서 추가

- src/main/java/in/koreatech/koin/admin/user/service/AdminUserService.java
- src/main/java/in/koreatech/koin/admin/user/validation/AdminUserValidation.java
- src/main/java/in/koreatech/koin/domain/coop/service/CoopService.java
- src/main/java/in/koreatech/koin/domain/owner/service/OwnerValidator.java
- src/main/java/in/koreatech/koin/domain/user/controller/UserController.java
- src/main/java/in/koreatech/koin/domain/user/model/User.java
- src/main/java/in/koreatech/koin/domain/user/repository/UserRepository.java
- src/main/java/in/koreatech/koin/domain/user/service/UserService.java
- src/main/java/in/koreatech/koin/domain/user/service/UserValidationService.java
- close #1482 
1. 유저 회원가입 시 중복이메일을 체크
2. 구조 통일
3. invert method 수정
> fix: 유저 회원가입 시 중복이메일을 체크한다.

- src/main/java/in/koreatech/koin/domain/student/model/redis/UnAuthenticatedStudentInfo.java
- src/main/resources/db/migration/V149__remove_phone_number_hyphens.sql
- close #1503
1. DB 전화번호 하이픈 삭제했습니다.
> feat: 전화번호 하이픈 삭제

- src/main/java/in/koreatech/koin/infrastructure/s3/client/CloudFrontClientWrapper.java
- close #1550
- 현재 정보로는 오류 원인을 파악하기 어려워 로깅을 추가했습니다.
- 2줄
> feat: CloudFront 캐시 무효화 로깅 추가

- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
- close #1555 
- (Noraml) 카테고리 별 동아리 조회 API 오류 수정했습니다. 
- hitSort의 기본값이 없어서 발생하는 NPE를 수정했습니다.
> fix: (Noraml) GET /clubs NPE 해결

- src/main/java/in/koreatech/koin/admin/club/controller/AdminClubApi.java
- src/main/java/in/koreatech/koin/admin/club/controller/AdminClubController.java
- src/main/java/in/koreatech/koin/admin/club/dto/response/AdminClubManagersResponse.java
- src/main/java/in/koreatech/koin/admin/club/dto/response/AdminNewClubResponse.java
- src/main/java/in/koreatech/koin/admin/club/dto/response/AdminPendingClubResponse.java
- src/main/java/in/koreatech/koin/admin/club/service/AdminClubService.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubManagerEmpowermentRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/QnaCreateRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubCategoriesResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
- close #1557 
1. SnakeCase가 없던 Response들에 SnakeCase를 추가하고, 형식을 일치시켰습니다.
지노님이 올리신 아래 이미지에 관련해서, path를 바꿀까요? 고민 중에 있습니당.
관련 스레드는 옆의 링크로! [슬랙](https://bcsdlab.slack.com/archives/C08G8GG7D0F/p1747547190261979)
> chore: 동아리 API SnakeCase 추가 및 형식 일치

- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubRepository.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
- close #1564 
- 카테고리 미 선택 시 동아리 전체 조회가 되도록 추가했습니다.
> feat: 동아리 카테고리 미 선택 시 동아리 전체 조회 추가

- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/controller/ClubController.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubLikeRepository.java
- src/main/java/in/koreatech/koin/domain/club/service/ClubService.java
- close #1574
1. 그럼 동아리 상세조회랑 카테고리조회 부분 좋아요 여부 추가
> fix: 반환값 좋아요 여부 추가

- src/main/java/in/koreatech/koin/infrastructure/s3/model/ImageUploadDomain.java
- close #1578 
- 동아리 이미지 업로드 도메인을 추가했습니다
> feat: 코인 동아리 이미지 업로드 도메인 추가

- src/main/java/in/koreatech/koin/admin/club/dto/response/AdminPendingClubResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
- src/main/java/in/koreatech/koin/domain/club/model/redis/ClubCreateRedis.java
- close #1587 
1. 누락된 동아리 역할 부분을 추가했습니다
> fix: 동아리 생성 요청/어드민 동아리 상세조회 역할 필드 추가

- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
- close #1589 
- GET /clubs 응답값 스네이크 케이스를 적용했습니다.
> feat: GET /clubs 응답값 스네이크 케이스 적용

- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubsByCategoryResponse.java
- close #1597 
- 동아리 조회 시 응답값에 좋아요 숨김 여부를 추가 했습니다
> feat: 동아리 조회 응답값 좋아요 숨김 여부 추가

- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubCreateRequest.java
- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubManagerDecideRequest.java
- src/main/java/in/koreatech/koin/admin/club/dto/request/AdminClubModifyRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubCreateRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubIntroductionUpdateRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubManagerEmpowermentRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubUpdateRequest.java
- src/main/java/in/koreatech/koin/domain/club/model/redis/ClubCreateRedis.java
- close #1604 
- 코인 동아리 API 요청 DTO 유효성 검증 어노테이션을 수정했습니다.
- 이전 작업에서 잘못 참조한 메소드를 수정했습니다.
> fix: 코인 동아리 API 요청 DTO 유효성 검증 어노테이션 수정

- src/main/java/in/koreatech/koin/domain/shop/model/order/ShopBaseDeliveryTip.java
> fix: ShopBaseDeliveryTip 수정

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- src/test/java/in/koreatech/koin/admin/acceptance/AdminNoticeApiTest.java
> hotfix: article API 패치조인 작업 롤백 (main)

- src/main/java/in/koreatech/koin/domain/notification/repository/NotificationSubscribeRepository.java
- src/main/java/in/koreatech/koin/domain/notification/service/NotificationService.java
- src/main/java/in/koreatech/koin/domain/shop/service/ShopService.java
- src/main/java/in/koreatech/koin/socket/domain/notification/service/NotificationSubscribeReader.java
- close #1634
1. 상위 알림 (식단) 구독 저장이 안되는 오류 해결
> hotfix: 상위 알림 구독 수정 (develop)

- src/main/java/in/koreatech/koin/domain/shop/model/menu/MenuOrigin.java
- src/main/resources/db/migration/V165__update_shop_menu_origin_column_type.sql
> refactor: TEXT 타입 매핑 수정

- src/main/resources/db/migration/V174__update_coopshop_timatable_25_summer.sql
- close #1670
1. 2025년 생협 하계 시간표로 변경하였습니다
혹시나 오탈자 있으면 알려주세여
> fix: 25-하계방학 생협시간표 업데이트

- src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
- src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
- src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
- src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
- src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopController.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shopinfo/OrderableShopDeliveryResponse.java
- src/main/java/in/koreatech/koin/domain/order/shop/service/OrderableShopInformationService.java
-  #1696
1. API 단순 분리
2. swagger 문서화 수정
> feat: 결제 페이지 검증 & 상점 배달 정보 API 분리

- src/main/java/in/koreatech/koin/_common/code/ApiResponseCode.java
- src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
- src/main/java/in/koreatech/koin/domain/order/cart/controller/CartController.java
- src/main/java/in/koreatech/koin/domain/order/cart/dto/CartPaymentSummaryResponse.java
- src/main/java/in/koreatech/koin/domain/order/cart/dto/CartResponse.java
- src/main/java/in/koreatech/koin/domain/order/cart/model/Cart.java
- src/main/java/in/koreatech/koin/domain/order/cart/service/CartQueryService.java
> feat: 장바구니 포장/배달 응답 분리

- src/main/java/in/koreatech/koin/domain/club/controller/ClubApi.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubBaseInfo.java
- close #1748 
- 동아리 조회 과정에서 발생하는 NPE를 수정했습니다.
- INVALID_REQUEST_PAYLOAD 에러 코드를 추가했습니다.
임시로 일단 저렇게 작업했고, ClubListQueryRepository에 작성된 코드를 추가 공부하면서 수정해보겠습니다.
> fix: 동아리 조회 API 오류 수정

- src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/menu/OrderableShopMenusResponse.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shopinfo/OrderableShopInfoSummaryResponse.java
- src/main/java/in/koreatech/koin/domain/order/shop/model/domain/OrderableShopInfoSummary.java
- src/main/java/in/koreatech/koin/domain/order/shop/repository/OrderableShopRepository.java
- src/main/java/in/koreatech/koin/domain/order/shop/service/OrderableShopInformationService.java
> feat: 상점 요약 정보 조회 API 이미지 목록 반환 & 주석 삭제

- src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopMenuApi.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/menu/OrderableShopMenusResponse.java
- #1756 
1. "is_sold_out" 응답값 추가
> feat: 상점 메뉴 조회 API 품절 응답값 추가

- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubEventResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubHotStatusResponse.java
- close #1758 
- snake case 누락을 추가했습니다.
- 선착순
> chore: snakecase 누락추가

- src/main/java/in/koreatech/koin/domain/user/verification/controller/UserVerificationController.java
- src/main/java/in/koreatech/koin/domain/user/verification/service/UserVerificationService.java
- close #이슈번호
1. 컨트롤러와 서비스의 인자 순서를 맞췄습니다.
- 기존
- 컨트롤러의 삽입 순서: request.email, reqeust.code, ipAddress
- 서비스가 받는 순서: request.email, ipAddress, request.code
> fix: 인자 순서 변경

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- src/test/java/in/koreatech/koin/acceptance/admin/AdminNoticeApiTest.java
> hotfix: 게시글 조회 로직 revert (main)

- src/main/java/in/koreatech/koin/domain/community/article/model/Article.java
- src/main/java/in/koreatech/koin/domain/community/article/repository/ArticleRepository.java
- src/main/java/in/koreatech/koin/domain/community/article/service/ArticleService.java
- src/test/java/in/koreatech/koin/acceptance/admin/AdminNoticeApiTest.java
> hotfix: 게시글 조회 로직 revert (develop)

- src/main/java/in/koreatech/koin/domain/user/model/User.java
- src/main/resources/db/migration/V203__seperate_user_table.sql
- close #1812
1. 익명 닉네임 초기화
2. 영양사 정보 유지
> fix: 익명 닉네임 초기화 및 영양사 정보 유지

- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubEventCreateRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/request/ClubEventModifyRequest.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubEventResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubEventsResponse.java
- src/main/java/in/koreatech/koin/domain/club/dto/response/ClubRecruitmentResponse.java
- src/main/java/in/koreatech/koin/domain/club/enums/ClubRecruitmentStatus.java
- src/main/java/in/koreatech/koin/domain/club/enums/ClubSortType.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubBaseInfo.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubRecruitment.java
- src/main/java/in/koreatech/koin/domain/club/model/ClubRecruitmentDday.java
- src/main/java/in/koreatech/koin/domain/club/repository/ClubListQueryRepository.java
> release: 캠퍼스 동아리 2차 스프린트 QA 수정사항 반영

- src/main/java/in/koreatech/koin/domain/order/cart/controller/CartApi.java
- src/main/java/in/koreatech/koin/domain/order/cart/dto/CartItemsCountSummaryResponse.java
- src/main/java/in/koreatech/koin/domain/order/shop/controller/OrderableShopApi.java
- src/main/java/in/koreatech/koin/domain/order/shop/dto/shoplist/OrderableShopCategoryFilterCriteria.java
> fix: 비즈니스 QA 수정

- src/test/java/in/koreatech/koin/unit/domain/address/DeliveryAddressValidatorTest.java
- src/test/java/in/koreatech/koin/unit/domain/cart/CartServiceTest.java
- src/test/java/in/koreatech/koin/unit/domain/cart/CartTest.java
- src/test/java/in/koreatech/koin/unit/domain/community/lostitem/chatroom/service/LostItemChatRoomInfoServiceTest.java
- src/test/java/in/koreatech/koin/unit/domain/order/ShopOpenScheduleServiceTest.java
- src/test/java/in/koreatech/koin/unit/domain/user/model/UserTest.java
- src/test/java/in/koreatech/koin/unit/domain/user/verification/model/VerificationCodeTest.java
- src/test/java/in/koreatech/koin/unit/domain/user/verification/model/VerificationCountTest.java
- src/test/java/in/koreatech/koin/unit/fixture/AddressFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/AdminFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/CartFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/CartMenuItemFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/LostItemArticleFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/LostItemChatFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/OrderableShopFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/OrderableShopMenuFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/OrderableShopOpenInfoFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/OwnerFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/StudentFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/UserFixture.java
- src/test/java/in/koreatech/koin/unit/fixture/VerificationFixture.java
* 디렉토리명 오타수정
---
* 디렉토리명 fixutre -> fixture로 수정
---
* PR 올라간 상태로 브런치명 바꾸면 PR 자동으로 내려가네요.....🥲
* 첫 PR입니다
---
> refactor: fixutre 디렉토리명 fixture로 수정

- src/main/resources/db/migration/V213__add_25-2nd_shuttle_bus.sql
* 
- close #이슈번호
---
* 25년 2학기 셔틀버스 업데이트 flyway 추가했습니다.
---
* 
---
> feat: 25년 2학기 셔틀버스 업데이트 flyway 추가

- src/main/java/in/koreatech/koin/domain/address/client/AddressClient.java
- src/main/java/in/koreatech/koin/domain/address/client/RoadNameAddressApiErrorCodeConverter.java
- src/main/java/in/koreatech/koin/domain/address/client/RoadNameAddressClient.java
- src/main/java/in/koreatech/koin/domain/address/service/AddressValidator.java
- src/main/java/in/koreatech/koin/domain/address/service/RoadNameAddressValidator.java
- src/main/java/in/koreatech/koin/domain/order/address/controller/AddressController.java
- src/main/java/in/koreatech/koin/domain/order/address/dto/RoadNameAddressApiResponse.java
- src/main/java/in/koreatech/koin/domain/order/address/service/AddressSearchOpenApiService.java
- src/main/java/in/koreatech/koin/domain/order/address/service/CampusAddressSearchService.java
- src/main/java/in/koreatech/koin/domain/order/delivery/dto/UserOffCampusDeliveryAddressRequest.java
- src/main/java/in/koreatech/koin/domain/order/delivery/model/OffCampusDeliveryAddress.java
- src/main/java/in/koreatech/koin/domain/shop/model/shop/Shop.java
- src/main/java/in/koreatech/koin/global/code/ApiResponseCode.java
- src/main/resources/db/migration/V215__alter_table_add_column_user_delivery_address.sql
- src/main/resources/db/migration/V216__alter_table_shops_add_column_address_detail.sql
- src/test/java/in/koreatech/koin/unit/domain/address/RoadNameAddressValidatorTest.java
- src/test/java/in/koreatech/koin/unit/fixture/AddressFixture.java
- close #1927 
---
- 주소 포맷을 위와 같이 통일합니다. 
- 바뀐 주소 포맷 대응을 위해 `shops` 테이블과 `user_delivery_address` 테이블에 컬럼을 추가했습니다.
- 수정 전
```json
{
"zip_number": "31253",
"si_do": "충청남도",
"si_gun_gu": "천안시 동남구",
"eup_myeon_dong": "병천면",
"road": "충절로",
"building": "",
"detail_address": "에듀윌 301호",
"full_address": "충청남도 천안시 동남구 병천면 충절로 1628-17 에듀윌 301호"
}
```
- 수정 후
```json
{
"zip_number": "31253",
"si_do": "충청남도",
"si_gun_gu": "천안시 동남구",
"eup_myeon_dong": "병천면",
"road": "충절로",
"building": "",
"address": "충청남도 천안시 동남구 병천면 충절로 1628-17",
"detail_address": "에듀윌 301호"
}
```
```java
/**
* 외부 주소 검색 API를 호출하여 주소의 유효성을 검증한다. 외부 API 오류 발생시 예외를 반환하지 않고 검증을 통과한 것으로 처리한다.
* @param address 주소(상세 주소를 제외한 기본 주소. 예: 충청남도 천안시 동남구 병천면 충절로 1600)
* @throws CustomException 주소 검색 결과가 0개 이하일 경우 유효하지 않은 주소로 판단한다.
*/
public void …
```
> feat: 외부 API 주소 검증 컴포넌트 추가 & 주소 포맷 통일

- src/main/java/in/koreatech/koin/domain/order/order/dto/response/InprogressOrderResponse.java
* order/in-progress API 반환값으로 paymentId를 추가하였습니다.
- close #1975 
---
* 반환값에 paymentId가 추가 되었습니다.
---
* 
---
- [] 테스트 코드 포함됨
> feat: paymentId 반환값 추가
